### ISSUE TITLE
[BaekJoon] 다리 놓기

### ISSUE THREAD

**Issue by haesoooo** [SSAFY12th/ssafyAlgostudy#106]
## 문제 링크
https://www.acmicpc.net/problem/1010

## 풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

## 풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by reasonyi** [comment]
문제 링크
#112 

풀이 사항
풀이 일자: 2024.08.12
풀이 시간: 27분 26초
채점 결과: 정답
예상 문제 유형: DP
시간: 124 ms
메모리: 15040 kb

풀이 방법
직접 손으로 그려가며 DP 배열의 점화식을 찾는다. 
![image](https://github.com/user-attachments/assets/6790e70f-ad73-4dbd-862e-dfdf840dc912)
내가 찾은 점화식은 dp[n][m] = dp[n][m-1] + dp[n-1][m-1]로, 그대로 문제에 적용하여 풀어주면 풀린다.
주의할 점은 초기화를 반드시 해줄 것.
초기화는 n=1일 때, 해당 행은 열의 값을 따라간다는 것.

**Comment by sangholee235** [comment]
### 문제 링크
#97 
### 풀이 사항
풀이 일자 : 240812
풀이 시간 :  10분
채점 결과 : 정답
예상 문제 유형 : 다이나믹 프로그래밍
시간 : 120 ms
메모리 : 14416 kb
### 풀이 방법
점화식 : dp[x][y] = dp[x-1][y-1]  + dp[x-1][y]
메모제이션 기법으로 모든 디피테이블을 채워둔뒤 요구되는 좌표의 디피값을
출력하는 형태로 풀이했다

**Comment by chanu2** [comment]
### 문제 링크
#118 
### 풀이 사항
풀이 일자 : 240812
풀이 시간 :  40분
채점 결과 : 정답
예상 문제 유형 : 수학
시간 : 280 ms
메모리 : 18232kb
### 풀이 방법
처음에 nCr 이지만 c최대 30이라면 문제가 된다.
고등학교 때 배운 공식 n!/((n-r)! * r!) 그렇지만 n 이 30 이면 문제가 된다.  그래서 다른 공식을 적용했다. 
30C28 이라면 -> 30C2로 바꾸고 ->   n*(n-1)*(n-1) .... / (r!)   ->  (30 * 29)/2!

**Comment by kro46** [comment]
## 문제 링크
#128 

## 풀이 사항
풀이 일자 : 240813
풀이 시간 : 1시간
채점 결과 : 정답
예상 문제 유형 : 수학
시간 : 164 ms
메모리 : 14540kb

## 풀이 방법
 - nCr 은 (n * n-1 * n-2 * ... * r+1) / r! 으로 단순화 가능
 - r+1~n 을 담은 배열 arr1 , 1~r 까지 담은 배열 arr2를 선언
 - 두 배열의 끝부터 비교해가며 arr1의 원소가 arr2의 원소로 나누어 떨어지면 arr1 = arr1/arr2, arr2 = 1로 변환해해줌
 - 모든 나누기 과정이 끝나면 각 배열의 모든 원소를 곱해 mul1 , mul2에 저장
 - 마지막으로 mul1/mul2를 수행하여 최종 값 출력

**Comment by haesoooo** [comment]
### 문제 링크
#105 
### 풀이 사항
풀이 일자 : 240808
풀이 시간 :  17분
채점 결과 : 정답
예상 문제 유형 : 수학
시간 : 120 ms
메모리 : 14264 kb

### 풀이 방법
재귀로는 안되더라.. 오버플로우 발생
N! / { R! * (N - R)! } 공식을 활용하면 됩니당
5C2 라고 할 때 5 * 4 / 2 * 1 하는 것처럼
N - R번만 연산하면 된다

**Comment by kimjuheee** [comment]
문제 링크
#132 

### 풀이 사항
풀이 일자 : 240813
풀이 시간 : 2시간
채점 결과 : 정답
예상 문제 유형 : 조합
시간 : 304ms
메모리 : 21140KB

### 풀이 방법
- arr[a][b]가 이미 계산된 경우 저장된 값을 반환한다.
- a==b이거나 b==0인 경우 1일 반환한다. (aCa, bCb = 1)
- 위 두가지 경우가 아니라면 combination(a,b)(=combination(a-1,b-1)+combination(a-1,b)) 출력한다.
