### ISSUE TITLE
[BackJoon] 모든 순열

### ISSUE THREAD

**Issue by kimdevspace** [SSAFY12th/ssafyAlgostudy#141]
# 문제 링크
https://www.acmicpc.net/problem/10974

# 풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

# 풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by kimdevspace** [comment]
### 문제 링크
#140 
### 풀이 사항
풀이 일자 : 240822
풀이 시간 : 5분
채점 결과 : 정답
예상 문제 유형 : 완전 탐색
시간 : 순열 알고리즘 -> 1800ms,  NextPermutation 알고리즘 -> 1688ms
메모리 : 순열 알고리즘 -> 65248kb, NextPermutation 알고리즘 -> 54740kb 
### 풀이 방법
순열 알고리즘은 n개의 수 중 n개를 뽑는 nPn 알고리즘을 사용했습니다~ 시간복잡도는 O(n!), n이 최대 8이므로 제한 시간 안에는 가능합니다!

NextPermutation알고리즘은 어떤 순열의 다음 순열을 구하는 알고리즘인데
만약 문제에서 어떤 순열의 다음 순열을 구하라!! 는 문제가 있을 때
수열을 나열해서 만들 수 있는 순열을 모두 구해서 한 순열의 다음 순열을 구하는 방법을 떠올릴 수 있어요. 하지만 순열을 모두 구하게 되면 너무 비효율 적입니다.
NextPermutation알고리즘으로 O(n)의 시간복잡도로 다음 순열을 구할 수 있어요!
- NextPermutation의 순서
1. 수열 정렬하기
2. 꼭대기 값(제일 큰 값) 다음 값을 오른쪽부터 찾아 줍니다.
3. 꼭대기 값(제일 큰 값) 이전 값 중 가장 큰 값을 찾아 줍니다. 
4. 두 위치 교환!
5. 꼭대기 위치부터 맨 뒤까지 오름차순으로 정렬해줍니다.

**Comment by sangholee235** [comment]
### 문제 링크
#140 
### 풀이 사항
풀이 일자 : 240823
풀이 시간 : 30분
채점 결과 : 정답
예상 문제 유형 : 브루트 포스
시간 :  1660ms
메모리 : 53224kb 
### 풀이 방법
nextPermutation 수업을 못들어서 인터넷 참고해서 공부한 뒤 풀이 했습니다
제가 이해한 내용으로는
1. 맨뒤부터 증가하는 부분을 찾는다 ex) 4 5
2. 그 부분을 피벗으로 그 뒷부분에서 맨 마지막부터 피벗보다 큰 수를 찾는다
3. 찾았으면 swap 한뒤 피벗부터 끝까지 오름차순 정렬
4. 증가하는 부분을 찾다가 0에 닿으면 ex) 5 4 3 2 1 더이상 진행 할 필요가 없으니 종료

**Comment by reasonyi** [comment]
### 문제 링크
#153 

### 풀이 사항
풀이 일자 : 240828
풀이 시간 : 13분 38초
채점 결과 : 정답
예상 문제 유형 : Next Permutation
시간 :  1696ms
메모리 : 55,840 kb

### 풀이 방법
Next Permutation을 이용하여 풀이하였음.
1. 수열을 만들 배열 정렬
2. 뒤에서부터 앞의 수보다 큰 값 i 찾기
3. 뒤에서부터 i-1값보다 크면서 가장 작은 값 j 찾기
4. i-1과 j swap
5. i부터 맨 뒤까지 오름차순 정렬

**Comment by chanu2** [comment]
### 문제 링크
#158 
### 풀이 사항
풀이 일자 : 240822
풀이 시간 : 10분
채점 결과 : 정답
예상 문제 유형 : 완전 탐색
시간 :  223ms
메모리 : 22184kb 
### 풀이 방법

np 인줄 모르고 그냥 순열로 풀었습니다. 다음번에 공부해 보겠습니다!

**Comment by kro46** [comment]
## 문제 링크

#167 

## 풀이 사항
풀이 일자 : 240828
풀이 시간 : 15분
채점 결과 : 정답
예상 문제 유형 : 순열/Next Permutation
시간 : 1732ms
메모리 : 63084kb

## 풀이 방법
dfs와 visited 배열을 사용한 일반 순열과 Next Permutation 두 가지로 구현해 보았는데 입력 값이 크지 않아서
시간 차이가 많이 나진 않았다.

**Comment by kimjuheee** [comment]
### 문제 링크
#170 

### 풀이 사항
- 풀이 일자 : 240828
- 풀이 시간 : 30분
- 채점 결과 : 정답
- 예상 문제 유형 : 순열
- 실행시간 : 1588ms
- 메모리 : 66344KB

### 풀이 방법
- 기저 조건으로 재귀의 깊이가 N이 되었을 경우 설정
- visited 배열로 방문 안 했다면 방문 처리 해주고 res에 수 담아주고 한 단계 더 재귀

**Comment by haesoooo** [comment]
### 문제 링크
#166  

### 풀이 사항
- 풀이 일자 : 240828
- 풀이 시간 : 20분
- 채점 결과 : 정답
- 예상 문제 유형 : 순열
- 실행시간 : 1712ms 
- 메모리 :  54,952kb 

### 풀이 방법
- np와 visited를 이용한 방법 두가지로 풀어보았습니다. 확실히 np가 시간 측면에서 효율적임
