### ISSUE TITLE
[SWEA] 수영장

### ISSUE THREAD

**Issue by kimdevspace** [SSAFY12th/ssafyAlgostudy#144]
문제 링크
https://swexpertacademy.com/main/code/problem/problemSolver.do?contestProbId=AV5PpFQaAQMDFAUq

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
실행 시간 :
메모리 : 

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by reasonyi** [comment]
# 문제 링크
#146 

# 풀이 사항
풀이 일자: 2024.08.27
풀이 시간: 2시간
채점 결과: 정답
예상 문제 유형: DFS/DP
시간: 111 ms
메모리: 19,476 kb

# 풀이 방법
dfs를 써야하는건 알겠는데, 3개월치를 계산할 때 어떻게 해야 좋을지 잘 생각이 안나서 푸는데 시간이 오래걸렸다.
간단하게 생각하면
1. 현재 달에서 3개월치를 결제한다.
2. 현재 달에서 1달 또는 하루권으로 최소비용이 나오는 것으로 결제한다.
둘 중 하나만 해주고 결제한 금액에 맞춰 cnt를 +3 또는 +1로 해주면 바로 구할 수 있다....
선택하거나 or 안하거나

처음에 수영장 이용 계획을 받을 때, 하루권과 한달권 중 무엇이 더 싼지 미리 저장해둔다.

**Comment by sangholee235** [comment]
### 문제 링크
#145 
### 풀이 사항
- 풀이 일자 : 240825
- 풀이 시간 : 7분 47초 20
- 채점 결과 : 정답
- 예상 문제 유형 : DFS
- 실행 시간 : 166ms
- 메모리 : 19,248kb

### 풀이 방법
- 최악의 경우 : 1년치를 사버리는 경우로 두고
- 현재 달에 이용계획이 있다면, 1일치, 1달치, 3달치 구매를 DFS를 탐색
- 최소 가격 갱신
- 어디서 본 문제랑 비슷해서 금방 했습니다

**Comment by chanu2** [comment]
### 문제 링크
#157  
### 풀이 사항
- 풀이 일자 : 240828
- 풀이 시간 : 15분 10초
- 채점 결과 : 정답
- 예상 문제 유형 : dfs, 백트레킹
- 실행 시간 : 139ms
- 메모리 : 19,248kb

### 풀이 방법
- 현재 달에 이용계획이 있다면, 1일치, 1달치, 3달치 구매를 DFS를 탐색
- 12월을 넘어가면 종료

**Comment by kro46** [comment]
## 문제 링크
#163 

## 풀이 사항
풀이 일자 : 240823
풀이 시간 : 1시간
채점 결과 : 정답
예상 문제 유형 : dfs
실행 시간 : 275ms
메모리 : 20060kb
## 풀이 방법
1. 1일 요금을 내는 경우와 1달 요금을 내는 경우 , 3달 요금을 내는 경우를 나누어 조건을 주고 DFS를 순회
2. 만약 3가지 경우를 통과했는데 값이 12달 요금보다 비싸면 12달 요금으로 최소 값 갱신

**Comment by kimjuheee** [comment]
### 문제 링크
#169 

### 풀이 사항
- 풀이 일자 : 240827
- 풀이 시간 : 3시간
- 채점 결과 : 정잡
- 예상 문제 유형 : dfs
- 실행시간 : 154ms
- 메모리 : 23924KB

### 풀이 방법
- 1일, 월간, 3개월로 요금을 내는 경우에 따라 각각 DFS 실행
- 기저 조건으로 12개월을 넘어가게 되면 최소 비용 갱신

**Comment by haesoooo** [comment]
### 문제 링크
#156
### 풀이 사항
- 풀이 일자 : 240827
- 풀이 시간 : 1시간 20분
- 채점 결과 : 정답
- 예상 문제 유형 : dfs
- 실행 시간 : 116ms
- 메모리 : 18,600kb
### 풀이 방법
- 1일, 1개월, 3개월에 대한 비용을 dfs로 계산한다
- 이용 계획이 없는 달은 skip
- 1년 비용으로 최솟값을 지정해둔다
