### ISSUE TITLE
[SWEA] 벽돌 깨기

### ISSUE THREAD

**Issue by sangholee235** [SSAFY12th/ssafyAlgostudy#148]
문제 링크
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWXRQm6qfL0DFAUo

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
실행 시간 :
메모리 : 

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by sangholee235** [comment]
### 문제 링크
#147 
### 풀이 사항
풀이 일자 : 240827
풀이 시간 : 40 분
채점 결과 : 정답
예상 문제 유형 : 완전탐색 (중복순열) + 구현
시간 :  1,015 ms
메모리 : 86,908 kb
### 풀이 방법
1. 공이 어떤 열에 몇개 떨어질지를 중복 순열로 탐색
2. plans배열에 plans[몇번째 공] = 떨굴 열 로 나눠서 저장
3. 공의 개수를 채울때마다 구현 되어있는 시뮬레이션에 돌린 후 남은 블럭 개수 갱신

**Comment by reasonyi** [comment]
# 문제 링크
#146 

# 풀이 사항
풀이 일자: 2024.08.27
풀이 시간: 2시간 41분
채점 결과: 정답
예상 문제 유형: DFS/BFS/중복순열
시간: 348 ms
메모리: 90,764 kb

# 풀이 방법
처음에 중복순열을 생각 못해서 dfs과정에서 뻘짓함
SWEA에서는 중복순열이 아니라 순열로 풀어도 정답처리됨. 뭐임????

- map저장 시 전체 블럭 개수를 미리 더해 저장해둔다.
- dfs로 어떤 열을 터트릴지 n만큼 중복순열을 뽑는다.
- 중복순열이 뽑히면, 맵 원본을 복사하여 copyMap에 저자아고, 중복 순열 순서대로 해당하는 열의 맨 위 블럭을 터트린다.

터트리는 과정
- 중복순열에서 터트릴 열을 하나씩 가져온다.
- 현재 열에서 가장 위의 블럭을 찾는다.
- 만약 맨 위 블럭이 없다면 break
- 가장 위의 블럭을 터트린다. (bfs를 활용하여 연쇄적으로 터지는 블럭을 모두 처리한다.)
- 남은 블럭을 전부 아래로 내린다.

블럭을 전부 터트렸다면, 전체 블럭 수에서 터진 블럭 수를 빼내어 최소값과 비교한다.
만약 최소값이 이미 0이되었다면 dfs탐색을 그만한다. (가지치기)

**Comment by kimdevspace** [comment]
### 문제 링크
#161 
### 풀이 사항
- 풀이 일자 : 240828
- 풀이 시간 : 설계 30분, 디버깅 1시간30분
- 채점 결과: 정답
- 예상 문제 유형 : 완탐(중복순열) + 시뮬레이션
- 시간 : 434ms
- 메모리 : 86.128kb
### 풀이 방법
1. 공의 개수만큼 중복순열로 공이 떨어질 열 인덱스 뽑기 (경우의 수 하나 뽑았을 때 마다 시뮬레이션 해야 하니까 맵을 복사해서 쓰기)
2. 시작 좌표 찾아서 벽돌 부수기(bfs시뮬레이션)
3. 벽돌 내리기 (스택 자료구조 사용했음)
4. 개수 세기

#### 어려웠던점
bfs 가 안돼서 계속 코드 찾아보다가 Point 클래스 생성자 매개 변수 순서가 바뀌어 있어서 허탈했습니다..
블록 내리는 거 구현할 때 블록의 개수를 세어 싹 0으로 바꾸고 개수만큼 밑에서 1로 채웠는데 블록은 1부터 9까지 숫자가 존재해서 잘 안됐다.
블록 내리는거 스택으로 구현하는 연습 많이 해보기

**Comment by kro46** [comment]
## 문제 링크
#168 

## 풀이 사항
풀이 일자 : 240828
풀이 시간 : 설계 30분, 디버깅 4시간
채점 결과: 정답
예상 문제 유형 : 중복순열 + DFS or BFS + 시뮬레이션
시간 : 1367ms
메모리 : 91620kb
## 풀이 방법
떨어지는 폭탄 수 만큼 중복 순열로 폭탄을 떨어트릴 위치를 선정 - Perm() / DFS
시작 좌표 찾기 - boom()
벽돌 부수고 퍼트리기 - spread() / BFS 
중간에 떠 있는 벽돌 아래로 내려주기 - clean() (스택 자료구조 사용했음)

어려웠던점
1. map을 깊은 복사 해야한다는 점.
2. 맵의 크기를 처음에 습관적으로 N x N을 받아서 디버깅할 때 문제가 되었음-> 원인을 못찾아서 여기서 2시간 뺏김ㅋㅋㅋ
3. 문제를 보면 최소 블록 개수를 찾는게 목표인데, 나는 최소한으로 블록을 없애는게 목표인줄 알고 계속 알고리즘을 고침;; -> 여기서 또 2시간 걸림
4. 입출력을 확실히 작성하고 문제를 똑바로 읽자! ㅠㅠ

**Comment by chanu2** [comment]
### 문제 링크
#173 
### 풀이 사항
- 풀이 일자 : 240829
- 풀이 시간 : 1시간 50분 
- 채점 결과: 정답
- 예상 문제 유형 : 중복순열 + 시뮬레이션
- 시간 : 981ms
- 메모리 : 86.128kb
### 풀이 방법
1. 공의 개수만큼 중복순열로 공이 떨어질 열 인덱스 뽑기
2. 시작 좌표 찾아서 벽돌 십자가 형태로 부수기 
3. 벽돌 내리기
4. 개수 세기

#### 어려웠던점
map 요소들을 더하는거를 ++한게 아니라 그 값을 더해서 너무 오래 헤맸다.. 사소한것도 잘 봐야겠다
