### ISSUE TITLE
[BaekJoon] 좋다

### ISSUE THREAD

**Issue by sangholee235** [SSAFY12th/ssafyAlgostudy#152]
문제 링크
https://www.acmicpc.net/problem/1253

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
실행 시간 :
메모리 : 

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by sangholee235** [comment]
# 문제 링크
#151 

# 풀이 사항
풀이 일자: 2024.08.27
풀이 시간: 1시간 
채점 결과: 정답
예상 문제 유형: 완전탐색 인줄 알았지
시간: 168 ms
메모리: 15148 kb


# 풀이 방법
투 포인터 개념을 학습 후 풀이 하였음
1. 양 끝점 부터 포인터를 잡고
2. 현재 포인터 인덱스 덧셈이 타겟보다 크면 오른쪽 포인터를 감소
3. 현재 포인터 인덱스 덧셈이 타겟보다 작으면 왼쪽 포인터를 증가
4. 왼쪽 포인터가 오른쪽 포인터를 넘어가면 찾을 수가 없음
5. 답을 찾으면 count ++

**Comment by reasonyi** [comment]
# 문제 링크
#155 

# 풀이 사항
풀이 일자: 2024.08.28
풀이 시간: 1시간 2분
채점 결과: 정답
예상 문제 유형: 투포인터
시간: 152 ms
메모리: 14,756 kb


# 풀이 방법
처음에 a를 받을 배열의 크기를 1,000,000,001로 잡았다가 메모리 조건 초과됨
음수가 들어올 수 있다는 것을 고려하지 않아 계속해서 실패함.

음수가 들어올 수 있으니 처음부터 모든 범위의 수를 더해볼 것을 고려해야한다!!!!

- a는 정렬한다.
- start는 0, end는 n-1을 가리키고 시작한다.
- 만약 start 혹은 end가 현재 수를 가리키고 있다면, 다음 수를 가리켜 시작하도록 한다.
- start보다 end가 클때만 반복.
- start번째 + end번째 = sum이 현재값과 같고 현재값를 더한게 아니라면 result++ 후 break
- 다르다면 sum이 큰 경우 end--, sum이 작은경우 start++

**Comment by kro46** [comment]
## 문제 링크

#164 

## 풀이 사항
풀이 일자: 2024.08.27
풀이 시간: 30분
채점 결과: 정답
예상 문제 유형: 이분 탐색/ 투 포인터
시간: 152 ms
메모리: 14852 kb

## 풀이 방법
이분탐색과 투 포인터에 대한 강의를 먼저 보고 코드를 작성하였음

양 끝점 부터 포인터를 잡고 타겟이 된 원소를 제외한 다른 2개의 원소를 선택(left , right)
현재 포인터 인덱스 덧셈이 타겟보다 크면 오른쪽 포인터를 감소
현재 포인터 인덱스 덧셈이 타겟보다 작으면 왼쪽 포인터를 증가
답을 찾으면 count ++

**Comment by chanu2** [comment]
# 문제 링크
#171 

# 풀이 사항
풀이 일자: 2024.08.28
풀이 시간: 45분
채점 결과: 정답
예상 문제 유형: 투포인터
시간: 164 ms
메모리: 15,113 kb


# 풀이 방법

음수가 들어올 수 있으니 처음부터 모든 범위의 수를 더해볼 것을 고려해야한다!!!!

- 배열 정렬 정렬한다.
- left는 0, right는 n-1을 가리키고 시작한다.
- 자기 자신을 가르킨다면 인덱스 left-- or right++
- left보다 right가 클때만 반복.
- start번째 + end번째 == sum 성립하면 break
- 클 때 작을 때를 비교해서 left++ 하거나 right--

**Comment by kimdevspace** [comment]
### 문제 링크
#172 
### 풀이 사항
- 풀이 일자 : 240829
- 풀이 시간 : 45분
- 채점 결과 : 정답
- 예상 문제 유형 : 투 포인터
- 시간 : 152ms
- 14,876kb
### 풀이 방법
- 배열 정렬
- 배열을 돌면서 target을 정함.
- start 는 0, end는 N -1을 가리키고 시작.
- 만약 자기 자신을 가르키면 인덱스 조정!

**Comment by kimjuheee** [comment]
### 문제 링크
https://github.com/SSAFY12th/ssafyAlgostudy/commit/04e3b5d52bfae4a1b655083d0f642eb5bdf9d7cc

### 풀이 사항
- 풀이 일자 : 240829
- 풀이 시간 : 1시간 15분
- 채점 결과 : 정답
- 예상 문제 유형 : 투포인터
- 시간 : 168ms
- 메모리 : 15028KB

### 풀이 방법
- left, right로 왼쪽, 오른쪽 포인터 설정
- right 포인터는 음수값이 존재할 수 있으므로 'N-1'로 설정
- 현재 숫자를 가리킨다면 포인터 이동
- 두 숫자의 합으로 나타낼 수 없다면 break
- 두 숫자의 합으로 나타낼 수 있다면 좋다 ~~ !

**Comment by haesoooo** [comment]
### 문제 링크
#165

### 풀이 사항
- 풀이 일자 : 240829
- 풀이 시간 : 40분
- 채점 결과 : 정답
- 예상 문제 유형 : 이분탐색, 투포인터
- 시간 : 160ms
- 메모리 : 14708KB

### 풀이 방법
- left보다 right idx가 클 때까지, 각 idx에 해당하는 값을 더해서 타겟 값과 비교한다.
- 이 때, left랑 right는 타겟 인덱스와 동일하면 안되고 더한 값이 타겟 값보다 크면 오른쪽 idx를 옮기고, 타겟 값보다 작으면 왼쪽 idx를 옮긴다.
