### ISSUE TITLE
[SWEA] 간단한 소인수분해

### ISSUE THREAD

**Issue by haesoooo** [SSAFY12th/ssafyAlgostudy#16]
### 문제 링크
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV5Pl0Q6ANQDFAUq

### 풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

### 풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by haesoooo** [comment]
### 문제 링크
#15 

### 풀이 사항
풀이 일자: 2024.07.22
풀이 시간: 15분
채점 결과: 정답
예상 문제 유형: 수학

### 풀이 방법
- 2, 3, 5, 7, 11 총 5개의 소수를 인수로 가지는 소인수분해
- N과 5개의 소수 각각에 대해 모듈러 연산
- 나머지가 0일 때 N을 해당 소수로 나눠주고, 지수 증가

**Comment by chanu2** [comment]
### 문제 링크

#21 

### 풀이 사항
풀이 일자: 2024.07.25
풀이 시간: 14분
채점 결과: 정답
예상 문제 유형: 수학, 구현

### 풀이 방법
- 각각을 변수로 선언 while문을 돌면서 각 수로 나누어 떨어지면 해당 변수 ++

**Comment by kimdevspace** [comment]
### 문제링크
#22 
### 풀이사항
풀이 일자 : 240725
풀이 시간 : 14분25초
채점 결과 :정답
예상 문제 유형 : 수학, 구현

### 풀이 방법
- 입력받은 수를 소인수 분해하여 소인수들을 배열의 인덱스로 삼아 누산 해줬습니다~

**Comment by reasonyi** [comment]
문제 링크
#23 

풀이 사항
풀이 일자: 2024.07.25
풀이 시간: 17분 41초
채점 결과: 정답
예상 문제 유형: 수학

풀이 방법
2, 3, 5, 7, 11을 int 배열에 넣고, 지수를 넣을 배열을 추가로 만들어준다.
2, 3, 5, 7, 11으로 n을 나눴을 때, 나누어 떨어지면 지수값을 ++해준다.
1이 남을 때까지 무한반복

**Comment by kro46** [comment]
## 문제 링크
https://github.com/SSAFY12th/ssafyAlgostudy/pull/24

## 풀이 사항
풀이 일자: 2024.07.25
풀이 시간: 20분
채점 결과: 정답
예상 문제 유형: 수학, 구현

## 풀이 방법
각각을 변수로 선언 while(N !=1)까지 돌면서 각 수로 나누어 떨어지면 해당 변수 ++

**Comment by JuHeeKim-joy** [comment]
### 문제 링크

#26 

### 풀이 사항
풀이 일자 : 2024.07.25
풀이 시간 : 36분
채점 결과 : 정답
예상 문제 유형 : 수학 문제

### 풀이 방법
입력받은 수를 while로 돌면서 각각의 수로 소인수분해하기

**Comment by chanu2** [comment]
close
