### ISSUE TITLE
[SWEA] 벌꿀채취

### ISSUE THREAD

**Issue by reasonyi** [SSAFY12th/ssafyAlgostudy#178]
# 문제 링크
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV5V4A46AdIDFAWu

# 풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

# 풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by reasonyi** [comment]
# 문제 링크
#177 

# 풀이 사항
풀이 일자: 2024.09.03
풀이 시간: 4시간 삽질하다 테케 오류 발견.... 이후 풀이시간 17분
채점 결과: 정답
예상 문제 유형: 구현/DFS/부분집합
시간: 120 ms
메모리: 20,468 kb

# 풀이 방법
같은 행에서 두 일꾼이 벌통을 채취할 수 있도록 코드를 구성하면, 50개의 테스트 케이스 중 49개만 통과됨.
이때문에 삽질한참하다... 다른 행에서만 선택 가능하도록 다시 코드를 구성하니 통과되었음......

풀이 방법
1. 한 행에서 연속적으로 m개의 벌통을 선택했을 때, c를 고려하면서 가장 많은 벌꿀을 채취할 수 있는 경우를 구하여 maxList에 저장.
2. c를 고려하면서 가장 많은 벌꿀을 채취할 수 있는 경우는 부분집합으로 구함.
3. 구한 maxList를 정렬하여 가장 큰 값 2개를 선택한다.

**Comment by kimdevspace** [comment]
### 문제 링크
#187 
### 풀이 사항
- 풀이 일자 : 240903
- 풀이 시간 : 6시간
- 채점 결과 : 정답
- 예상 문제 유형 : 완탐, 구현
- 시간 : 119ms
- 메모리 : 20,496ms
### 풀이 방법
/*
1. 이중 for문으로 2차원 배열에서 m개만큼 뽑는다.
2. m개 중 최댓값을 뽑아줌. dfs로
   dfs
     IF SUM > C return
     IF CNT == M return;
     다음 열을 더해주는 경우
     더해주지 않고 하나만 뽑는 경우
     둘다 cnt + 1
3. 일꾼 1의 최댓값을 뽑았으면 일꾼 2의 최댓값을 뽑아야 함.
    같은 열이라면 ! 자기 자신이 포함되지 않도록 하기위해 j열을 +M 만큼 미루고 시작
    다른 열이라면 0 부터 시작
    일꾼 2의 최댓값을 뽑아줌.
4. 둘이 더해서 최댓값 갱신.
 */

**Comment by kro46** [comment]
## 문제 링크
#188 

## 풀이 사항
풀이 일자: 2024.09.03
풀이 시간: 이틀..?
채점 결과: 정답
예상 문제 유형: 구현/DFS/부분집합
시간: 210 ms
메모리: 44584 kb

## 풀이 방법
두 일꾼의 영역을 구할 때 하나의 열에 두 일꾼이 모두 존재할 수 있도록 
첫 번째 일꾼이 차지한 마지막 인덱스를 두 번째 일꾼 영역 구할때 넘겨줌.(1번 일꾼의 행/열 값을 dfs의 인자로) 
두 번째 일꾼은 넘겨받은 인자 바로 다음 인덱스부터 접근(이러면 두 일꾼의 영역이 겹치지 않음)
 1. 첫 번째 일꾼의 영역 구하기 -> dfs 와 리스트 사용
 2. 두 번째 일꾼의 영역 구하기 -> dfs 와 리스트 사용
 3. 각 영역에서 원소의 합이 C를 넘지 않는 조합에서 얻을 수 있는 최대 꿀의 양 구하기 
 -> 부분집합( sum<C이면 return시킴 : 가지치기)
 5. 두 영역의 값을 더해서 max값 갱신(값을 더해서 max값을 갱신하는 부분은 두번째 일꾼의 영역 선택이 끝났을 때 수행)
* 키포인트 :일꾼 영역을 구할 때, col + M이 j 보다 크면 i 가 자동으로 +1되고 이 부분을 체크해서  j는 0으로 초기화한다.

**Comment by sangholee235** [comment]
### 문제 링크
#189
### 풀이 사항
- 풀이 일자 : 240903
- 풀이 시간 : 2시간
- 채점 결과 : 정답
- 예상 문제 유형 : 완전탐색, 구현
- 시간 : 126 ms
- 메모리 : 20,212ms
### 풀이 방법
1. 각 인덱스에서 M만큼 영역까지 최대 벌꿀 채취량 구하기 ( DFS ) 
2. 두 일꾼이 겹치지 않게 인덱스 선택하는 경우 고르기 ( 그냥 4중 포문 써서 억지로 구함 )
3. 그 값이랑 현재 최소값과 비교

**Comment by chanu2** [comment]
# 문제 링크
#192 

# 풀이 사항
풀이 일자: 2024.09.03
풀이 시간: 1시간 55분
채점 결과: 정답
예상 문제 유형: 구현/DFS
시간: 256ms
메모리: 35,404 kb

# 풀이 방법
- 2차원 배열에서 좌표 2개 조합으로 뽑는다.
-  뽑은 좌표들을 m만큼 각자 이동 시켜 리스트에 저장
-  리스트에 같은 좌표가 있으면 종료
-  리스트 내부 값을 부분집합을 통해서 최댓값 갱신

**Comment by haesoooo** [comment]
# 문제 링크
#183 

# 풀이 사항
풀이 일자: 2024.09.03
풀이 시간: 1시간 30분 + (같은 줄 고려하는 코드로 수정하는 데 1시간) = 2시간 30분
채점 결과: 정답
예상 문제 유형: DFS, 구현, 조합, 부분집합
시간: 132ms
메모리: 22,880 kb

# 풀이 방법

--- 기존 풀이 (일꾼 두 명은 각자 다른 행에서만 일한다. 왜 맞았지 ?) ---
- CombiRow() : 전체 행 N개 중 2개를 뽑는다. 
-  CombiHoney() : 뽑은 2개의 행에 대해서 각 행마다 M개를 연속해서 선택할 수 있는지 확인하고 dfs를 각각 돌린다. 0부터 N - M + 1까지 확인하면 된다. M개의 cell을 honey에 저장하고 dfs 돌린다
- dfs() : 부분집합으로 각 cell을 택할지 말지 나눠서 돌리고, limit이 C를 넘어가는 순간 종료시킨다. 그리고, depth가 honey의 크기에 도달했다면 최댓값을 계산하고 종료한다

-> '같은 행에 대해서도 두 명의 일꾼이 같이 일할 수 있다.' 는 조건 고려하여 다시 풀이
- 기존 코드에서, SameRow() 함수 추가, 각 행마다 돌린다
- SameRow() : 일단 N (행) 크기가 2 * M 사이즈보다 커야 가능하니까 체크하기.
- 만족할 경우, j부터~ j+M 까지 첫번째 일꾼이 꿀 저장하고 dfs, 이후 j + M부터 이후 M 개에 대해서는 두번째 일꾼이 꿀 저장

**Comment by kimjuheee** [comment]
### 문제 링크🍯 
#207 

### 풀이 사항
- 풀이 일자 : 240902
- 풀이 시간 : 3일 ...
- 채점 결과 : 정답
- 예상 문제 유형 : 구현, DFS, 조합
- 시간 : 165 ms
- 메모리 : 23468KB

### 풀이 방법
- 두 명의 일꾼이 채취할 벌통을 DFS로 선택하여 가능한 모든 조합을 탐색
- 선택된 벌통이 같은 줄에 있는지 확인
- 각 일꾼의 벌통에서 꿀을 채취할 수 있는 최적의 조합을 구해 최대 꿀 계산
