### ISSUE TITLE
[SWEA] 탈주범 검거

### ISSUE THREAD

**Issue by reasonyi** [SSAFY12th/ssafyAlgostudy#179]
# 문제 링크
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV5PpLlKAQ4DFAUq

# 풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

# 풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by reasonyi** [comment]
# 문제 링크
#184 

# 풀이 사항
풀이 일자: 2024.09.03
풀이 시간: 46분 19초
채점 결과: 정답
예상 문제 유형: 구현/BFS
시간: 149 ms
메모리: 24,744 kb

# 풀이 방법
- 처음 맨홀의 위치부터 bfs로 시간을 고려하여 탐색한다.
- 탐색 시간이 지나면 종료한다.
- 탐색 시, 현재 파이프의 모양에 따라 상하좌우 중 어느 방향으로 갈 수 있는지에 주의한다.
- 현재 파이프에서 다음 파이프로 이동할 때, 이동하려는 방향과 다음 파이프의 모양이 맞는지 확인하여 이동한다.

**Comment by sangholee235** [comment]
# 문제 링크
#176 

# 풀이 사항
풀이 일자: 2024.09.02
풀이 시간: 57분 26초
채점 결과: 정답
예상 문제 유형: BFS / 구현
시간: 248 ms
메모리: 25,516 kb

# 풀이 방법
1. BFS 탐색 진행
2. 진행 하는 과정에서 파이프를 고려해서 진행 가능한 방향을 고려
3. 진행 가능하다면 거리를 기록
4. 주어진 시간 이하의 값이 기록 된 거만 골라서 개수 카운팅 ㅅㄱ

**Comment by chanu2** [comment]
# 문제 링크
#193 

# 풀이 사항
풀이 일자: 2024.09.04
풀이 시간: 1시간
채점 결과: 정답
예상 문제 유형: 구현/BFS
시간: 160 ms
메모리: 26,560 kb

# 풀이 방법
- 처음 맨홀의 위치부터 bfs
- poll한 파이프 모양을 기준으로 방향을 탐색
- 탐색 하고 방향이 맞으면 queue에 넣고 break;
- 시간이 다 지났으면 종료

**Comment by haesoooo** [comment]
# 문제 링크
#191

# 풀이 사항
풀이 일자: 2024.09.04
풀이 시간: 2시간
채점 결과: 정답
예상 문제 유형: BFS, 구현
시간: 139 ms
메모리: 25,412 kb

# 풀이 방법
- R, C를 pair 좌표로 저장해둔다.
- bfs() : 현재 좌표의 map값에 대해 if문으로 검사하며 1~7 각각에 대해 "다음 좌표가 범위 내 && 방문 X && 다음 좌표 cell이 0이 아닐 경우" 상, 하, 좌, 우 함수를 돌림 (1은 상하좌우, 2는 상하 .. )
- up(), down(), right(), left() : up 함수는 더 up 가능한지 봐야 함 (1,2,4,7번은 더 가능) down은 1,3,6,7 ... 
- 그런 식으로, 더 가능하다면 다음 cell도 방문 true로 하고 queue에 넣어준다
- bfs 처음에 queue size를 누적해서 더하고 시간 지났을 때 출력


 노가다 전문가로서, 노가다로 풀었읍니다.. bfs 는 거들 뿐 ..

**Comment by kro46** [comment]
## 문제 링크
#198 

## 풀이 사항
풀이 일자: 2024.09.04
풀이 시간: 1시간 44분
채점 결과: 정답
예상 문제 유형: 구현/BFS
시간: 142 ms
메모리: 26,084 kb

## 풀이 방법
처음 맨홀의 위치부터 bfs : L-1만큼 반복
poll한 파이프 모양과 방향 그리고 다음 파이프로 올 수 있는 모든 경우를 검사
-> 디버깅만 1시간 넘게 쓴듯;(4,5,6,7번 파이프는 자기 자신이 다음 파이프로 올수 없다는 점을 1시간 디버깅 하고 깨달음)
탐색 하고 방향이 맞으면 queue에 넣고 break;
시간이 다 지났으면 종료

**Comment by kimdevspace** [comment]
### 문제 링크
#204 
### 풀이 사항
- 풀이 일자 : 240905
- 풀이 시간 : 1시간 20분
- 채점 결과 : 정답
- 예상 문제 유형 : 시뮬레이션
- 시간 : 127ms
- 메모리 : 26,124kb
### 풀이 방법
1. 처음 위치에서 출발
   고려해야 할건 현재 파이프( 숫자 ) 에 따라 어느 방향으로 탐색할 수 있는지, 다음 탐색할 좌표가 현재 좌표와 연결 되어 있는지 확인,
2. 탐색 할 때 초를 늘려 L초 까지만 탐색!
3. 탐색 가능할 때마다 +1 해주기
