### ISSUE TITLE
[SWEA] 무선 충전

### ISSUE THREAD

**Issue by reasonyi** [SSAFY12th/ssafyAlgostudy#180]
# 문제 링크
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWXRDL1aeugDFAUo

# 풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

# 풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by reasonyi** [comment]
# 문제 링크
#195 

# 풀이 사항
풀이 일자: 2024.09.04
풀이 시간: 2시간 56분
채점 결과: 정답
예상 문제 유형: 구현
시간: 150 ms
메모리: 23,744 kb

# 풀이 방법
1. A와 B의 위치를 이동시킨다.
2. A와 B의 현재 위치에서 선택 가능한 충전기 종류를 찾아 각각 List에 저장한다.
3. A를 먼저 선택 후, B를 선택하는 경우 / B를 먼저 선택 후, A를 선택하는 경우 / 둘 중 하나만 선택하는 경우 (A, B)각각 을 고려하여 선택 후, 계산하는 함수 호출. (완전탐색으로 최대값을 찾는다.)
4. 같은 충전기를 쓰는 경우 각각 반씩 사용하는 것에 유의한다.

**Comment by sangholee235** [comment]
# 문제 링크
#197 

# 풀이 사항
풀이 일자: 2024.09.04
풀이 시간: 35분
채점 결과: 정답
예상 문제 유형: 구현
시간: 196 ms
메모리: 21,948 kb

# 풀이 방법
1. 무선충전기 정보를 클래스로 관리한다
2. 만든 클래스형 리스트로 무선 충전기 정보를 관리한다
3. 사용자가 충전기 범위에 들어있는지 확인하는 메서드를 만든다
4. 범위 안에 사용자가 들어오면 파워를 계산하고
5. 같은 무선 충전기위에 올라와있다면 둘 중 하나의 값만 더해준다
6. 같은 충전기에 없다면 두 충전량을 다 올린다.

**Comment by chanu2** [comment]
# 문제 링크
#201 

# 풀이 사항
풀이 일자: 2024.09.05
풀이 시간: 1시간 15분
채점 결과: 정답
예상 문제 유형: 구현
시간: 159 ms
메모리: 23,810 kb

# 풀이 방법
- 충전소를 리스트에 모두 저장
-  A와 B의 위치를 이동시킨다.
-  A와 B의 현재 위치에서 선택 가능한 충전기를 각각의 리스트에 저장
- 이중 for문으로 충전의 최댓값을 저장 
- 결과에 최대값을 더해준다

**Comment by haesoooo** [comment]
# 문제 링크
#205

# 풀이 사항
풀이 일자: 2024.09.05
풀이 시간: 1시간 40분
채점 결과: 정답
예상 문제 유형: 구현
시간: 151 ms
메모리: 21,480 kb

# 풀이 방법
- 충전소의 좌표, 범위, 효율을 담는 클래스 BC 생성
- 충전소들을 저장할 BC 배열 생성
- 총 이동횟수만큼 for문을 돌면서 A와 충전소 각각과의 거리, B와 충전소간의 거리를 모두 계산하여 범위 내에 있다면 A, B 리스트에 해당 충전소를 저장
- 리스트에 들어 있는 충전소들 (범위 내에 있는 충전소들) 을 효율이 큰 순서로 정렬한다.
- 이후, A 리스트와 B 리스트에 대해서 가장 효율이 큰 원소가 다르면 그냥 각각 sum에 더하고, 같으면 1개일 때랑 1개 초과일 때를 나눠서 비교한다
- 이동한다

A 리스트랑 B 리스트에 원소가 1개일 때랑 2개 이상일 때랑 뭐 그런거 비교하는게 어려웠다.. 그리고 리스트 정렬하는거를 compareTo 오버라이딩해서 구현했는데 그게 많이 어려웠따.. 자바는 어려워 ~~~~
