### ISSUE TITLE
[SWEA] 핀볼 게임

### ISSUE THREAD

**Issue by sangholee235** [SSAFY12th/ssafyAlgostudy#213]
# 문제 링크
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWXRF8s6ezEDFAUo

# 풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

# 풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by sangholee235** [comment]
# 문제 링크
#210

# 풀이 사항
풀이 일자: 2024.09.06
풀이 시간: 1시간 30분
채점 결과: 정답
예상 문제 유형: 단순 구현
시간: 2,545 ms
메모리: 113,980 kb

# 풀이 방법
1. 블랙홀 좌표와, 웜홀 좌표를 리스트로 관리
2. 0인 지점에서 상하좌우 모두 핀볼 쏴보고 점수 갱신 !
3. 방향을 고정하고, 블랙홀을 만나거나 초기위치를 만나지 않으면 반복
4. 블록을 만났을경우, 벽을 만났을경우 고려하여 방향 변환
5. 웜홀을 만났을 경우, 같은 웜홀 번호를 갖고있지만 , x y가 다른 웜홀 (이러면 짝 웜홀임) 을 찾아서 그 웜홀로 이동

**Comment by kimdevspace** [comment]
### 문제 링크
#221 
### 풀이 사항
- 풀이 일자 : 240910
- 풀이 시간 : 2시간
- 채점 결과 : 정답
- 예상 문제 유형 : DFS로 할랬는데 스택오버플로우난다고 해서 구현으로 함 (시뮬레이션)
- 시간 : 1,340ms
- 메모리 : 43.608kb
### 풀이 방법
스킬
- nextDir 2차원 배열을 이용해 현재 이동 방향에 따라서 꺾이는 방향 도출하기
풀이
-웜홀인 것들 리스트에 저장.
- map에서 0인 지점들 에서 출발하는 4방향 모두 시뮬레이션 하기
- 블랙홀을 만나거나 제자리로 돌아오면 break
- 블록에 부딪히거나 좌표 범위에 부딪히면 score++
- 웜홀을 만났을 때 웜홀 리스트 순회하면서 좌표 값이 같고 r 또는 c값이 다르면 좌표 변경!

**Comment by kro46** [comment]
## 문제 링크
#223 

## 풀이 사항
풀이 일자: 2024.09.11
풀이 시간: 2시간 30분
채점 결과: 정답
예상 문제 유형: 단순 구현
시간: 1,401 ms
메모리: 46,188kb

## 풀이 방법
시작 가능 위치와 웜홀 좌표를 리스트로 관리
모든 시작 가능 위치에서 상하좌우로 모두 핀볼 쏴보고 점수 누적
방향을 고정하고, 블랙홀을 만나거나 초기위치를 만나지 않으면 반복
블록을 만났을 경우, 벽을 만났을 경우 고려하여 방향 변환
웜홀을 만났을 경우, 같은 번호는 같고 r c가 다른 웜홀로 핀볼 이동
한 방향에 대한 핀볼의 이동이 끝나면 max 값 갱신

**Comment by chanu2** [comment]
### 문제 링크
#229 
### 풀이 사항
- 풀이 일자 : 240912
- 풀이 시간 : 2시간 25분
- 채점 결과 : 정답
- 예상 문제 유형 : 시뮬레이션
- 시간 : 1,269 ms
- 메모리 : 44,568 kb
### 풀이 방법

- hashMap을 통해서 갈 수 있는 방향을 모두 저장.
- map에서 0인 지점들 에서 출발하는 4방향 모두 탐색
- 블랙홀을 만나거나 제자리로 돌아오면 break
- 블록에 부딪히거나 좌표 범위에 부딪히면 cnt++
- 웜홀을 마주치면 리스트에서 비교후에 좌표를 초기화 해준다.

**Comment by haesoooo** [comment]
### 문제 링크
#226 

### 풀이 사항
- 풀이 일자 : 240912
- 풀이 시간 : 2시간
- 채점 결과 : 정답
- 예상 문제 유형 : 시뮬레이션
- 시간 : 920 ms
- 메모리 : 43,220 kb
### 풀이 방법
- 6 이상의 값을 받을 때 웜홀을 쌍으로 저장하고자 [5][2] 크기의 좌표쌍 배열 생성
- 배열 값이 0일 때 -> 상,하,좌,우에 대해서 각각 탐험
- 탐험 ) 
  -  진행하다가, 벽이면 현재 방향 바꾸고, cnt++하고 좌표도 바꿔준다 (현 좌표 -> 벽 찍고 -> 다시 현 좌표)
  - 블랙홀 만나면 끝낸다
  - 다시 시작 좌표로 돌아오면 끝난다 (벽 체크보다 나중에 체크해야함)
  - 진행한 cell 이 6 이상이면 좌표 확인해서 다른 쌍으로 좌표 바꿔줌 (웜홀)
  - 1~5에 대해서 cnt++하고 각각 방향 변경해줌 (벽돌)
- 최댓값 갱신
