### ISSUE TITLE
[SWEA] 보물상자 비밀번호

### ISSUE THREAD

**Issue by sangholee235** [SSAFY12th/ssafyAlgostudy#214]
# 문제 링크
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWXRUN9KfZ8DFAUo

# 풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

# 풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by sangholee235** [comment]
# 문제 링크
#211

# 풀이 사항
풀이 일자: 2024.09.06
풀이 시간: 35분 12초
채점 결과: 정답
예상 문제 유형: 구현
시간: 259 ms
메모리: 28,256 kb

# 풀이 방법
1. 한변에 몇개가 들어가는지 계산 N / 4
2. 그 사이즈 만큼 비밀번호 추출 해서 Set 자료구조에 저장 (중복 방지)
3. 회전해서 저장
4. passwordSet을 List에 담아서 정렬 후 K-1 번째 값 출력

**Comment by kro46** [comment]
## 문제 링크
#218 

## 풀이 사항
풀이 일자: 2024.09.08
풀이 시간: 45분
채점 결과: 정답
예상 문제 유형: 구현
시간: 124 ms
메모리: 20,332 kb

## 풀이 방법
1. 입력받은 문자열의 0~N/4번 인덱스를 잘라서 해당 문자열 뒤에 붙임
2. 0번 인덱스부터 N-1번 인덱스까지 돌면서 N/4 씩 잘라서 String str에 저장
3. 저장된 String을 parseInt(str,16)으로 10진수 변환 -> List에 저장
4. 이 전에 같은 값을 저장한 적이 없으면 List에 저장, 아니면 continue
5. 모든 반복을 끝내고 Collections.sort(list , Collections.reverseOrder()) 로 내림차순 정렬
6. List의 K-1번째 값을 출력

**Comment by kimdevspace** [comment]
### 문제 링크
#222 
### 풀이 사항
- 풀이 일자 : 240910
- 풀이 시간 : 30분
- 채점 결과 : 정답
- 예상 문제 유형 : 구현
- 시간 : 177ms
- 메모리 : 22,212kb
### 풀이 방법
- 입력받은 문자열을 N / 4 만큼 잘라서 String으로 해준 후,
- Integer.parseInt(자른 문자열, 16) 으로 변경하여 set에 넣어준 후,
- set을 List로 변환하여 내림차순 정렬,
- k-1번째 수 출력

**Comment by reasonyi** [comment]
# 문제 링크
#225 

# 풀이 사항
풀이 일자: 2024.09.12
풀이 시간: 48분
채점 결과: 정답
예상 문제 유형: 구현
시간: 140 ms
메모리: 21,924 kb

# 풀이 방법
문제가 어려워서,,, 문제 이해하는데 시간을 계속 쓰다가? 그마저도 이해 못해서 GPT로 겨우 이해함 
- 처음에 문자열 받아서 회전시킬 때 편하게 하기 위해 LinkedList사용하여 문자열을 하나씩 잘라 넣어줌.
- n/4번 회전하면서 n/4번씩 잘라서 10진수로 변환하여 HashSet에 넣어줌.
- 시계 방향 회전(마지막 요소 첫 번째에 넣어주기)
- 회전이 끝나면 HashSet을 List로 바꿔서 내림차순 정렬 후 k번째로 큰 값 출력.

**Comment by chanu2** [comment]
# 문제 링크
#228 

# 풀이 사항
풀이 일자: 2024.09.06
풀이 시간: 47분 
채점 결과: 정답
예상 문제 유형: 구현
시간: 109 ms
메모리: 18,596 kb


# 풀이 방법
1. 한변에 몇개가 들어가는지 계산 N / 4
2. 그 사이즈 만큼 비밀번호 추출 해서 set으로 중복제거
3. 회전해서 저장
4. set을 List에 담아서 정렬 후 K-1 번째 값 출력

**Comment by haesoooo** [comment]
# 문제 링크
#228 

# 풀이 사항
풀이 일자: 2024.09.06
풀이 시간: 40~50분 
채점 결과: 정답
예상 문제 유형: 구현
시간: 217 ms
메모리: 27,788kb


# 풀이 방법
1. 맵 썼음
2. 한 칸에 들어갈 문자 개수 (eachCnt = N  / 4)
3. 받은 문자열에서 한 글자씩 저장하다가 eachCnt 개수만큼 저장하면 그 문자를 맵에 저장
4. 회전 : N/4 - 1번 돌리면 된다. [(j + 1) % N] = j 이 방법 톱니바퀴 문제에서 배운 이후로 유용하게 써먹음 ㅎㅎ
5. 배열에 담아서 정렬하고 했는데 이부분에서 스트림을 썼는데 잘 몰라서 구글링 함 .. ㅋㅋ
