### ISSUE TITLE
[BOJ] 파이프 옮기기 1

### ISSUE THREAD

**Issue by sangholee235** [SSAFY12th/ssafyAlgostudy#215]
# 문제 링크
https://www.acmicpc.net/problem/17070

# 풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

# 풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by sangholee235** [comment]
# 문제 링크
#212

# 풀이 사항
풀이 일자: 2024.09.06
풀이 시간: 12분
채점 결과: 정답
예상 문제 유형: DFS
시간: 220 ms
메모리: 16,892 kb

# 풀이 방법
1. 3개의 모드로 분기하여 DFS 탐색
2. 갈 수 없는 방향으로 회전이면 가지치기
3. x y 좌표를 파이프의 끝 좌표로 계산
4. 1,2 부터 탐색하여 N,N에 닿으면 answer++

**Comment by kimdevspace** [comment]
### 문제 링크
#219 

### 풀이 사항
풀이 일자: 2024.09.06
풀이 시간: 45분 00초
채점 결과: 정답
예상 문제 유형: DFS
시간: 248ms
메모리: 22,084kb

### 풀이 방법
45도씩 꺾어서 이동 가능하기 때문에
1. 우로 가는 경우 : 우, 우하 범위 체크 및 1 체크
2. 하로 가는 경우 : 하, 우하 범위 체크 및 1 체크
3. 우하로 가는 경우 :  우하, 우, 하 범위 체크 및 1 체크
조건이 참 일때만 dfs를 돌고,  N, N 좌표에 도달했을 때 ans++

**Comment by kro46** [comment]
## 문제 링크
#220 

## 풀이 사항
풀이 일자: 2024.09.10
풀이 시간: 1시간 10분
채점 결과: 정답
예상 문제 유형: DFS
시간: 664 ms
메모리: 35372kb

## 풀이 방법
r,c 좌표와 방향(d)을 주고 DFS 탐색
방향에 따라 이동할 수 있는 길이 다르기 때문에 각 방향에 맞게 이동할 수 있도록 if문으로 분기
EX) 현재 방향이 가로이면 가로 방향과 대각선 방향으로만 이동할 수 있게 분기
방향에 맞고 해당 길이 벽(1)이 아니면 DFS 계속 진행
0,1 부터 탐색하여 N-1,N-1에 닿으면 count++

**Comment by reasonyi** [comment]
# 문제 링크
#224 

# 풀이 사항
풀이 일자: 2024.09.12
풀이 시간: 1시간
채점 결과: 정답
예상 문제 유형: DFS
시간: 388 ms
메모리: 176,128 kb

# 풀이 방법
* 좌표와 방향이 필요. 좌표는 두 칸 중, 종점과 더 가까운 값만 갖고 있으면 됨.
* dfs로 탐색.
*  - 탐색 시 대각선은 어느 방향이든 전부 가봐야한다.
*  - 오른쪽으로 이동은 가로 방향인 경우에만.
*  - 아래로 이동하는 경우에는 세로 방향인 경우에만.
*  - 대각선은 3방이 전부 다 비어있는지 확인해야한다.

**Comment by haesoooo** [comment]
# 문제 링크
#226

# 풀이 사항
풀이 일자: 2024.09.12
풀이 시간: 50분
채점 결과: 정답
예상 문제 유형: DFS
시간: 502 ms
메모리: 299,996 kb

# 풀이 방법
* 두 칸짜리 파이프 배열을 만들자!
* (0,1)부터 DFS 시작
* 방향을 가로부터 시작, 가로, 세로, 대각선일 때 가능한 파이프 방향에 맞춰 파이프 배열의 좌표를 갱신해주고 각각 재귀
* (N-1, N-1)에 도착하면 카운트하고 종료
