### ISSUE TITLE
[SWEA] 보급로

### ISSUE THREAD

**Issue by haesoooo** [SSAFY12th/ssafyAlgostudy#236]
## 문제 링크
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV15QRX6APsCFAYD

## 풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

## 풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by kro46** [comment]
## 문제 링크
#240  

## 풀이 사항
풀이 일자: 2024.09.17
풀이 시간: 55분
채점 결과: 정답
예상 문제 유형: BFS/다익스트라
시간: 146 ms
메모리: 24,256 kb

## 풀이 방법
1. map 입력받음
2. 이동할 위치와 이동 시간을 담기 위한 클래스 Position을 구현(PQ에 쓸 용도이므로 Comparable<>도 구현)
3. 모든 위치로의 이동 비용은 MAX_VALUE로 초기화
4. map의 시작점부터 종점까지의 최소 비용을 구하기 위해 다익스트라 알고리즘 활용
5. 시작점, 이동 시간을 PQ에 담고 이동 시작. -> 시작점의 위치는(0,0)이고 이 때의 이동 시간은 0이다.
6. 4방 탐색 중 비용이 가장 적은 위치를 찾아서 다음 위치로 선정, 이동 비용 갱신
7. 계속 이동하다가 종점(N-1,N-1)에 닿으면 현재까지 이동한 비용을 return

**Comment by sangholee235** [comment]
# 문제 링크
#241

# 풀이 사항
풀이 일자: 2024.09.17
풀이 시간: 30분
채점 결과: 정답
예상 문제 유형: BFS
시간:  232 ms
메모리: 27,604 kb

# 풀이 방법
단순 BFS 접근으로 해결 하려 하였으나, 가중치가 있었음 다익스트라에 익숙하지 않음으로 피지컬로 해결해보려함
일단 방문한 정점이라도 현재값보다 작으면 작은 값으로 갱신하는 방식으로 해결

**Comment by reasonyi** [comment]
## 문제 링크
#249 

## 풀이 사항
풀이 일자: 2024.09.19
풀이 시간: 1시간
채점 결과: 정답
예상 문제 유형: BFS/그리디
시간: 133 ms
메모리: 22,100 kb

## 풀이 방법
제가 푼 방법이 다익스트라인지 모르겠습니다...
근데 그냥 그리디하게 풀면 될거같아서 일단 BFS를 하되, 그리디하게 진행했습니다...

- pq를 활용하여 풀이.
- pq에 넣는 Point 클래스에 가중치를 필드로 추가한다.
- 가중치를 기준으로 오름차순 정렬하도록 compareTo 메서드를 구현한다.
- pq에서 꺼내어 상하좌우로 이동할 수 있는지 확인하는데, 만약 이동 가능한 경우(방문 안함까지 체크) pq에 추가한다. 이때 가중치는 현재 위치 가중치+이동한 위치 가중치이다.
- 이러면 가장 작은 가중치부터 이동하여 visited배열에 체크되기 때문에, map의 모든 위치가 최선의 경우로 이동되어 기록된다. 
- 목적지에 도착하면 결과를 업데이트 하고 bfs를 종료한다.

**Comment by kimdevspace** [comment]
### 문제 링크
#253 
### 풀이 사항
- 풀이 일자 : 240919
- 풀이 시간 : 20분
- 채점 결과 : 정답
- 예상 문제 유형 : 그래프 탐색 / 최단 경로
- 시간 : 270ms
- 메모리 : 29,592kb
### 풀이 방법
- 우선순위 큐를 이용하여 제일 작은 가중치 먼저 탐색 하도록 작성, map의 N-1. M-1에 도달하면 break!

**Comment by chanu2** [comment]
# 문제 링크
#256 

# 풀이 사항
풀이 일자: 2024.09.18
풀이 시간: 1시간10분
채점 결과: 정답
예상 문제 유형: BFS
시간: 167 ms
메모리: 23,204 kb


# 풀이 방법
dfs로 단순하게 문제 접근했지만 시간초과 
bfs를 구현하여 방문 2차원 배열을 만들어서 방문을 했어도 최소가 되면 갱신

**Comment by haesoooo** [comment]
## 문제 링크
#235

# 풀이 사항
풀이 일자: 2024.09.18
풀이 시간: 1시간
채점 결과: 정답
예상 문제 유형: BFS
시간: 180 ms
메모리: 28,168kb


# 풀이 방법
bfs로 탐색하면서 작을 때만 갱신했다
