### ISSUE TITLE
[SWEA] 보호 필름

### ISSUE THREAD

**Issue by haesoooo** [SSAFY12th/ssafyAlgostudy#237]
## 문제 링크
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV5V1SYKAaUDFAWu

## 풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

## 풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by kro46** [comment]
## 문제 링크
#239 

## 풀이 사항
풀이 일자: 2024.09.17
풀이 시간: 1시간 30분
채점 결과: 정답
예상 문제 유형: DFS/구현
시간: 382 ms
메모리: 22444 kb

## 풀이 방법
1. map을 입력받는다. 동시에 temp 맵을 입력받는다.
2. A배열과 B배열을 각각 0,1로 초기화
3. min값은 아무리 커도 K이기 때문에 min은 K로 초기화
->(모든 열이 K만큼 같은 원소가 반복해서 나오려면 K번 같은 약품을 넣으면됨)
4. K가 1이거나 , 맵 조작없이 모든 열이 K개 이상의 반복되는 원소를 가지면,  min값은 0으로 변경하고 출력
5. solve()에서 각 행에 A약품을 넣는 경우, B 약품을 넣는 경우, 아무 약품도 안넣는 경우로 나눠 DFS수행
6. check()에서 모든 열에서 K개 이상의 같은 원소가 반복되는지 검사 -> true이면 min값 갱신

**Comment by sangholee235** [comment]
## 문제 링크
#242

## 풀이 사항
풀이 일자: 2024.09.17
풀이 시간: 30분
채점 결과: 정답
예상 문제 유형: 조합 DFS

## 풀이 방법
백트래킹을 통한 최소 약품 투입 횟수 탐색

dfs 메서드를 통해 각 막을 변경하지 않거나, A 또는 B로 변경해가면서 모든 가능한 조합을 탐색
각 조합에 대해 성능 검사를 통과할 수 있는지 확인하고, 최소 약품 투입 횟수를 갱신

각 세로 열에 대해 동일한 특성의 셀이 K개 이상 연속적으로 있는지 검사
모든 열이 통과하면 true를 반환하여 해당 조합이 합격 기준을 충족함을 검증

**Comment by reasonyi** [comment]
## 문제 링크
#248 

## 풀이 사항
풀이 일자: 2024.09.19
풀이 시간: 50분
채점 결과: 정답
예상 문제 유형: DFS
시간: 3,034 ms
메모리: 89,012 kb

## 풀이 방법
r번째 행을 안바꿈, A로 변경, B로 변경 을 dfs로 전부 진행해보고 최소값을 찾는다.
이때 최소값과 같아지거나 더 커지면 더 진행할 필요 없으므로 return하여 다음 dfs진행

**Comment by kimdevspace** [comment]
### 문제 링크
#254 
### 풀이 사항
- 풀이 일자 : 240919
- 풀이 시간 : 1시간
- 채점 결과 : 정답
- 예상 문제 유형 : 완탐
- 시간 : 474ms
- 메모리 : 33,056kb
### 풀이 방법
1. 부분 집합으로 조작이 필요한 행 선택
2. A로 바뀌는 경우, B로 바뀌는 경우, 바뀌지 않는 경우로 탐색
3. 탐색이 완료되면 열마다 K만큼 연속된 것이 있는지 확인.
4. 있다면 최솟값 갱신
