### ISSUE TITLE
[BOJ] 도시분할계획

### ISSUE THREAD

**Issue by kimdevspace** [SSAFY12th/ssafyAlgostudy#262]
### 문제 링크
https://www.acmicpc.net/problem/1647

### 풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

### 풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by kimdevspace** [comment]
### 문제링크
#261 
### 풀이 사항
- 풀이 일자 : 240922
- 풀이 시간 : 35분
- 채점 결과 : 정답
- 예상 문제 유형 : 최소 스패닝 트리
- 시간 : 1,652ms
- 메모리 : 352,024kb
### 풀이 방법
- 크루스칼과 프림으로 둘다 풀어봤다. 크루스칼은 간선위주 탐색으로 간선이 적을 때 유용하다. 프림은 정점 위주 탐색으로 간선이 많을 때 유용하다. 간선이 최대 100만개이므로 프림 알고리즘으로 푸는게 효율이 훨 좋다.
1. 최소의 비용으로 마을을 연결한다.
2. 전체 비용에서 최대 비용을 뺀 값이 정답임.
    why?
   마을을 두개로 나누면서의 비용이 최소가 되어야 하는데, 비용이 최대인 간선을 하나 끊어버리면 그 때 총 비용이 최소가 됨!
   다른 간선을 끊을수도 있는데 위 처럼 비용이 제일 높은 간선을 끊어야 최소 비용으로 마을 두개로 나눌 수 있음

**Comment by kro46** [comment]
## 문제링크
#267 

## 풀이 사항
풀이 일자 : 240923
풀이 시간 : 1시간 30분
채점 결과 : 정답
예상 문제 유형 : 크루스칼/프림
시간 : 1,708 ms
메모리 : 351,760 kb

## 풀이 방법
1. 프림 알고리즘 구현을 위해 이중 ArrayList인 graph, PQ , Q , visited를 선언
2. 우선순위 큐에 사용될 Edge클래스 구현
3. 정점에 대해 입력받은 간선  그래프에 추가(무향이므로 양쪽으로 추가)
4. 가장 큰 유지비를 차지하는 간선을 찾기 위해 max_cost 선언
5. 프림 알고리즘 진행 중 PQ에서 꺼내진 정점의 간선의 비용을 더할 때 해당 간선의 비용을 max_cost와 비교하여 갱신
6. 모든 최소 비용 구하기가 끝나면 total - max_cost을 리턴
 
## 소감
크루스칼은 어느정도 익숙해져서 프림알고리즘을 활용해 봤음. 그런데 이거 문제 이해하는게 너무 어려웠음... 
어떤 간선을 제거해야 최소 유지비가 나오는지 감이 안잡혀서 1시간정도는 그거 고민하느라 보낸듯.. 
아무튼 다른 친구들의 아이디어를 보고 바로 캐치해서 풀어보니 틀림(?)
알고보니 유향그래프인줄 알고 두 정점 중 한 쪽에만 간선을 추가함.. -> 문제를 잘 읽자
수정하고 제출하니 통과!

**Comment by sangholee235** [comment]
### 문제링크
#264
### 풀이 사항
- 풀이 일자 : 240922
- 풀이 시간 : 30분
- 채점 결과 : 정답
- 예상 문제 유형 : 최소 스패닝 트리
- 시간 : 2,368ms
- 메모리 : 345,348kb
### 풀이 방법
1. 크루스칼 알고리즘을 활용하여 최소 신장 트리를 만들었다.
2. 가장 비용이 큰 간선을 제거하였다.
3. 간선 하나를 제거하면 두가지 도시로 분리 되므로 최소 비용

**Comment by chanu2** [comment]
### 문제링크
#269 
### 풀이 사항
- 풀이 일자 : 240924
- 풀이 시간 : 50분
- 채점 결과 : 정답
- 예상 문제 유형 : 프림,크루스칼
- 시간 : 1664 ms
- 메모리 : 351892 kb
### 풀이 방법
1. 간선이 많은거 같아서 prim사용
2. prim 구현 하면서 mst가 만들어 질 때 까지 합구하기
3. qp에서 값을 빼고 최대값 갱신
4, 합 - 최댓값

**Comment by reasonyi** [comment]
## 문제링크
#279 

## 풀이 사항
풀이 일자 : 2024.09.26
풀이 시간 : 25분
채점 결과 : 정답
예상 문제 유형 : MST
시간 : 1,392 ms 
메모리 : 328,932 kb

## 풀이 방법
크루스칼 알고리즘을 사용하여 풀이하였다. (크루스칼이 더 익숙해서!)
처음에 문제를 이해 못해서 문제 이해에 20분가량 썼는데... 그냥 최대 간선 하나 삭제하면 분할이 끝나는 것이었다. 

- 기본적인 크루스칼 알고리즘처럼 하되, find()에서 최적화를 해주고, 만약 union()에 성공했다면, 성공한 간선을 다른 리스트에 따로 저장해두었다가 크루스칼 알고리즘이 끝난 뒤 가장 큰 값의 간선을 삭제한다.

**Comment by haesoooo** [comment]
## 문제링크
#283

## 풀이 사항
풀이 일자 : 2024.09.26
풀이 시간 : 1시간 40분
채점 결과 : 정답
예상 문제 유형 : MST
시간 : 1716ms 
메모리 : 351,580 kb

## 풀이 방법
간선이 더 많은 조건이라고 하여 프림을 공부해서 풀어보았다. 처음에 게리맨더링처럼 풀려고 했다 .. ㅜ
그런데 프림이 크루스칼보다 느리다고 한다. 이유를 찾아보니까 프림은 어쨌든 우선 순위 큐를 쓰니까 들어갈 때마다 정렬을 하는 시간이 원소 개수의 로그에 비례하는데 (log E) ,
 다 정렬을 해놓고 비교를 하는 크루스칼에 비해 이 과정이 느릴 수밖에 없고 알고리즘 풀이에서는 프림이 더 빠르다고 느낄만큼 그래프가 커질 일이 잘 없다고 한다..? 아무튼 언제 뭐를 쓰면 좋을지 잘 공부해봐야할듯
