### ISSUE TITLE
[BOJ] 감시

### ISSUE THREAD

**Issue by sangholee235** [SSAFY12th/ssafyAlgostudy#268]
### 문제 링크
https://www.acmicpc.net/problem/15683

### 풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

### 풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by sangholee235** [comment]
### 문제링크
#265
### 풀이 사항
- 풀이 일자 : 240922
- 풀이 시간 : 40분
- 채점 결과 : 정답
- 예상 문제 유형 : DFS, 구현
- 시간 : 716ms
- 메모리 : 133,348kb
### 풀이 방법
1. 카메라 타입별 모든 방향 조합을 구한다
2. 조합이 완성되면 감시 구역을 색칠한다
3. 사각지대를 계산후 최소 사각지대값과 비교 갱신한다
4. 감시 구역을 복구한뒤 다음 조합으로 계산한다

**Comment by kimdevspace** [comment]
### 문제 링크
#270 
### 풀이 사항
- 풀이 일자 : 240924
- 풀이 시간 : 1시간3분
- 채점 결과 : 정답
- 예상 문제 유형 : 완전탐색
- 시간 : 628ms
- 메모리 : 254,708kb
### 풀이 방법
1. CCTV 리스트에 CCTV의 좌표와 번호 담아주기
2. CCTV들의 방향을 중복순열로 뽑아서 정해주기 ( 0:우 1:하 2:좌 3:상 )
3. CCTV 번호에 따라서 현재 방향에 따른 탐색할 방향 도출하여 모두 탐색 -> 감시한 부분 -1 로 표시해주기
4. 감시가 끝나면 0의 개수 세어 최소값으로 갱신해주기

**Comment by chanu2** [comment]
### 문제 링크
#271 
### 풀이 사항
- 풀이 일자 : 240924
- 풀이 시간 : 1시간10분
- 채점 결과 : 정답
- 예상 문제 유형 : 완탐, 백트레킹
- 시간 : 328ms
- 메모리 : 50588kb
### 풀이 방법
1. hashMap으로 cctv 방향을 저장 
3. CCTV 중복순열로 뽑아서 정해주기 ( 0:상 1:하 2:좌 3:우 )
4. 배열 복사
5. hashMap에서 뽑은 방향으로 방향을 바꿔서 이동하며 계산 
6. 배열을 돌면서 0의 개수를 확인 후 최솟값 갱신

**Comment by reasonyi** [comment]
### 문제 링크
#275 

### 풀이 사항
- 풀이 일자 : 2024.09.26
- 풀이 시간 : 1시간7분
- 채점 결과 : 정답
- 예상 문제 유형 : 완전탐색, 조합
- 시간 : 348ms
- 메모리 : 137,640 kb

### 풀이 방법
1. 각 cctv별로 회전하는 방향에 따른 감시 방향 변화를 cameraDir 배열에 미리 저장해둔다.
2. 조합으로 카메라 번호 별 방향을 전부 뽑는다. 카메라 별 방향이 정해질 때마다 check() 함수를 호출하여 사각지대를 구한다.
3. check() 함수는 map을 copy한 후, 카메라 번호 별 방향대로, mapChange를 호출하여 copyMap의 감시 결과를 구하고, 사각지대를 계산하여 최소값을 갱신한다.
4. 모든 작업이 끝나면 최소값을 출력한다.

**Comment by kro46** [comment]
## 문제 링크
#276 

## 풀이 사항
풀이 일자 : 2024.09.26
풀이 시간 : 3시간
채점 결과 : 정답
예상 문제 유형 : 완전탐색, 조합
시간 : 224ms
메모리 : 32,040 kb
## 풀이 방법
1. 카메라의 개수만큼 list에 삽입 Point로(카메라 좌표 + 카메라 번호)
2. DFS에서는 list에 담은 카메라의 좌표와 번호를 통해 4방향으로 탐색 수행
3. 현재 카메라로 4방향 탐색 시 감시되는 영역을 리스트에 담고 그 다음 카메라로 이동, 만약 return되어 돌아오면 remove함수를 통해 이전에 담은 영역은 모두 제거(백트래킹)
4. 모든 카메라를 다 순회하면 현재 min값과 비교하여 더 작으면 min값 갱신하고 재귀 탈출
5. 모든 재귀를 끝마치면 min값 출력

## 어려웠던 점 
1. CCTV는 CCTV를 통과한다는 문장을 읽지 못해서 한참 헤멨음 -> 글 좀 읽자
2. 오히려 DFS내부 코드를 덜어내니 정답이 나옴 -> 코드가 복잡하게 길다면 덜어내보자
3. 지난번 파이프 옮기기 문제처럼 처리해줘야할 if문이 많아서 오타검수에 시간이 오래걸림

**Comment by haesoooo** [comment]
## 문제 링크
#273

## 풀이 사항
풀이 일자 : 2024.09.24
풀이 시간 : 1시간45분
채점 결과 : 정답
예상 문제 유형 : dfs
시간 : 300
메모리 : 34, 352 kb
## 풀이 방법
1. 1에서 5 사이의 값이면 cctv 배열에 좌표를 저장한다.
2. 1~6 사이 값이면 방문 처리한다
3. cctv 배열에 존재하는 개수만큼 재귀를 진행한다 
4. 각 cctv에 해당하는 방향에 맞춰서 쭉 cctv 진행 (방향에 맞춰 방문 처리)
5. 각각에 맞춰서 dfs 진행한다

## 어려웠던 점 
1. visited 배열을 복사하고, 원복하는 과정들이 좀 헷갈린다 ..
2. cctv 별로, 방향 별로 각각 분기해야하는 과정을 구현하는 방법을 생각하는 게 오래걸렸다. dfs 안에서 또 dfs를 실행해야할 지, queue에서 하나씩 뽑으면서 할 지 그런게 고민됐음
