### ISSUE TITLE
[BOJ] 다리만들기2

### ISSUE THREAD

**Issue by sangholee235** [SSAFY12th/ssafyAlgostudy#285]
### 문제 링크
https://www.acmicpc.net/problem/17472

### 풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

### 풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by sangholee235** [comment]
### 문제링크
#284 
### 풀이 사항
- 풀이 일자 : 240927
- 풀이 시간 : 2시간 30분 24초 21
- 채점 결과 : 정답
- 예상 문제 유형 : 최소 스패닝 트리, BFS, 구현
- 시간 : 104ms
- 메모리 : 14,360 kb
### 풀이 방법
1. BFS를 통해서 특정 섬의 좌표를 다 담아둠 담으면서 섬개수를 셈
2. 담아둔 좌표로 섬들간의 최소 거리를 구함
3. 구한 최소거리를 edgeList에 담음
4. 구한 edgeList로 크루스칼을 돌려서 최소 스패닝 트리를 구함
5. 총 가중치가 최소 거리임 (정답)

### 어려웠던점
문제를 마주치고 푸는 방법은 바로 떠올렸어요
그러나 구현하는 과정에서 막막함이 너무 컸어요
다리 사이의 거리 구하는 것도 힘들었어요
다리 사이에 다리가 놔지는지 검증하는것도 어려웠어요
리스트 배열 관리하는것도 어려웠어요
크루스칼도 까먹어서 다시 보고 짰어요

**Comment by kimdevspace** [comment]
### 문제링크
#286 
### 풀이 사항
- 풀이 일자 : 240928
- 풀이 시간 : 3시간 35분
- 채점 결과 : 정답
- 예상 문제 유형 : 구현, DFS, BFS, MST
- 시간 : 100ms
- 메모리 : 14,248kb
### 풀이 방법
1. 섬에 번호 부여 BFS
2. 연결성 확인 DFS
3. MST 구하기

### 어려웠던 점
1. 푸는 과정, 방법은 떠올랐으나 시도해보기가 무서웠음. -> 내가 생각하는걸 코드로 구현할 수 있는지 확인하는 과정이 머릿속에서 안됨.. 왜 무서웠냐면 설계가 완벽하지 않다고 생각해서. 괜히 짯다가 다시 밀어야 될거 같아서.
2.  dfs 의 기저 조건을 잘못 설정해줬음 여기서도 30분 정도 해맴. 재귀가 아직 부족한 느낌이 들어서 재귀도 한번 더 익혀봐야 겠음.
3. 테케들 정답까지 다 나왔는데 계속 틀렸다고 해서 1시간을 넘게 해맸음. -> 이유는.. 모든 정점이 연결되어 있어야 하는데 그 부분을 고려하지 않아서 4%대에서 계속 틀림. 최소 스패닝 트리는 모든 정점이 최소의 가중치로 연결되어 있어야 함.!|
테케에는 이런 반례들이 없었는데 질문 게시판 반례들 보고 "아!!!!!!!!!!!!!!"하고 떠올랐다.

간선의 개수는 정점의 개수 - 1개! <- 이 부분을 생각하지 못했음.

**Comment by reasonyi** [comment]
### 문제링크
#296 

### 풀이 사항
- 풀이 일자 : 2024.10.01
- 풀이 시간 : 1시간 50분
- 채점 결과 : 정답
- 예상 문제 유형 : 구현, DFS, BFS, MST
- 시간 : 104ms
- 메모리 : 14,292kb

### 풀이 방법
1. 처음에 섬을 -1로 저장한다.
2. -1로 된 섬을 찾아 BFS로 섬에 번호를 부여한다.
3. 각 섬의 위치마다 상하좌우로 움직여서 맵 안이면서 빈칸인 개수를 센다. 만약 2보다 큰 다리 연결이 가능한 다른 섬을 만났다면, Edge에 추가한다.
4. 크루스칼을 이용해 최소신장트리를 구한다.
5. 연결되어있지 않은 섬이 있다면 -1을 출력하고, 전부 연결되어 있다면 최소비용을 출력한다.

### 어려웠던 점
- 처음에 다리 연결을 확인하기 위한 코드를 괴상하게 짰음. 4중 for문에 if문 다회 사용으로 진짜 스파게티를 넘어 짜파게티 코드를 짬.......
- 처음 다리 연결 확인할 때는, 각 섬의 모든 좌표를 ArrayList에 저장하여 푸는 방식으로 풀었음.
- 각 섬을 꺼내와서 섬의 좌표끼리 확인하는 방식으로 다리 건설 가능 여부를 확인함.
- 테케는 다 맞췄으나, 위의 방법에서 가장 문제점은, 비교하는 섬끼리 얼마나 떨어져 있는지만 확인했기 때문에, 중간에 다른 섬이 끼어서 다리가 끊어지는 경우를 계산하지 못함.
- 때문에 1%대에서 바로 틀렸습니다 나와서... 설계 자체가 잘못된 것을 알고 전부 싹 밀고 다시 구현함.

**Comment by kro46** [comment]
## 문제링크
#301 

## 풀이 사항
풀이 일자 : 241004
풀이 시간 : 4시간 16분
채점 결과 : 정답
예상 문제 유형 : 최소 스패닝 트리, BFS, 구현
시간 : 104ms
메모리 : 14,348 kb
## 풀이 방법
1. BFS를 통해서 각 섬에 번호를 붙여주고, 섬에 포함된 좌표를 모두 landList에 저장 
  1-1.-> 섬의 최대개수는 6개이므로 landList의 크기를 7로 만듦(1번부터 쓸 것이기 때문)
2. 인접행렬을 만들어 모든 원소를 MAX_VALUE로 초기화 -> 마찬가지로 Matrix[7][7]로 만듦 
3. 섬의 개수만큼 반복하며 각 섬 간의 간선 중 최소거리를 edgeList에 담음
4. 구한 edgeList로 크루스칼을 돌려서 최소 비용을 구함(cost)
5. 크루스칼의 결과로 연결된 섬의 개수(cnt)가 landCnt -1과 다르면 -1 출력, 아니면 cost를 출력
## 어려웠던점
- 이 문제는 애초에 코드량 자체가 많아서 코드를 쓰는 와중에 계속 집중하지 못하는 문제가 있었음.
- 그래서 중간부터는 모든 과정을 메모장에 적어가며 흐름을 놓치지 않게 진행함.
- 또한, 이 문제의 관건은 얼마나 많은 과정을 메서드로 쪼개서 쉽게 접근하느냐였던 것 같음.
- 그 결과, main메서드를 포함 총 11개의 메서드로 코드를 완성함...
- 한가지 팁이 있다면, 인접행렬을 완성할 때 4방향을 모두 볼 필요 없이 오른쪽과 아래쪽만 보면서 간선을 구해도 가능함.
- 이유는 섬의 시작이 왼쪽 상단부터 시작하기 때문에 우측과 아래측만 연결해주면 알아서 모든 간선에 대한 검사가 가능함.
