### ISSUE TITLE
[BOJ] 미세먼지 안녕!

### ISSUE THREAD

**Issue by kimdevspace** [SSAFY12th/ssafyAlgostudy#288]
문제 링크
https://www.acmicpc.net/problem/17144

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by kimdevspace** [comment]
### 문제 링크
#287 
### 풀이 사항
- 풀이 일자 : 240929
- 풀이 시간 : 3시간 30분
- 채점 결과 : 정답
- 예상 문제 유형 : 구현, 시뮬레이션
- 시간 : 368ms
- 메모리 : 35,220kb
### 풀이 방법
1. 리스트에 공기청정기 위치를 담았음.
2. 동시에 확산하는 것을 구현하기 위해 2차원temp배열을 사용
3. 동시 확산
4. 먼지 회전 (배열 돌리기)
5. 먼지세기! 

- 어려웠던 점
동시에 확산한다? 라는 개념이 어려웠음. 배열을 하나 더 만들어서 계산해주는 아이디어는 구글링을 통해 배웠다!
- 부족한 점
방법은 떠오르나 코드를 옮기는 것이 아직 많~~~~~~~~~~이 부족하다.
컴퓨터적인 사고가 부족 ex) 배열을 어떻게 돌려야 값이 제대로 돌려지는지 등등
완벽한 설계를 하는 방법은 그냥 문제를 많이 풀어보고 많은 개념들을 익힌 후에 하는 것이 맞는 것 같음.

**Comment by chanu2** [comment]
### 문제 링크
#289 
### 풀이 사항
- 풀이 일자 : 240930
- 풀이 시간 : 1시간 29분
- 채점 결과 : 정답
- 예상 문제 유형 : 구현, 시뮬레이션
- 시간 : 292ms 
- 메모리 : 28148kb
### 풀이 방법
1.  확산 시키기
2. 새로운 배열을 계속해서 만들어서 t 만큼 돌 때 모두 계산해서 최신화하여 한번에 다 퍼뜨린다.
3. 공기 청정기 돌리기 이전 값을 저장하면서 달팽이 문제 처럼 돌리면서 이동 시키고 배열을 변경 해준다  
4. 0 이상이 값을 모두 더하여 결과 출력

**Comment by reasonyi** [comment]
### 문제 링크
#290 

### 풀이 사항
- 풀이 일자 : 2024.10.01
- 풀이 시간 : 1시간 44분
- 채점 결과 : 정답
- 예상 문제 유형 : 구현, 시뮬레이션
- 시간 : 296 ms
- 메모리 : 31,180 kb
- 
### 풀이 방법
1. 확산된 값을 저장할 배열을 따로 만든 후 확산값을 저장하여 map을 바꿔준다.
2. 공기청정기의 위아래 순환이 함께 이동하는 경우(좌우 이동)은 같은 for문으로 처리.
3. 다를 수 있는 순환의 경우(상하 이동)은 for문을 따로 만들어 처리

- 어려웠던 점
처음에 먼지를 리스트에 전부 저장하는 방식으로 플이하였으나 424 ms 에 84,556 kb라는 정신나간 메모리 수치 나옴 그래서 이전에 풀었던 풀이를 다시 보고 풀었는데, 때로는 그냥 무식하게 전부 참조하고, 변경하는 것이 빠를 수 있다는 생각을 하게 되었음.

**Comment by sangholee235** [comment]
### 문제 링크
#294 
### 풀이 사항
- 풀이 일자 : 241001
- 풀이 시간 : 1시간 30분
- 채점 결과 : 정답
- 예상 문제 유형 : 시뮬레이션
- 시간 : 332 ms
- 메모리 : 32,604 kb
### 풀이 방법
1. 입력 받을때 공기청정기 위치 기억 배열로 관리
2. 확산 시키기 (퍼트릴때 퍼지는 숫자를 세줘서 퍼뜨림 4방향으로 항상 퍼지는게 아니니까)
3. 공기청정기 돌리기
4. 최종 먼지 개수 세기

- 어려웠던 점
공기 청정기가 돌아간다는 개념을 이해하기 어려웠다. 구현 또한 쉽지 않았다.

**Comment by kro46** [comment]
## 문제링크
#299 

## 풀이 사항
풀이 일자 : 2024.10.03
풀이 시간 : 2시간 23분
채점 결과 : 정답
예상 문제 유형 : 구현, 시뮬레이션
시간 : 456 ms
메모리 : 76,732 kb
## 풀이 방법
1. 청정기 위치 저장 , 청정기 위치 저장 후에 해당 좌표는 0으로 변환
  1-1. 미세먼지의 좌표를 list에 모두 저장  (해당 좌표값이 5 이상인 것들만 저장) -> Point Class 구현

2. 확산, 모든 저장된 미세먼지 좌표 순회 
  tmp = Point.value / 5; (네방향으로, 배열범위 내이고, 청정기좌표가 아닐때) -> 각 방향에 t 값을 더함, [i,j]는 t만큼 감소
 확산이 끝나면 list를 비워줌

3. 순환. 기준점(목적지 기준)
청정기 좌표 -> cleaner List에 Point로 저장
청정기의 위쪽의 경우 순환 방향이 Down, Left, Up, Right
청정기의 아래쪽의 경우 순환 방향이 Up, Left, Down, Right

위 과정을 T번 반복한 후 map의 미세먼지 총량을 더하여 출력
## 어려웠던 점
확산을 구현할 때 청정기로 들어가는 먼지를 0으로 바꿔야하는데 이 부분을 어떻게 해결하는게 좋을지 고민이 많았음.
결론적으론 그냥 청정기 바로 전 위치의 미세먼지를 그 다음 위치의 값으로 덮어쓰는 방식을 채택함.
위의 방법을 쓰려면 기존의 순환 방향과 정반대로 순환을 구현해야하기때문에 좀 어지러웠음.
