### ISSUE TITLE
[BaekJoon] 전쟁 - 전투

### ISSUE THREAD

**Issue by reasonyi** [SSAFY12th/ssafyAlgostudy#29]
문제 링크
https://www.acmicpc.net/problem/1303

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by reasonyi** [comment]
문제 링크
#28 

풀이 사항
풀이 일자: 2024.07.26
풀이 시간: 23분 32초
채점 결과: 정답
예상 문제 유형: DFS/BFS

풀이 방법
맵 전체를 돌면서 방문하지 않은 곳이 있다면 방문.
주변에 같은 진영의 병사라면 dfs로 전부 방문하여 모여있는 병사의 수를 셈.
모여있는 병사의 수^2 만큼 각 진영의 위력을 구하여 더함.
맵 전체를 방문했다면 아군과 적의 위력 출력.

**Comment by kimdevspace** [comment]
### 문제 링크
#34 
### 풀이 사항
풀이 일자 : 240729
풀이 시간 : 45분
채점 결과 : 정답
예상 문제 유형 : DFS / BFS

### 풀이 방법
DFS 알고리즘을 이용하여 방문체크 하면서 상하좌우 인접할 시  cnt += 1 후 제곱하여 정답 출력!

**Comment by chanu2** [comment]
### 문제 링크
#41 
### 풀이 사항
풀이 일자 : 240731
풀이 시간 : 29분31초
채점 결과 : 정답
예상 문제 유형 : DFS / BFS

### 풀이 방법
DFS 알고리즘을 이용하여 방문체크 하면서 W 일때 B일 때  돌면서  count

**Comment by kro46** [comment]
## 문제 링크

#42 

## 풀이 사항
풀이 일자 : 240801
풀이 시간 : 1시간
채점 결과 : 정답
예상 문제 유형 : DFS / BFS

## 풀이 방법
BFS알고리즘 활용 -BFS함수에 alpha를 매개변수로 넣어줌(W일 때와 B일 때를 구분)
BFS안에서 상하좌우를 검사하여 같은 알파벳이 있으면 cnt 값을 계속 증가하면서 queue에 담고, poll()이 끝나면 cnt^2값을 리턴
main에서 리턴값을 받아서 sumW , sumB에 누산하여 결과 출력

**Comment by haesoooo** [comment]
## 문제 링크

#36 

## 풀이 사항
풀이 일자 : 240730
풀이 시간 : 30분
채점 결과 : 정답
예상 문제 유형 : DFS 

## 풀이 방법
맵에서 각 좌표마다 탐색, 현재 좌표의 배열 값이 B면 cntB++, W면 cntW++;
상하좌우에 대해서 범위 이내이고, 현재 좌표의 배열 값과 [nexty][nextx]에 해당하는 배열 값이 같고, 방문하지 않은 경우 재귀
dfs 끝나고 cntB, cntW에 대해서 각각 제곱(pow)

C++ : 2024kb / 0ms
JAVA : 16464kb / 164ms

**Comment by chanu2** [comment]
end
