### ISSUE TITLE
[BOJ] 극장 좌석

### ISSUE THREAD

**Issue by sangholee235** [SSAFY12th/ssafyAlgostudy#293]
문제 링크
https://www.acmicpc.net/problem/2302

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by kro46** [comment]
## 문제링크
#295 

## 풀이 사항
풀이 일자 : 241001
풀이 시간 : 2시간
채점 결과 : 정답
예상 문제 유형 : 동적 계획법 -> 피보나치 수열
시간 : 100ms
메모리 : 14,292kb
풀이 방법
VIP = 고정석 -> 바뀔 수 없는 좌석
나머지 = 자신의 왼쪽 오른쪽과 자리 변경 가능 
ex)
1
12 21
123 213 132
1234 2134 1324 1243 
2143
12345 21345 13245 12435 12354
21435 21354 13254   
위의 가짓수를 보고 피보나치가 떠오름
이제 구간의 개수와 각 구간별 좌석 수를 구해야함 
고정석 전까지 좌석의 개수를 세어 구간을 나누고 구간별 원소의 개수를 eCnt에 저장 
모든 구간별 원소의 개수를 구하면 mul에 fibo[]안에 각 원소의 개수를 넣어 곱함
모든 계산이 끝나면 mul 값 출력(총 가짓수는 20억을 넘지 않음-> int사용가능)
어려웠던점
N과 M의 개수에 따라 분기를 나눠줘야하는데 M이 0일 때와 N이 1일때의 경우를 처리해주지 않아서 계속 런타임 에러가 뜨다가 2시간만에 잡음 -> 문제 자체는 어렵지 않았는데 예외처리에 신경을 많이 써야해서 오래 걸렸던 문제임

**Comment by reasonyi** [comment]
### 문제링크
#297 

### 풀이 사항
- 풀이 일자 : 2024.10.02
- 풀이 시간 : 49분
- 채점 결과 : 정답
- 예상 문제 유형 : 동적 계획법 
- 시간 : 92 ms
- 메모리 : 14,120 kb

### 풀이 방법
![image](https://github.com/user-attachments/assets/59e2c757-7665-4184-954b-a4c803e63cb1)
1. vip 좌석을 받을 때, 해당 좌석과 직전 좌석 간 거리를 구해 cal에 저장한다.
2. 저장된 cal중에서 가장 큰 값을 찾아 max에 저장한다.
3. max값 크기+1만큼 dp 배열을 만든다. 이때 max값이 2보다 작다면 2로 만들어 dp의 최소 크기가 3이 되게 한다.
4. dp의 길이만큼(max+1)만큼 dp값을 구한다. 
5. 점화식은 dp[i] = dp[i-1] + dp[i-2] 이다.
6. cal에 저장된 값을 가져와 dp에서 해당하는 값을 구해 reuslt에 계속 곱한다.
7. result 출력.

### 어려웠던점
점화식은 금방 구했는데, dp 초기화 조건을 생각 못해서 찾는데 오래걸렸다.

**Comment by kimdevspace** [comment]
### 문제 링크
#298 
### 풀이 사항
- 풀이 일자 : 241002
- 풀이 시간 : 1시간3분
- 채점 결과 : 정답
- 예상 문제 유형 : DP 
- 시간 : 92ms
- 메모리 : 14,180kb
### 풀이 방법
1. 각 수의 크기마다 크기가 변할 수 있는 경우를 하나씩 써 내려가기
2. dp[0] = 1, dp[1] = 1, dp[2] = 2 로 시작하는 dp[i] = dp[i-1] + dp[i-2] 인 피보나치  수열이 됨 (각 인덱스는 변경할 수 있는 경우의 수)
3. 고정석을 입력받고 고정석 기준으로 구간을 나눔.
4. 각 구간마다 경우의 수를 곱해주기
### 어려웠던 점
dp 점화식 찾기가 힘들어요 아직 dp할 짬이 아닌거같아요
