### ISSUE TITLE
[S/W 문제해결 기본] view

### ISSUE THREAD

**Issue by chanu2** [SSAFY12th/ssafyAlgostudy#3]
### 문제 링크
https://swexpertacademy.com/main/code/problem/problemDetail.do?problemLevel=3&contestProbId=AV134DPqAA8CFAYh&categoryId=AV134DPqAA8CFAYh&categoryType=CODE&problemTitle=&orderBy=INQUERY_COUNT&selectCodeLang=ALL&select-1=3&pageSize=10&pageIndex=1

### 풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

### 풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by kimdevspace** [comment]
## 풀이사항
풀이 일자 : 2024.07.18
풀이 시간 : 34분 35초
채점 결과 : 정답
예상 문제 유형 : 구현..?

## 풀이 방법
배열에서 시작 두 칸과 끝 두 칸을 제외하고 탐색을 시작했고, 탐색한 값이 [-2] ~ [+2] 중 최댓값이라면 (최댓값 - 그 다음 값) 을 ans에 누산하며 풀었습니다.

**Comment by reasonyi** [comment]
문제 링크

#10 

풀이 사항
풀이 일자: 2024.07.22
풀이 시간: 13분
채점 결과: 정답
예상 문제 유형: 구현, 시뮬레이션

풀이 방법
빌딩 높이를 배열에 입력받는다.
2번째 인덱스부터 시작하여 앞 두 건물과 뒤 두 건물과의 높이차를 비교한다
현재 빌딩이 가장 높으면 조망권이 확보되는 값 만큼 result에 더하여 나중에 출력.

**Comment by kro46** [comment]
##문제 링크
#12 

##풀이 사항
풀이 일자: 2024.07.19
풀이 시간: 30분
채점 결과: 정답
예상 문제 유형: 구현, 시뮬레이션

##풀이 방법
배열 크기 N과 빌딩의 크기를 배열에 입력 받는다.
2번 인덱스부터 시작해서 현재 빌딩 위치로부터 양쪽으로 2번째까지 빌딩 높이를 비교해서 가장 작은 값을 sum 변수에 저장
N-2번 인덱스까지 반복

**Comment by haesoooo** [comment]
### 문제 링크
#14 

### 풀이 사항
풀이 일자: 2024.07.09
풀이 시간: 10분
채점 결과: 정답
예상 문제 유형: 구현

### 풀이 방법
- 각 건물의 높이 정보 저장
- 가장 좌측과 우측 2개의 건물을 제외하고 좌, 우 각각 빌딩 높이 비교 (max)
- 현재 빌딩 높이와 좌, 우 중 max 값에 대한 차이 계산

**Comment by chanu2** [comment]
## 풀이사항
풀이 일자 : 2024.07.23
풀이 시간 : 29분 35초
채점 결과 : 정답
예상 문제 유형 : 구현

#17 

## 풀이 방법

배열에서 시작 두 칸과 끝 두 칸을 제외하고 탐색을 시작했고, 기준 빌딩을 max로 놓고 arr[-2] ~ arr[+2] 탐색하면서 기준 빌딩을 제외하고 가장 높은 빌딩을 찾아 기준 빌딩 보다 높이가 작을 때 count에 빌딩의 차를 더해준다.

**Comment by JuHeeKim-joy** [comment]
### 문제 링크
깃 충돌로 해결하고 재업도드 하겠습니다 ...

### 풀이사항
풀이 일자 : 2024.07.24
풀이 시간 : 1시간
채점 결과 : 정답
예상 문제 유형 : 구현

### 풀이 방법
- N : 빌딩 수, arr : 각 빌딩 높이 입력받기
- i번째 빌딩의 높이(arr[i])와 max 비교하기 
- 조망권이 확보된 층수를 cnt에 누적하기
