### ISSUE TITLE
[BOJ] 숫자 카드

### ISSUE THREAD

**Issue by kimdevspace** [SSAFY12th/ssafyAlgostudy#307]
문제 링크
https://www.acmicpc.net/problem/10815

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by reasonyi** [comment]
### 문제 링크
#321 

## 풀이 사항
- 풀이 일자 : 2024.10.08
- 풀이 시간 : 7분
- 채점 결과 : 정답
- 예상 문제 유형 : 탐색
- 시간 : 1,140 ms
- 메모리 : 111,508 kb

### 풀이 방법
탐색 문제

### 생각해볼 점
사실 다른 로직을 구성할 필요 없이 포함 유무만 찾으면 되는 문제라, 굳이 배열에 저장해서 이진탐색 하는 것보다, HashSet같은 자료구조에 넣어서 contains함수를 사용하는 것이 더 빠르게 구할 수 있음을 알았다.

**Comment by sangholee235** [comment]
### 문제링크
#317
### 풀이 사항
- 풀이 일자 : 241008
- 풀이 시간 : 10분
- 채점 결과 : 정답
- 예상 문제 유형 : 자료구조
- 시간 : 784ms
- 메모리 : 137,896 kb
### 풀이 방법
1. 해시셋에 갖고 있는 숫자를 담음
2. contain으로 포함하는지 여부를 구분
3. 있으면 1 없으면 0 출력

### 어려웠던점
해시셋쓰면 되는걸 바로 알았으나 자바에서 해시셋을 써본적이 없었다. 그래가꼬 공부하고 풀었음

**Comment by kro46** [comment]
## 문제 링크
#325 

##풀이 사항
플이 일자 : 241008
풀이 시간 : 10분
채점 결과 : 정답
예상 문제 유형 : 이분 탐색
시간 : 1,088ms
메모리 : 108,700kb

## 풀이 방법
binraySearch를 직접 구현해서 풀었음.
자바에서 지원하는 Arrays.binarySearch()로도 해보고 HashSet으로도 해봤는데 HashSet이 가장 빨랐고,
그 다음 직접 구현한 것이 빨랐다. 
자바에서 지원하는 Arrays.binarySearch()는 메서드 내부에 우리가 모르는 안전장치용 코드가 더 있어서 직접 구현한 것보다 느리다고 한다.
3가지 모두 장단점이 있으니 공부해보는것을 추천!

**Comment by chanu2** [comment]
### 문제 링크
#329 
### 풀이 사항
플이 일자 : 241010
풀이 시간 : 5분
채점 결과 : 정답
예상 문제 유형 : 해쉬?
시간 : 842ms
메모리 : 137984kb
### 풀이 방법
해시셋 아닙니까?

**Comment by haesoooo** [comment]
### 문제 링크
#330
### 풀이 사항
플이 일자 : 241010
풀이 시간 : 15분
채점 결과 : 정답
예상 문제 유형 : 이분탐색, map
시간 : 792ms
메모리 : 138,804kb
### 풀이 방법
이분탐색으로도 풀어보고 맵으로도 풀었습니다.
이 문제는 존재 여부만 확인하면 되는 문제라 맵이나 셋으로 풀 수 있지만
다른 일반적인 이분탐색 문제에서는 그렇지 않기 때문에 연습 마니 해야겟습니다!!
