### ISSUE TITLE
[BOJ] 녹색 옷 입은 애가 젤다지?

### ISSUE THREAD

**Issue by kimdevspace** [SSAFY12th/ssafyAlgostudy#308]
문제 링크
https://www.acmicpc.net/problem/4485

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by kimdevspace** [comment]
### 문제 링크
#311 
### 풀이 사항
풀이 일자 : 241005
풀이 시간 : 22분
채점 결과 : 정답
예상 문제 유형 : 최단 경로
시간 : 212ms
메모리 : 20,736kb
### 풀이 방법
0,0 시작으로 n-1, n-1까지 다익스트라 알고리즘을 이용하여 최단경로를 구하는 간단한 문제.

### 어려웠던 점
문제를 보고 다익스트라 안쓰고 그냥 pq만 써도 될거같다라는 생각에 풀어봤는데 아니나 다를까 안됩니다요
매번 이동거리를 갱신해주면서 최소를 찾아야 최단으로 갈 수 있는 사실을 깨달았다! 2차원에서 다익스트라는 비슷하다
큰 템플릿이라 생각하고 외워봅시다

**Comment by kro46** [comment]
## 문제 링크

#314 

## 풀이 사항
풀이 일자 : 241006
풀이 시간 : 45분
채점 결과 : 정답
예상 문제 유형 : 다익스트라
시간 : 192ms
메모리 : 20,600kb

## 풀이 방법
0,0 시작으로 n-1, n-1까지 다익스트라 알고리즘을 이용하여 최단경로를 구하는 간단한 문제.

## 어려웠던 점
다익스트라 알고리즘이 아직 손에 안익어서 이전에 풀었던 코드를 보고 푸는것 보단 생각해서 직접 구현해보려고 노력했다.
직접 구현하는데까지 약 30분? 정도 시간이 걸렸다. 
근데 테스트케이스 개수 안주고 테케번호 붙이는게 오류떠서 조건을 살짝 손보니까 성공! 
암튼 다익스트라 알고리즘 어느정도 감을 익히는데 중점을 두었다.

**Comment by sangholee235** [comment]
## 문제 링크

#315

## 풀이 사항
풀이 일자 : 241007
풀이 시간 : 30분
채점 결과 : 정답
예상 문제 유형 : 최단 경로 탐색
시간 : 232ms
메모리 : 20,268kb

## 풀이 방법
보급로문제랑 비슷한 방식으로
다익스트라로 최소 비용을 구해 최 우하단의 cost를 구하였다

## 어려웠던 점
우선순위 큐를 만드는 방식이 아직 어색했다 좀 더 손에 익을때까지
직접 구현을 해봐야겠다.

**Comment by reasonyi** [comment]
### 문제 링크
#319 메모이제이션
#320 다익스트라

### 풀이 사항
풀이 일자 : 2024.10.08
풀이 시간 : 12분
채점 결과 : 정답
예상 문제 유형 : 메모이제이션, 최단 경로

시간 :    
 메모이제이션ver - 648 ms
 다익스트라ver     - 224 ms

메모리 : 
 메모이제이션ver - 299,664 kb
 다익스트라ver     - 21,280 kb

### 풀이 방법
메모이제이션은 그냥 큐에 넣어서 반복되는 연산이 좀 많이 생긴다.
그리디함을 추가해 풀었더니 훨씬 시간도 빠르고 메모리 단축이 엄청나게 됨

### 어려웠던 점
bfs는 메모리 엄청 잡아먹는다는걸 명심하고 있었어야 했는데,,, 아무생각없이 큐를 써서 풀리고 나니까 이슈 쓰러 왔다가 팀원들 시간이랑 메모리 보고 충격받아서 pq썼다

**Comment by chanu2** [comment]
### 문제 링크
#322 
### 풀이 사항
풀이 일자 : 241008
풀이 시간 : 32분
채점 결과 : 정답
예상 문제 유형 : 다익스트라
시간 : 192ms
메모리 : 19344kb
### 풀이 방법
0,0 시작으로 n-1, n-1까지 다익스트라 알고리즘을 이용하여 최단경로를 구하였다.

**Comment by haesoooo** [comment]
### 문제 링크
#331
### 풀이 사항
풀이 일자 : 241010
풀이 시간 : 35분
채점 결과 : 정답
예상 문제 유형 : 다익스트라 (그리디 + DP)
시간 : 204ms
메모리 : 19344kb
### 풀이 방법
0,0 부터 2차원 배열로 cost 테이블 생성, 상하좌우에 대해 범위 탐색하며 이 노드를 방문하는게 더 저렴한지를 체크해서 진행하는 다익스트라 방식으로 구현

### 어려웠던 점
pq를 구현할 때 여러 값을 가진 원소를 넣으면, C++에서는 Comparator를 딱히 구현하지 않으면 원소의 첫번째 값으로 정렬이 되는데 이를 간과하고 첫번째에 노드를 넣었다. 값으로 정렬하지 않고 노드로 정렬하니까 그냥 완탐이랑 다를 바 없는 시간이 걸려서 당황함
그리고 pq에 넣어줄 때 nextCost가 아니라 cost 테이블에 저장한 값을 넘겨주어야 하는데 이 또한 헷갈렸씁니다.
