### ISSUE TITLE
[BOJ] 마법사 상어와 토네이도

### ISSUE THREAD

**Issue by kimdevspace** [SSAFY12th/ssafyAlgostudy#309]
문제 링크
https://www.acmicpc.net/problem/20057

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by kimdevspace** [comment]
### 문제 링크
#310 
## 풀이 사항
- 풀이 일자 : 241005
- 풀이 시간 : 2시간 40분
- 채점 결과 : 정답
- 예상 문제 유형 : 구현, 시뮬레이션
- 시간 : 320ms
- 메모리 : 34,408kb
### 풀이 방법
1. 가운데부터 좌, 하, 우, 상으로 2차원 배열을 달팽이배열로 탐색.
2. 0이 아닌 값 탐색 시 ( 모래를 찾을 시 ) 확산
3. 문제에서 주어진 조건처리후 정답 구하기

### 어려웠던 점
처음에는 배열을 회전시키는 풀이로 설계 후 풀었음. 하다가 디버깅이 안돼서 포기
두번째에는 맵을 복사해서 푸는 설계로 풀었는데 복사를 두번 진행 하다보니 N^4의 시간복잡도 떄문에 시간 초과났음
맵을 복사하지 않고도 풀 수 있다!

그리고 달팽이배열로 탐색하는거도 너무 어려웠음요 . ㅠ

**Comment by chanu2** [comment]
### 문제 링크
#312 
## 풀이 사항
- 풀이 일자 : 241005
- 풀이 시간 : 1시간 52분
- 채점 결과 : 정답
- 예상 문제 유형 : 구현, 시뮬레이션
- 시간 : 420ms
- 메모리 : 34576kb
### 풀이 방법
1. 가운데부터 좌, 하, 우, 상으로 2차원 배열을 탐색 하면서 달팽이 모양으로 이동
2. 방향기준으로 갈 수 있는 모든 좌표를 저장해둔 값으로 계산 진행
3. 결과값 도출

**Comment by reasonyi** [comment]
### 문제 링크
#316 

## 풀이 사항
- 풀이 일자 : 2024.10.08
- 풀이 시간 : 1시간 21
- 채점 결과 : 정답
- 예상 문제 유형 : 구현, 시뮬레이션
- 시간 : 568 ms
- 메모리 : 44,588 kb

### 풀이 방법
1. 배열을 달팽이 모양으로 탐색
2. 만약 이동한 위치에 있다면 규칙에 따라 모래 흩뿌리기
3. 0, 0에 도달할 때까지 위의 과정을 반복하고, 끝난 후 격자 밖으로 나간 모래의 양 출력

### 어려웠던 점
- 소수점을 버린 만큼만 흩뿌려진다는 점에서 헷갈려서 헤멤.
- 일단 구현에 맞춰 코드를 짜다보니... 하드코딩으로 역대급 스파게티 코드 탄생
- 하드코딩으로 하기보다는 그냥 배열을 90도 회전시키는 메서드를 만들어서, 그걸 활용해 코드를 작성했다면 훨씬 가시성 좋은 코드를 짤 수 있었을 것 같음

**Comment by sangholee235** [comment]
### 문제링크
#323
### 풀이 사항
- 풀이 일자 : 241008
- 풀이 시간 : 4시간
- 채점 결과 : 패배
- 예상 문제 유형 : 구현, 시뮬레이션

### 풀이 방법
1. 토네이도를 달팽이 돌림
2. 토네이도 돌아간 위치에서 모래 흩뿌리기
3. 넘어가면 총량에 더하고 안넘어가면 맵에 더함

### 어려웠던점
도당채 왱 ㅏㄴ 되는지 모르겠음 너무 화남 정말

**Comment by kro46** [comment]
## 문제 링크
#326 

## 풀이 사항
풀이 일자 : 2024.10.09
풀이 시간 : 알 수 없음..약 6시간?(너무 오래걸려서 중간에 포기했다가 다시 잡음)
채점 결과 : 정답
예상 문제 유형 : 구현, 시뮬레이션
시간 : 456 ms
메모리 : 35,464 kb

## 풀이 방법
배열을 달팽이 모양으로 탐색
만약 이동한 위치에 있다면 규칙에 따라 모래 흩뿌리기
0, 0에 도달할 때까지 위의 과정을 반복하고, 끝난 후 격자 밖으로 나간 모래의 양 출력
## 어려웠던 점
1. 달팽이문제에 약한걸 알고 있었지만 이렇게 약할 줄 몰랐음 ->그래서 중간에 달팽이 문제 풀고 다시 옴
 1-1. 근데 달팽이 문제 푸는 방법이 있더라 -> 이건 내 코드에 상세히 설명해 둠.
2. 처음 도전할 때는 문제에 적힌대로 회전하면서 모래를 뿌리려고 했었음.. 근데 이렇게하면 어디가 틀렸는지 디버깅이 아예 불가능(폰 노이만급 천재가 아닌이상)
3. 그래서 그냥 4가지 방향에 대한 모든 뿌리는 좌표를 구하기로 함(이것도 노가다 매우 힘들었음)
4. 모래를 뿌리고 알파 자리에 남은 모래를 더하는데 알파자리도 배열 범위를 벗어나는 경우가 있음<- 이걸 고려하지 못함
5. 위의 에러를 잡는데 또 오래걸림..
6. 결론 : 구현문제 이렇게 나오면 일단 노가다할 생각으로 접근하자.(돌리기? ㄴㄴ 그러다 디버깅도 못함)

**Comment by chanu2** [comment]
고생하셨습니다~
