### ISSUE TITLE
[BaekJoon] 연구소

### ISSUE THREAD

**Issue by reasonyi** [SSAFY12th/ssafyAlgostudy#31]
문제 링크
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV5Pl0Q6ANQDFAUq

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by reasonyi** [comment]
문제 링크
#30 

풀이 사항
풀이 일자: 2024.07.26
풀이 시간: 58분 39초
채점 결과: 정답
예상 문제 유형: 구현/BFS/DFS

풀이 방법
처음 맵을 입력받을 때, 만약 빈공간(0)이라면 빈공간 리스트에 추가, 바이러스(2)라면 바이러스 리스트에 추가하여 따로 기록해둔다.
DFS를 이용하여 벽을 3개 세운다.
벽 3개가 다 세워지면 BFS를 이용하여 바이러스를 전염시킨다. (map 복사본에서)
전염이 끝나면 남아 있는 안전 영역을 구하여 최대값과 비교한다.

**Comment by kimdevspace** [comment]
### 문제 링크
#35 
### 풀이 사항
풀이 일자 : 240730
풀이 시간 : 이틀 ㅋㅋ
채점 결과 : 정답
예상 문제 유형 : 백트래킹, DFS, BFS

### 풀이 방법
빈 공간에 벽을 세 개 세울 수 있는 모든 경우의 수를 고려해야 한다.
벽이 세 개가 세워질 때 bfs를 이용하여 바이러스를 퍼뜨린 후
0의 개수를 세어, 최댓값을 갱신해준다.

**Comment by chanu2** [comment]
문제 링크
#30 

풀이 사항
풀이 일자: 2024.07.31
풀이 시간: 47분 40초
채점 결과: 정답
예상 문제 유형: BFS, DFS, 백트레킹

풀이 방법
입력을 받으면서 2의 위치를 배열로 따로 저장한다.  백트레킹을 통해서 배열에 벽을 3개 무작위로 세운다 depth가 3을 만족하여 벽을 3개 세웠을 때  2차원 배열의 깊은 복사를 통해서 copyArr를 만들고 2의 위치를 기록했던 배열로 bfs를 통해서 바이러스를 퍼뜨려 나간다.  그 후 copyArr를 2중 for문으로 확인하면서 0일 때 count++ 하고 max 값을 갱신해준다.

**Comment by kro46** [comment]
## 문제 링크
#42 
## 풀이 사항
풀이 일자 : 240731
풀이 시간 : 4시간?(고민한 시간까지 합치면 그 이상일듯..)
채점 결과 : 정답
예상 문제 유형 : 백트래킹, DFS, BFS

## 풀이 방법
빈 공간에 벽을 세 개 세울 수 있는 모든 경우의 수를 계산 -> DFS로 구현
벽이 3개 세워지면 BFS를 이용하여 바이러스를 퍼트림- 이 때 반드시 DFS로 받아온 배열을 복사해서 사용해야한다. 
안그러면 BFS를 탈출한 후 DFS를 돌 때 무한 반복에 걸리거나 안전영역의 개수로 0을 출력하게 된다...
0의 개수를 세어, 최댓값을 갱신해준다.

**Comment by haesoooo** [comment]
## 문제 링크
#44
## 풀이 사항
풀이 일자 : 240731
풀이 시간 : 1시간 40분 + (C++에서 자바로 바꾸는데 1억년 걸림..)
채점 결과 : 정답
예상 문제 유형 : 조합, BFS

## 풀이 방법
1. 벽을 세우기 위해서, 0인 곳에 대해서만 좌표를 저장한다 (combi 배열)
2. 벽 3개를 세우기 위해서, combi.size() 중 3개를 뽑는다 (조합)
3. 각 경우의 수마다 원본 맵을 복사해와서 바이러스를 확산시키기 (bfs)
4. 확산이 끝나고 0 (안전구역) 카운팅
5. 모든 경우의 수에 대해서 최댓값 갱신


pair <int, int>로 0인 곳에 대해서 좌표를 받아서 1차원으로 저장
-> 1차원에 대해 조합 확인

**Comment by chanu2** [comment]
end
