### ISSUE TITLE
[BOJ] N-Queen 9663

### ISSUE THREAD

**Issue by kimdevspace** [SSAFY12th/ssafyAlgostudy#33]
문제 링크
https://www.acmicpc.net/problem/9663

### 풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

### 풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by kimdevspace** [comment]
### 문제 링크
#32
### 풀이 사항
풀이 일자 : 240726
풀이 시간 : 59분
채점 결과 : 정답
예상 문제 유형 : 백트래킹

### 풀이 방법
그래프에서 r ,c 값이 있을 때 c 값이 같으면 안됨 (세로 중복 불가) 또 양쪽 대각선이 같으면 안됨. 이를 판별하기 위해 방문 배열을 총 3개를 만들었으며 대각선 중복을 체크하는 방문 배열은 크기를 N의 두배로 설정! why? 체크하는 방식이 r+c와 r-c+N 의 최댓값이 될 수 있기 때문임. 총 세 부분의 예외를 통과 했을 때 dfs로 다음 깊이로 진입! 백트래킹이므로 dfs 탐색이 끝나고 나면 방문 체크를 해제 해주어야 함!

**Comment by chanu2** [comment]
### 문제 링크
#32
### 풀이 사항
풀이 일자 : 240731
풀이 시간 : 1시간20분
채점 결과 : 정답
예상 문제 유형 : 백트래킹

### 풀이 방법
처음 완전 탐색으로 문제를 해결하고자 했지만 n의 최댓값이 14이기 때문에 14의 14승으로 시간 복잡도가 너무 커져서 다른 방식으로 생각해야 했다. 각 행에는 1개의 퀸 만 들어갈 수 있다는 생각을 바탕으로 인덱스를 행으로 갖는 1 차원 배열로 arr를 만들어서 n 번의 백트래킹을 통해서 같은 열에 있는 퀸과 대각선에 있는 퀸 이 존재한다면 넘어가도록 구현했다. 대각선에 퀸의 존재를 판단하는 알고리즘 규칙을 찾는데 어려움을 겪었다.

**Comment by kro46** [comment]
##문제 링크

#42  

풀이 사항
풀이 일자 : 240731
풀이 시간 : 1시간
채점 결과 : 정답
예상 문제 유형 : DFS(백트래킹)

풀이 방법
퀸은 1행당 1개만 놓을 수 있기 때문에 행의 크기만큼 반복한다. 1행에 퀸을 하나 놓고 2행을 탐색 - 이 전에 배치된 퀸과 같은 열이 아니고 대각선에 걸리지도 않는 공간을 탐색한다. 이를 위해 3개의 방문 배열을 생성한다. - 하나는 열 검사용, 두 개는 대각선 검사용으로 활용한다. 3개의 방문 배열을 통해 다음 행에 퀸을 놓을 수 있는 공간을 찾아 계속 이동한다. 최종적으로 판에 놓은 퀸의 개수가 행의 크기와 같으면 count값을 ++한다.

**Comment by reasonyi** [comment]
문제 링크
#43 

풀이 사항
풀이 일자: 2024.08.01
풀이 시간: 55분 37초
채점 결과: 정답
예상 문제 유형: DSF/백트래킹

풀이 방법
처음에 2차원 배열을 이용하여 dfs로 풀이하려 하였으나, 로직을 짜는데 실패하여... 다른 사람의 풀이를 참고하였다.
index값을 열로, value를 행으로 가지는 1차원 배열을 이용하여 체스판을 나타내고, 이를 가지고 문제를 풀이함.
dfs를 활용하여 새로 놓은 퀸이 이전에 놓여진 퀸과 같은 행, 대각선에 위치하는 경우는 퀸을 놓지않고, 아니라면 퀸을 놓아 dfs를 다시 호출하는 형태로 구현

**Comment by haesoooo** [comment]
## 문제 링크

#37

## 풀이 사항
풀이 일자 : 240730
풀이 시간 : 2시간
채점 결과 : 정답
예상 문제 유형 : 백트래킹

## 풀이 방법
행 크기에 대한 1차원 배열 생성 -> dfs 함수 내에서 각 행마다 열의 길이만큼 돌면서 일단 퀸을 배치하고, 해당 위치가 배치 조건을 만족하는지 검증 -> 만족하면 다음 행으로 넘어가서 계속 진행,, -> 마지막 행에 도달한 경우 퀸 배치에 성공한 것이므로 cnt++;

**Comment by kimjuheee** [comment]
#45 

### 풀이사항
풀이 일자 : 240730
풀이 시간 : 4시간
채점 결과 : 정답
예상 문제 유형 : DFS

### 풀이방법

- n+1이면 퀸이 모두 배치되었기 때문에 count 증가
- n의 크기 하나씩 증가하며 map 깊이 증가
- 현재 위치가 합당한 위치인지 체크하는 checkMap 호출
