### ISSUE TITLE
[BOJ] 다리만들기

### ISSUE THREAD

**Issue by chanu2** [SSAFY12th/ssafyAlgostudy#337]
문제 링크
https://www.acmicpc.net/problem/2146

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by chanu2** [comment]
### 문제 링크
#338 
## 풀이 사항
- 풀이 일자 : 241013
- 풀이 시간 : 1시간 13분
- 채점 결과 : 정답
- 예상 문제 유형 : 구현, bfs
- 시간 : 244ms
- 메모리 : 138444kb
### 풀이 방법
1.  bfs 돌면서 map을 섬의 숫자로 각각 변경
2. 2중 for문을 돌면서 최단 거리를 찾는 bfs 구현
3. 종료 조건을 현재 나의 섬과 다른 섬을 만났을 때가 가장 최솟값이라고 생각해서 다른섬을 만나면 최솟값을 갱신, 최솟값보다 값이 클 때도 종료

**Comment by sangholee235** [comment]
### 문제 링크
#342 
### 풀이 사항
- 풀이 일자 : 241014
- 풀이 시간 : 50분
- 채점 결과 : 정답
- 예상 문제 유형 : 너비우선탐색
- 시간 : 548 ms
- 메모리 : 141,872 kb
### 풀이 방법
1. 섬을 구분하며 리스트에 각 섬의 좌표 저장
2. 저장된 좌표를 탐색하며 다른 섬일 경우 거리 갱신

### 복기
맵을 복사해서 상황마다 거리를 재려고 했으나
한 큐 size만큼 distance를 증가한다는 개념으로 풀이함 (새로 배우게 됨)

**Comment by kimdevspace** [comment]
### 문제 링크
#352 
### 풀이 사항
풀이 일자 : 241014
풀이 시간 : 40분
채점 결과 : 정답
예상 문제 유형 : bfs(가중치가없는 최단거리 구하기)
시간 : 348 ms
메모리 : 138,528 kb
### 풀이 방법
1. 섬을 구분하기 위해 섬에 번호를 부여.
2. 번호마다 섬일 수 있는 곳 (= 값이 1인곳) 리스트에 넣기
3. 리스트의 좌표마다 다른 섬이랑 최단거리로 이어지는 값 찾아서 최소로 갱신하기

### 어려웠던 점
dfs로 구현하려다 좀 어려웠음
가중치가 없는 최단거리 => 아묻따 bfs를 기억하자

**Comment by haesoooo** [comment]
## 문제 링크
#355

## 풀이 사항
풀이 일자 : 241016
풀이 시간 : 1시간 30분
채점 결과 : 정답
예상 문제 유형 : BFS/DFS
시간 : 288 ms
메모리 : 78,480 kb

## 풀이 방법
1. map에서 섬들을 dfs로 라벨링 -> tempmap에 각 섬 idx 저장
2. 큐 배열을 만들어서 각 섬의 좌표를 저장한 큐를 queues[idx]에 대입
3. 각 섬마다 visited 배열 초기화, bfs 시작 전에 시작 섬의 좌표들은 모두 방문 처리
4. bfs()
    - 현재 queues[idx]에 들어있는 시작 좌표들에 대해 동시에 탐색 진행 (q.size만큼 for문 돌리면서 for문이 끝나면 거리를 증가)
    - 탐색 : 다음 좌표가 0일 때 그 좌표 방문 처리해주고 큐에 저장
    - 만약 map 상에서 다음 좌표가 1이면서 tempmap에서 != idx 라면 다른 섬이라는 의미이므로 거리 리턴하고 종료
5. 각 섬마다 bfs 진행하며 리턴한 거리값을 최소 비교 갱신

## 어려웠던 점
- 처음에는 각 섬의 외곽선만 따서 해당 좌표들에서만 bfs를 진행할 수 있도록 구현하였음.
- 외곽선의 기준은 상하좌우에서 0을 만난다면 분류하도록 정했는데, 0을 만나더라도 외곽선이 아닌 경우가 존재하는 것을 간과
- 그래서 그냥 단순 dfs로 섬 라벨링을 진행하도록 변경,,

- 그리고 진짜 한 60%에서 20번 넘게 메모리 초과나서 너무 힘들었다 ㅠ^ㅠ.. 문제는 bfs를 돌 때 방문 여부 체크하는 부분에 있었다
- 항상 bfs를 진행할 때 아무 생각 없이 큐에서 꺼내서 visited 처리 했는데, **현재 큐에 들어있는 좌표들을 동시에 탐색 진행시키려면 다음 좌표들을 탐색하면서 "큐에 넣을 때 방문 처리"해야된다 !!!!**
- 그리고 섬이 1번부터 3번까지 있다고 치면 1 -> 2, 1 -> 3, 2 -> 3 이런식으로 내 idx보다 큰 섬에 대해서만 탐색하는 방식으로 하면 1 -> 2, 2 -> 1 이런식으로 중복 탐색을 안할 수 있어서 더 빨라질 것 같은데 그 부분을 구현하는건 실패햇다.. 어떻게 하면 좋을까 ??

**Comment by reasonyi** [comment]
## 문제 링크
#359 

## 풀이 사항
풀이 일자 : 241016
풀이 시간 : 24분
채점 결과 : 정답
예상 문제 유형 : BFS/DFS
시간 : 260 ms
메모리 : 138,304 kb

## 풀이 방법
1. 처음에 섬의 위치를 받을 때 1을 -1로 변경해준다.
2. bfs를 활용하여 map에서 -1인 위치를 섬의 번호로 변경한다. (섬마다 번호를 매김)
3. 맵 전체를 돌면서 0이 아닌 위치(섬)를 발견하면 다리 놓기를 시도한다.
4. bfs를 활용하여 다리를 놓기 시작하는데, 방문하지 않았으면서 현재 섬 번호와 다른 위치로만 이동한다. (섬이 없거나 다른 섬인 곳으로만 이동.)
5. 큐에서 꺼냈을 때 현재 위치가 처음 시작한 섬과 다른 섬이라면 다리 길이의 최소값 갱신 후 다리 놓기 종료.

## 느낀점
- 다리만들기2에서 했던 섬 번호 매기기 방법을 그대로 사용해서 수월하게 풀 수 있었던 것 같다.
- 해수의 코드를 봤는데... 메모리가 거의 2배 차이나는 것은 내가 섬 번호 매기기도 bfs로 했기 때문인가??? 바꾸면 확 줄일 수 있을까?? 이후에 다시 작성해봐야할 것 같다.
