### ISSUE TITLE
[BOJ] 캐슬디펜스

### ISSUE THREAD

**Issue by chanu2** [SSAFY12th/ssafyAlgostudy#339]
문제 링크
https://www.acmicpc.net/problem/17135

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by chanu2** [comment]
### 문제 링크
#340 
## 풀이 사항
- 풀이 일자 : 241012
- 풀이 시간 : 2시간 11분
- 채점 결과 : 정답
- 예상 문제 유형 : 구현, bfs
- 시간 : 840ms
- 메모리 : 104768kb
### 풀이 방법
1.  궁수 위치를 중복 순열로  List 저장
2. map을 copy 해서 새로운 배열 생성
3. 모든 적의 위치를 매번 최신화 하여  List에 저장
4. 궁수 3명 모두 for문 돌면서 가장 가깝고 가장 가까운 index(저장한 적의 list의 index)를 찾아는다.
5. hashSet으로 중복재거
6. copyMap 최신화 
7. 적 한칸식 모두 내리기 
8. 적 List 비어있으면 종료

## 어려웠던점 
- 문제를 잘 읽어야겠다. 궁수 위치가 성에 있다는 것을 못보고 처음에 마음대로 2차원 배열 조합으로 궁수를 놨습니다,,,

**Comment by sangholee235** [comment]
### 문제링크
#341 
### 풀이 사항
- 풀이 일자 : 241013
- 풀이 시간 : 1시간
- 채점 결과 : 정답
- 예상 문제 유형 : 완전탐색
- 시간 : 196ms
- 메모리 : 26,268 kb
### 풀이 방법
1. 중복순열을 통해 궁수 배치
2. 궁수 배치가 완료 되면 시뮬레이션
2-1. 사거리내에 적이 있다면 제일 가깝고 거리가 같다면 최좌단 적을 타겟팅
2-2. 적 타겟팅시 HashSet으로 중복 불가능하게 고르기
3. 타겟 제거 후 맵 내리기

### 어려웠던점
1, 맵 내릴때 clone 안써서 헤맸습니다.
2. 중복순열 만들때 궁수 저장 사이즈 [M]으로 해서 틀렸습니다 [3]이 맞음

**Comment by reasonyi** [comment]
### 문제링크
#357 

### 풀이 사항
- 풀이 일자 : 241016
- 풀이 시간 : 2시간 15분
- 채점 결과 : 정답
- 예상 문제 유형 : 완전탐색, 구현
- 시간 : 292ms
- 메모리 : 29,348 kb

### 풀이 방법
- 조합으로 가능한 궁수 배치를 전부 뽑아 변수에 저장한다.
- 뽑아놓은 궁수 배치 조합만큼 반복하면서 적의 위치를 복사하여 각 궁수 별 죽이는 적의 위치를 저장한다.
- 중복해서 활을 쏘는 경우까지 생각하여 죽인 적의 명수를 구해 cnt에 저장하고, 남아있는 적의 위치를 아래로 한 칸 내린다. 이때 맵을 벗어나는 경우 고려 대상에서 삭제한다.
- 모든 조합마다 반복하여 가장 큰 cnt값을 구하고 출력한다.

### 어려웠던점
- 최대한 시간 줄여보겠다고 맵을 저장 안하고 적의 위치만 저장했는데... 맵이 작아서 그냥 맵 전체 순회하고 내리고 하는게 더 빠르게 걸릴 것 같다고 생각했다.
- 적의 위치를 저장해서 푸니까 구현하는데 머리아팠다

**Comment by kimdevspace** [comment]
### 문제링크
#358 
### 풀이사항
풀이일자: 241016
풀이시간: 10월15일 두시간 풀다가 포기, 10월16일 1시간
채점결과: 정답
예상 문제 유형 : 완탐, 시뮬레이션
시간: 384ms
메모리 : 52,232kb
### 풀이방법
1. 조합으로 궁수가 위치할 수 있는 모든 곳 탐색
2. 궁수가 타겟으로 하는 적의 위치를 정해주고 적절한 자료구조에 담아야 함. 타겟의 조건을 만족하는 적이 여러개라면 가장 왼쪽의 적을 타겟으로 삼아야 함
3. 타겟은 중복이 발생할 수 있기 때문에 Set으로 저장. 타겟을 정했으면 제거 후 개수 최댓값으로 갱신해주기
### 어려웠던 점
궁수의 타겟이 되는 조건 중 동일 조건이 여러개라면 가장 왼쪽의 적을 갱신해주는 로직이 어려웠어요..
조건을 만족할 때마다 거리를 최소로, 타겟의 좌표의 컬럼값을 최소로, 그리고 그 타겟을 정해주어야 함.
조건1. 거리가 최소여야 함
조건2. 거리가 최소일 때는 현재 열 값이 최소여야 함.

널값이 아닐때만 타겟을 정해주기.

**Comment by haesoooo** [comment]
### 문제링크
#360 🍥🍥🍥

### 풀이 사항
- 풀이 일자 : 241016
- 풀이 시간 : 2시간 15분
- 채점 결과 : 정답
- 예상 문제 유형 : 완전탐색, 구현
- 시간 : 292ms
- 메모리 : 29,348 kb

### 풀이 방법
- mC3 조합으로 궁수 3명의 열 위치만 뽑기 (행 위치는 N으로 고정)
- 각 경우의 수마다 시뮬레이션을 진행해야 하므로 맵이나 변수 등 카피
while(temptotal) {
 1. 각 열마다 가장 밑에 있는 적의 행 위치 저장 (maxRows[])
 2. 각 궁수마다 (3명) 열 별로 탐색하며 가장 가까운 적의 위치를 저장한다. 이 때 가장 가까운 적과의 거리가 D 이하라면 위치를 (-1, -1)로 표기
 3. 각 궁수마다 공격할 좌표가 (-1, -1)이 아니라면 공격한다 (해당 위치 0으로 만들고, temptotal--, curAns++)
 4. 공격이 모두 끝나면 적군 모두 아래로 이동 (N - 1행에 있던 애들은 그냥 없애고, 그 수만큼 temptotal++)
}
모든 경우의 수가 끝날 때마다 curAns를 최대로 비교 갱신한다.

### 어려웠던점

- 이 문제는 테케는 다 맞는데 계속 1%에서 틀려서 계속 생각해봤는데 내가 구현했던 궁수 - 적 간 거리 계산 로직 때문에 틀렷다.
- 내가 설계한 로직 : 현재 궁수의 위치 기준으로 -1, 0, +1 열에 대해서만 탐색해준다. 그거보다 멀면 고려대상이 아니라고 생각했다 ..
- 이슈 쓰면서 생각해보니까 당연히 적이 그거보다 멀리 있을 수도 있겠다 ..... 바보다
- 구현은 세부적인 아이디어를 한 번 잘못 생각하면 개망하는듯.

**Comment by kro46** [comment]
## 문제 링크
#369

 ## 풀이 사항
풀이 일자 : 241017
풀이 시간 : 3시간 16분
채점 결과 : 정답
예상 문제 유형 : 구현, DFS / BFS
시간 : 416ms
메모리 : 54,200kb

## 풀이 방법
1. 궁수 위치를 조합으로 List 저장
2. map을 copy 해서 새로운 배열 생성
3. Map을 확인하여 적이 있으면 공격을 수행, 아니면 sum을 kill과 비교하여 업데이트
4. 공격을 수행하기 전에 모든 적의 위치를 매번 최신화 하여 List에 저장
5. 궁수의 위치와 적의 위치를 비교하여 거리를 구하고 그 중 거리 차이가 D보다 작은 적들 PQ에 저장
6. PQ는 거리가 가까운 순으로 정렬하고, 만약 두 원소의 거리가 같으면 c가 작은 순으로 정렬
7. pq에서 하나를 뽑아서 해당 위치 값이 1이면 0으로 만들고 count++; / 아니면 그냥 넘어감
8. 적들 위치를 한 칸 씩 내림
9. 2~8까지 반복하다가 모든 경우의 수를 다 처리하면 return

## 어려웠던점
할많하않..... 
님들 저 3시간 고민했는데 compareTo()를 오름차순으로 구현(c가 작은 순으로 정렬해야하는데 큰 순으로 정렬해놨음)이 반대로 되어있었어요. ㅠㅠㅠㅠㅠ(근데 이래도 예제 테스트케이스가 다 돌아가서 혼자 쉐도우복싱 오지게함)
