### ISSUE TITLE
[PGS] 퍼즐 게임 챌린지

### ISSUE THREAD

**Issue by sangholee235** [SSAFY12th/ssafyAlgostudy#344]
문제 링크
https://school.programmers.co.kr/learn/courses/30/lessons/340212

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by chanu2** [comment]
### 문제링크
#345 
### 풀이 사항
- 풀이 일자 : 241014
- 풀이 시간 : 3시간
- 채점 결과 : 정답
- 예상 문제 유형 : 이분 탐색
- 테스트 15  (60.98ms, 142MB)

### 풀이 방법
1. low =1 , high = 100000으로 설정해서 이분탐색 진행
2. mid로 계산 후에 limit을 넘지 않으면  high = level - 1 넘었을 때 low = level +1
3. low가 high를 역전하면 stop

### 어려웠던점
1. 이분탐색 자체에 어려움이 있어서 강의 보고 공부했습니다. 
2. 종료 조건과 low와 high가 만날 때를 항상 잘 생각해야 겠다고 생각했습니다

**Comment by haesoooo** [comment]
### 문제링크
#346
### 풀이 사항
- 풀이 일자 : 241015
- 풀이 시간 : 45분
- 채점 결과 : 정답
- 예상 문제 유형 : 이분 탐색, 매개변수 탐색
- 테스트 15 (39.02ms, 115MB)

### 풀이 방법
최적화 문제이기 때문에 결정 문제로 바꾸어줌
- 최적화 : 제한 시간 (limit) 내에 모든 퍼즐을 통과할 수 있는 "최소 레벨"을 찾기
- 결정 : 레벨이 midlevel일 때, 제한시간 내로 통과 "가능한가 아닌가"

어떤 변수 간에 반비례 관계가 있는가 → 레벨과 소요시간

1. level을 param으로 두고, 각 level에서 모든 퍼즐 탐색
2. 모든 퍼즐에 대해서 time 계산 
3. 계산한 time이 limit을 초과한다면 left = mid + 1
4. 이하라면 right = mid - 1, ans와 최소 비교 갱신
5. low <= high가 역전될 때 종료

### 어려웠던점
1. 어떤 변수들 간에 반비례 관계가 존재하고, 어떤 것을 파라미터로 지정하여 이분탐색을 진행할 것인지 등을 설계하는 단계가 어려웠다.

**Comment by kimdevspace** [comment]
### 문제링크
#356 
### 풀이사항
풀이일자:241016
풀이시간:1시간1분
채점결과:정답
예상문제유형:바이너리서치
테스트 15 (44.61ms, 140MB)
### 풀이방법
1. 숙련도가 제일 높을 때 모든 퍼즐을 최소의 시간으로 맞출 수 있음, 제일 낮을 때 제일 오래걸림.
2. 입력받은 퍼즐의 난이도의 최소, 최대를 찾아 값을 정해줌
3. 이분탐색으로 limit이하의 최댓값을 갖는 숙련도를 찾으면 됨
### 어려웠던 점
문제의 가독성이 저만 안좋았나요 아님 제가 난독인걸까요
국어문제같음;;

**Comment by kro46** [comment]
## 문제링크
#361 
## 풀이 사항
풀이 일자 : 241016
풀이 시간 : 1시간 20분
채점 결과 : 정답
예상 문제 유형 : 이분 탐색, 매개변수 탐색
테스트 17 (44.20ms, 134MB)

## 풀이 방법
1. level에 따른 총 시간을 구하기 위해 cal()메서드를 구현한다. 
2. cal(level)을 주고 나온 값을 limit와 비교하여 같거나 작으면 right를 mid로 옮기고, limt보다 크면 left를 mid+1로 옮긴다.
3. 그 후 다시 while문 처음으로 돌아와서 mid를 재지정한다.
4. 위의 비교를 left가 right를 넘는 순간까지 반복한다.
5. right는 항상 limit와 같거나 작은 값을 유지하기 때문에 answer로 right값을 대입하고 리턴한다.

## 어려웠던점
프로그래머스의 코딩 환경 자체가 익숙하지 않아서 디버깅에 애를 먹었음. 또한 매개변수로 선정한 값을 limit와 비교할 때 어떤 부등호나 등호를 써야할지 고민을 많이했다. 
예를 들어, cal()값이 limit보다 작으면(혹은 크면 혹은 같으면) left를 옮기는게 맞는지 right를 옮기는게 맞는지 잘 선택해야했다.
