### ISSUE TITLE
[PGS] 입국심사

### ISSUE THREAD

**Issue by sangholee235** [SSAFY12th/ssafyAlgostudy#348]
문제 링크
https://school.programmers.co.kr/learn/courses/30/lessons/43238

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by sangholee235** [comment]
### 문제링크
#347 
### 풀이 사항
- 풀이 일자 : 241015
- 풀이 시간 : 30분
- 채점 결과 : 정답
- 예상 문제 유형 : 이분 탐색
- 시간 : 60 ms
- 메모리 : 100 mb
- 
### 풀이 방법
1. 찾아야할 매개변수 찾기 -> 모든 사람 처리하는 시간
2. 최악의 경우까지 범위 설정 -> 가장 빠른 처리 시간 * n (times[0] * n)
3. 이분탐색 시작 
  3-1. 시간 내 처리 가능 할 경우 right = mid - 1;
  3-2. 처리 불가능 할 경우 left = mid + 1;
4. left 리턴

### 복기
1.이분탐색의 경우 현재 매개변수로 가능한지 체크하는 메서드를 만들어야 하는 경우가 많은데
그 조건을 찾는게 생각보다 느렸다
2. 당연히 mid 만 찾는거라고 생각했는데 left를 리턴해야함을 알았다
3. 이분탐색으로 답을 찾는 경우 N이 매우 클 가능성이 높은데 int 형으로 선언하면 어려운 경우가 많다
데이터 타입을 잘 주자

**Comment by haesoooo** [comment]
### 문제링크
#351
### 풀이 사항
- 풀이 일자 : 241015
- 풀이 시간 : 27분
- 채점 결과 : 정답
- 예상 문제 유형 : 이분 탐색, 매개변수 탐색
- 시간 : 72 ms
- 메모리 : 82 mb
- 
### 풀이 방법
1.  left : 0
2. right : 최대 심사 시간 * n
3. param을 시간으로 지정하여, 해당 시간동안 각 심사관들이 심사할 수 있는 사람 수를 계산
4. 모든 사람 수를 합산
5. if) n명 이상 -> midtime과 현재 answer를 최소 비교 갱신, 시간 더 줄여도 되니까 right = midtime - 1;
6. else -> 시간 늘려야하므로 left = midtime + 1;

### 느낀점

- 최적화 문제 : n명의 사람을 심사하기 위해 times.size() 명의 심사관이 나눠 심사할 때 소요되는 **최소 시간"" 구하기
- 결정 문제 : K분의 시간이 주어질 때 각 심사관이 심사할 수 있는 사람 수를 모두 더했을 때 **n명 심사 가능한가 아닌가**

- O(MN)의 시간복잡도에서 O(MlogN)으로 줄인다 (M은 10만, N은 10억이었으므로)

최적화문제에서 구하고자 하는 변수를 결정문제에서는 param으로 활용하는 방안을 고려하는 것이 좋다.
매개변수 탐색은 값을 찾았다고 바로 리턴하고 끝나는 것이 아니라 어떤 지점에서 true -> false 혹은 false -> true로 변하는지를 확인해야한다. 그래서 그 답까지 계속 범위를 좁혀나감. 결국에 true/false 가 변하는 것은 딱 한번이기 때문

**Comment by reasonyi** [comment]
### 문제링크
#354 

### 풀이 사항
- 풀이 일자 : 241016
- 풀이 시간 : 12분
- 채점 결과 : 정답
- 예상 문제 유형 : 이분 탐색, 매개변수 탐색
- 테스트 4 (71.28ms, 81MB)

### 풀이 방법
- 심사를 받는 데 걸리는 시간을 기준으로 이분탐색을 진행하여 모든 사람이 심사를 받는데 걸리는 최소 시간을 찾는다.
- left = 1, right = 1,000,000,000,000,000,000 (10^18)
- mid는 심사하는 데 걸리는 시간제한이라고 생각하고, time으로 나눠 최대 몇 명이 심사를 받을 수 있는지 구한다
- 최대 심사 가능 인원이 n보다 크거나 같으면 right = mid-1, 작으면 left = mid+1;
- 최솟값을 구하는 것이니 left를 return 한다. 

### 어려웠던 점
- long을 안 써줘서 틀렸다... 
- 그리고 right 설정할 때 원래 최대 시간 * n으로 설정했는데 안 돼서... 그냥 최대 n * 최대 시간으로 해줬다. 그랬더니 10^18이 되었다...

**Comment by chanu2** [comment]
### 문제링크

### 풀이 사항
- 풀이 일자 : 241016
- 풀이 시간 : 1시간 10분
- 채점 결과 : 정답
- 예상 문제 유형 : 이분 탐색, 매개변수 탐색
- 테스트 4 (59.36ms, 92.3MB)

### 풀이 방법
- 모든 사람이 심사를 받는 기준으로 이분탐색진행
- low= 1, rhigh = 1,000,000,000,000,000,000
- mid를 times로 나눠서 count를 구한다.
- count n보다 크거나 같으면 high = mid - 1, 작으면 low= mid+1;
- 마지막 상황을 보면 high < low 이므로 low 리턴

### 어려웠던 점
- 모든 사람이 심사를 받는 기준으로 이분탐색을 해야 하는지 찾기 어려웠다.
- long범위를 넘어가기 때문에 그것에 대한 처리를 해줘야 하는 것을 인지하기 어려웠다.

**Comment by kro46** [comment]
## 문제링크
#362 

## 풀이 사항
풀이 일자 : 241016
풀이 시간 : 1시간 15분
채점 결과 : 정답
예상 문제 유형 : 이분 탐색, 매개변수 탐색
테스트 7 (141.38ms, 96.5MB)

## 풀이 방법
1. 이분탐색 시작 전에 times배열을 정렬해준다.
2. left = 0, right = 10억 * times의 마지막 원소로 값을 설정해준다.
3. mid값을 times[i]로 나눠서 그 결과를 리턴하기 위해 compare()메서드를 구현한다.
4. compare()의 값이 n보다 크거나 같으면 right를 mid로 옮겨주고, 아니면 left를 mid + 1로 옮겨준다. => lower bound
5. 반복이 끝나면 right를 반환한다.

## 어려웠던 점
1. 처음에 문제를 접했을 때는 count를 time으로 나눌 생각을 못해서 visited배열 만들어서 큐로 풀려고했는데, 생각해보니 그러면 시간초과가 날거라서 다른 방법을 찾아야했음. 그런데 바로 떠오르지 않아서 힌트를 보고 다시 풀었음.
2. 위의 아이디어를 얻고나서 구현은 10분도 안걸렸는데 long형으로 안바꿔줘서 테케가 자꾸 4개만 맞음. 그러다 찬우가 적어놓은 이슈글 보고 수정하여 바로 통과!

**Comment by kimdevspace** [comment]
### 문제링크
#363 
### 풀이사항
풀이일자: 241017
풀이시간: 1시간20분
채점결과: 정답
예상 문제 유형: 매개변수탐색
테스트 7 〉 | 통과 (88.12ms, 97.5MB)
### 풀이방법
모든 사람이 입국심사하는데 걸리는 최악의 시간은 n * 심사시간최댓값임
1부터 n*심사시간 최댓값 범위 내에서 매개변수 탐색!
모든 사람이 통과할 수 있으면 범위를 고정해주고 최솟값의 범위를 고정해주면서 최솟값을 찾아줍니다요.
### 어려웠던 점
매개변수탐색이 어려워 현규형님께 배웠습니다.
매개변수탐색을 어느때 사용하는지, 최대를 구할때와 최소를 구할때 다르다는 것도 배웠습니다.
완탐류 문제만 하다가 이런 머리쓰는 문제 푸니까 새롭네여
