### ISSUE TITLE
[PGS] 징검다리

### ISSUE THREAD

**Issue by haesoooo** [SSAFY12th/ssafyAlgostudy#372]
### 문제 링크
https://school.programmers.co.kr/learn/courses/30/lessons/43236

### 풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

### 풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by haesoooo** [comment]
### 문제링크
#371

### 풀이사항
풀이일자: 2024.10.18
풀이시간: 25분
채점결과: 정답
예상 문제 유형: 이분탐색, 매개변수 탐색
시간: 테스트 34) 28.80ms
메모리: 90.3MB

### 풀이방법
- 공유기 설치 문제 반대로 풀었다.
- **결정문제 : 가장 인접한 돌 간의 거리를 K라고 했을 때 N개의 돌을 제거할 수 있는가? (전체 - N개 만큼 남길 수 있는가?)**
- N개를 제거한다 -> 돌 개수 - N개 만큼 남길 돌을 선택한다.
- 첫 돌은 무조건 선택한다.
- 선택한 돌에 대해서는 prevIdx를 갱신해주고 선택했다는 의미로 cnt++
- if (cnt >= 전체 돌 개수 (rocks.length + 2) - N) 라면 돌 간 거리를 더 키워도 조건을 충족한다는 뜻이니까 answer 갱신하고 left = mid + 1;

### 어려웠던 점
- 문제가 불친절한게 .. 첫번째 지점의 돌 (0)과 마지막 지점의 돌 (distance)도 존재한다고 두고 풀어야 함. 처음엔 그 두 개를 제외하고 풀었다가 60퍼만 맞았다.

**Comment by sangholee235** [comment]
### 문제링크
#377

### 풀이사항
풀이일자: 2024.10.19
풀이시간: 3시간
채점결과: 정답
예상 문제 유형: 이진탐색
시간: 테스트 34) 27 ms
메모리: 80 mb

### 풀이방법
1. 바위 위치 정렬 (최초 미정렬 상태)
2. 정렬된 바위 간의 거리를 배열로 저장
3. left = 0 right = distance (최악)
4. mid 값만큼 바위를 깼을때 몇개의 바위를 제거 할 수 있는지 확인
4-1. 더 많이 제거되면 실패 : right = mid - 1;
4-2-1. 성공하면 answer = mid 로 갱신 (일단 저장 해두기)
4-2-2. left = mid + 1; (더 큰 mid값으로 시도 해보기) 
5. left가 right를 역전하는 시점의 answer 값을 return


### 어려웠던 점
1. 이분탐색 문제라는 것을 판단하는것 자체가 어려웠음
2. left = 0 right = distance 라는것을 인지 했음에도 성공여부를 판단하는 메서드를 작성하기 어려웠음
3. mid값으로 성공을 하는지 판단하는 로직을 생각했음에도 구현에 어려움을 겪음

**Comment by reasonyi** [comment]
### 문제링크
#388 

### 풀이사항
풀이일자: 2024.10.22
풀이시간: 23분
채점결과: 정답
예상 문제 유형: 이진탐색, 매개변수탐색
시간 및 메모리:
  테스트 34) 27.65ms, 80.1MB
  가장 오래 걸린 경우: 테스트 7) 38.28ms, 87.5MB

### 풀이방법
- 바위 위치 정렬
- 정렬된 바위 간 거리를 구해 배열에 저장
- left = 0 right = distance (최악)
- 최소 거리를 매개변수로 정하여, 해당 거리보다 더 짧은 돌 사이의 거리가 있다면 제거한다.
- left및 right의 범위를 지정할 때, 제거한 돌의 개수가 n과 같거나 작은 경우 left를 mid+1로 갱신한다.
- (left가 n과 같은 값 중 가장 큰 값을 찾아 mid+1이 되어 범위에 더 이상 n과 같은 값이 포함되지 않더라도, right가 무조건 mid-1로 n과 같은 값중 가장 큰 값을 포함하게 되기 때문에 조건 설정을 이렇게 해줄 수 있다.)
- 이후 n과 같은 값 중 가장 큰 값을 찾아야하므로, right 를 return

### 어려웠던 점
- 문제를 계속 읽어봤는데, 전혀 풀어본 적 없는 유형이라 못풀 것 같아서 다른 사람의 해설을 참고했다.
- 어떤 것을 기준으로 잡을건지 정한 뒤 left, right값을 정하는 것, 중간에 들어가는 구현을 생각해내는 것이 어려운 것 같다.
- 생각을 해내도 그냥 푸는게 어렵다

**Comment by kro46** [comment]
## 문제링크
#389 

## 풀이사항
풀이일자: 2024.10.22
풀이시간: 3시간 26분
채점결과: 정답
예상 문제 유형: 이진탐색, 매개변수탐색
시간 및 메모리: 테스트 39) 51.90ms, 91.2MB

## 풀이방법
1. 바위 정렬
2. 정렬된 바위 간 거리를 구해 diff 리스트에 저장
3. left = min(diff), right = distance로 설정
4. 최소 거리를 매개변수로 정하여, 최솟값으로 mid를 쓸 수 있는지 조건함수를 통해 검사
5. 조건함수: rocks배열을 돌면서 이전 바위와의 거리차가 mid보다 작으면 이전 바위를 제거하고 아니라면 이전 바위로 현재 바위를 지정 -> 이 때, 제거한 바위의 개수가 n을 넘으면 false를 리턴
6. mid가 조건함수를 통과하면(최솟값으로 쓸 수 있으면) left = mid + 1 & answer = mid, 통과하지 못하면 right = mid - 1로 지정
7. 이 문제는 최댓값을 찾는 upper bound문제이기 때문에 while(left <= right)로 겹친 상황까지 고려하는 조건을 주었음.

## 어려웠던 점
아이디어가 떠오르지 않으면 절대 못 풀 문제였고, upper bound와 lower bound에 대한 충분한 학습이 필요한 문제였다.
이분탐색 문제를 어렵게 내면 왜 정답률이 1~2%라고 하는지 알게 되었다...

**Comment by kimdevspace** [comment]
### 문제링크
#391 
### 풀이사항
풀이일자: 241023
풀이시간: 59분
채점결과: 정답
예상문제유형: 매탐
시간,메모리: TC6 39.81ms, 88.4MB
### 풀이방법
mid(거리) 값에 대해 바위를 n개 이하로 제거하며 mid 이상 간격을 유지할 수 있는 mid의 최댓값을 구하는 문제

0과 distance로 시작하여 mid일 때 바위들을 n개 이하로 제거하여 mid 이상 간격을 유지할 수 있는 mid의 최댓값을 구한다.

### 어려웠던 점
이분탐색 매개변수탐색은 노력으로 될까요? 재능타는거같은데

**Comment by chanu2** [comment]
### 문제링크
#396 

### 풀이사항
풀이일자: 2024.10.23
풀이시간: 2시간 55분
채점결과: 정답
예상 문제 유형: 이진탐색
시간: 테스트  34 (40.11ms, 90.1MB)
메모리:  90.1MB

### 풀이방법
1. 바위 배열 정렬
2. 매개 변수를 돌 사이의 거리로 두고 이분 탐색 진행
3. 바위 사이의 거리를 구한다.  
4.  for 문을 돌면서 거리의 합이 mid 미만 일때 까지  바위를 부숴나간다.  이상이라면 현재 값을 저장하고 현재값을 기준으로 바위를 다시 부숴나간다. 왼쪽으로만 봤기 때문에 distance에서 저장된 마지막 값을 비교하여 최종적으로 바위가 부서지는 계수를 구한다.
5. 이분탐색을 진행한다. 
6. mid <= n   때 answer = mid를 넣고 low = mid + 1; 한다.

### 어려웠던 점
1. 이분탐색 문제라는 것을 판단하는것 자체가 어려웠음
2. 돌 사이의 거리를 구하는 구현이 어려웠다.
3. 돌사이의 거리를 구할 때 왼쪽과 오른쪽을 다 확인하지 않아도 되는 것을 아는데 이해가 오래걸렸다 (강사님 찬스)
