### ISSUE TITLE
[BOJ] 전기가 부족해

### ISSUE THREAD

**Issue by kimdevspace** [SSAFY12th/ssafyAlgostudy#374]
문제 링크
https://www.acmicpc.net/problem/10423

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by kimdevspace** [comment]
### 문제링크
#373 
### 풀이사항
풀이 일자: 241018
풀이 시간: 1시간
채점 결과: 정답
예상 문제 유형: 최소 스패닝 트리
시간: 532ms
메모리: 49,800kb
### 풀이방법
발전소에 연결 되어 있다면 연결을 해주지 않기 위해 처음에 boolean 배열을 이용하여 발전소를 기록해두었음.
내 지능상 도저히 안풀려서 답지를 보고 공부했습니다요.

발전소를 서로소 집합에서 -1로 표현하고 푸는 풀이입니다.

1. 기본적인 풀이는 크루스칼 풀이임
2. union 메서드에서 노드들의 부모노드가 -1로 둘 다 같다? -> 서로 발전소에 연결 되어있으므로 return;
    다르면? 노드들의 입력을 x 와 y라고 할 때 x 가 -1(발전소)면 y를 -1로 바꾸어서 발전소에 연결! 반대로 y가 발전소면 x를 발전소에 연결!,,,,,,,,만약 둘다 아니라면 그냥 연결

크루스칼을 하다가 노드들이 모두 발전소에 연결되어 있다면(checked메서드) 로직 종료

**Comment by kro46** [comment]
## 문제링크
#375 

## 풀이사항
풀이 일자: 241018
풀이 시간: 1시간 20분
채점 결과: 정답
예상 문제 유형: 최소 스패닝 트리
시간: 588ms
메모리: 49,440kb

## 풀이방법
1. 0번 노드에 발전소들을 미리 먼저 연결 해놓음
2. 간선정보를 모두 간선리스트에 저장
3. 크루스칼을 돌리는데 탈출조건을 N+K-1로 지정(K개는 0번 노드와 발전소 연결한 간선)

## 어려웠던 점
아이디어가 은근 떠올리기 어려웠음. 처음에는 발전소마다 최소스패닝을 돌려서 가장 비용이 낮은 걸 고르는 방식을 생각했는데
N이 10만이라 아무리봐도 터질거같아서 생각을 바꿈. 근데 이 아이디어 떠오르기만하면 무조건 5분컷임

**Comment by sangholee235** [comment]
## 문제링크
#376 

## 풀이사항
풀이 일자: 241018
풀이 시간: 1시간
채점 결과: 정답
예상 문제 유형: 최소 스패닝 트리
시간: 548ms
메모리: 50,656 kb

## 풀이방법
1. 간선 비용이 저렴한 순서로 정렬
2. 발전소 정점끼리 union 연산
-> 발전소를 하나의 부모로 통일 해두면, 이미 발전소와 연결된 정점은 사이클이 형성되어 선택되지 아니함
-> 그러면 발전소는 하나만 연결 되고 최소 비용으로 선택
4. 크루스칼로 최소 스패닝 트리 만들기

## 어려웠던 점
발전소를 미리 연결한다는 개념을 떠올리는게 쉽지 않았음
발전소는 한번만 연결 되어야 한다는 정보로 찾게되었음

**Comment by reasonyi** [comment]
## 문제링크
#385 

## 풀이사항
풀이 일자: 241022
풀이 시간: 20분
채점 결과: 정답
예상 문제 유형: MST
시간: 412 ms
메모리: 46,680 kb

## 풀이방법
- 입력받을 것을 모두 입력받고, make 하는 과정에서 발전소 위치의 부모는 0으로 통일한다 (이미 연결된 것으로 간주하여 여러 발전소가 하나의 지역에 연결되는 것을 막는다. 0번지역은 사용하지 않기 때문에 이렇게 했음!)
- 크루스칼

## 느낀점
처음에 갈피가 좀 안잡혔는데 그림그리듯 생각하니까 금방 풀 수 있었던 것 같다. 안풀릴 땐 역시 시각화

**Comment by chanu2** [comment]
## 문제링크
#393 

## 풀이사항
풀이 일자: 241022
풀이 시간: 1시간 30분
채점 결과: 정답
예상 문제 유형: 최소 스패닝 트리
시간: 548ms
메모리: 48772kb

## 풀이방법
1. 0번 노드에 발전소들의 부모를 정해준다 
2. 크루스칼 알고리즘 적용 


## 어려웠던 점
아이디어 떠오르는게 어려워서 사람들한테 물어봤다. 아이디어 생각하는게 어려운 것 같다

**Comment by haesoooo** [comment]
## 문제링크
#398

## 풀이사항
풀이 일자: 241022
풀이 시간: 1시간 50분
채점 결과: 정답
예상 문제 유형: 최소 스패닝 트리
시간: 500ms
메모리: 51890kb

## 풀이방법
1. 발전소들을 먼저 정점 방문처리 후, 해당 발전소들과 연결된 간선들을 모두 확인한다.
2. 프림 알고리즘 적용


## 어려웠던 점
처음에 크루스칼로 풀려고 하니까 정점(도시) 간의 관계가 직관적이지 않아서 프림으로 풀었다.
큐에 동시에 넣고 트리를 생성하면 별도로  발전소 여부를 확인해줄 필요가 없다. -> 이걸 생각하기까지 너무 오래걸렸다..
MST를 너무 공식적으로 풀다보니까 조금만 문제에 변화를 주어도 아이디어를 잘 못 떠올리는 것 같다 ,...
