### ISSUE TITLE
[BOJ] 점심메뉴 

### ISSUE THREAD

**Issue by sangholee235** [SSAFY12th/ssafyAlgostudy#380]
문제 링크
https://www.acmicpc.net/problem/12099

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by sangholee235** [comment]
## 문제링크
#378

## 풀이사항
풀이 일자: 241020
풀이 시간: 1시간 30분
채점 결과: 정답
예상 문제 유형: 매개변수탐색, 완전탐색
시간: 952 ms
메모리: 52,208 kb

## 풀이방법
1. menuData : List<int[]> -> {매운맛 수치, 단맛수치} 매운맛 
2. 매운맛 수치를 기준으로 정렬 (comparator)
3. 매운맛 lowerBound와 upperBound 찾기
4. 범위 내에서 단맛 수치를 만족하는지 검증 후 count++

## 어려웠던 점
완전탐색으로 풀려서 당황함 근데 너무 느려서 매개변수 탐색을 시도함
탐색 할 변수가 여러개라 당황함, 근데 완전탐색으로 풀리는 사실을 감안하여
이진탐색을 통해 lowerBound와 upperBound 로 매운맛 범위를 좁혀 시간을 줄임

**Comment by kimdevspace** [comment]
### 풀이사항
풀이 일자: 2401022
풀이 시간: 48분
채점 결과: 정답
예상 문제 유형: 이분탐색
시간: 948ms
메모리: 52,220kb
### 풀이방법
1. 리스트에 맛들을 넣어서 매운맛 기준으로 정렬
2. 매운맛의 LowerBound와 UpperBound를 찾음
3. 위의 범위 내에 단맛이 범위 내에 있는지 (둘 다 만족하는지) 찾고 cnt++
### 어려웠던 점
상호 완탐으로 풀렸나??..?? 시간초과 5,000 * 100,000 날텐데 ㄷㄷㄷ
완탐으로 하다가 안풀려서 이분탐색함

**Comment by kro46** [comment]
## 문제링크
#386 

## 풀이사항
풀이 일자: 2401022
풀이 시간: 1시간 12분
채점 결과: 정답
예상 문제 유형: 이분탐색
시간: 836ms
메모리: 53,436kb

## 풀이방법
1. 리스트에 맛들을 넣어서 매운맛 기준으로 정렬
2. 매운맛의 LowerBound와 UpperBound를 찾음
3. 위의 범위 내에 단맛이 범위 내에 있는지 (둘 다 만족하는지) 찾고 cnt++

## 어려웠던 점
완탐으로 풀리긴했는데 너무 오래걸려서 힌트 얻어서 이분 탐색으로 다시 풀었음.  
어떤 부분에서 이분탐색을 적용해야할지 아이디어가 아직 잘 안떠올라서 익숙해지려면 비슷한 문제를 여러 번 풀어보는 것이 답이라는 결론을 내림

**Comment by reasonyi** [comment]
## 문제링크
#387 

## 풀이사항
풀이 일자: 2401022
풀이 시간: 1시간 20분
채점 결과: 정답
예상 문제 유형: 이분탐색
시간: 892 ms
메모리: 53,980 kb

## 풀이방법
1. 리스트에 맛들을 넣어서 매운맛 기준으로 정렬
2. 매운맛의 LowerBound와 UpperBound를 찾음
3. 위의 범위 내에 단맛이 범위 내에 있는지 찾아 cnt++ 후 StringBuilder에 더해 나중에 한번에 출력

## 어려웠던 점
1. 처음에는 List에 넣어서 매운맛 순서대로 정렬 후 범위를 찾고, 그 범위만큼 subList하여 다시 정렬 한 뒤  단맛 범위를 찾으려 하였다. 하지만 sort를 계속 호출하는 것에 많은 시간이 들어감... 그래서 시간초과 났다.
2. 1번에서 그럼 처음에 매운맛 기준 정렬하고 subList하지말고(subList는 얕은 복사라 기존 배열의 정렬이 바뀐다.) 깊은 복사를 하면 어떨까? 싶었지만 subList할 배열의 크기도 최대 10만개이기 때문에... 1번 방법보다는 좀 더 퍼센트가 올라갔지만 결국 시간초과 났다.
3. 완탐으로 냅다 했는데 풀렸다. 근데 2456ms 나왔다. 이거 내생각엔 완탐으로 풀리면 안되는 문제같은데..? 하고 다시 시도했다
4. lowerBound upperBound 개념을 모르고 그냥 바이너리서치 메서드 안에서 한번에 찾는 걸로 했는데 이게 lowerBound upperBound인 것 같다. 그런데 정답 코드를 보니까 약 60ms정도 차이나는데... 뭐때문에 내 코드가 느린건지 모르겠다...ㅠㅠ

**Comment by chanu2** [comment]
## 문제링크
#394 

## 풀이사항
풀이 일자: 241022
풀이 시간: 1시간 30분
채점 결과: 정답
예상 문제 유형: 이분탐색
시간: 888 ms
메모리: 52332 kb

## 풀이방법
1. 음식들을 지수를 2차원 배열로 저장하고 매운맛 기준으로 정렬 
2.  low , upper bound로 매운맛이 가능한 범위를 찾고 단맛을 비교해서 개수를 count한다. 

어떤것을 이분 탐색할지 조금 오래 걸렸다.

**Comment by haesoooo** [comment]
## 문제링크
#395

## 풀이사항
풀이 일자: 241022
풀이 시간: 1시간
채점 결과: 정답
예상 문제 유형: 이분탐색
시간: 920 ms
메모리: 52300 kb

## 풀이방법
1. 각 날짜마다의 매운맛 단맛 limit을 담을 date 배열 (limit 클래스)
2. 각 메뉴마다의 매운맛 단맛을 담을 menu 배열 (flavor 클래스 -> 매운맛 기준 정렬 compareTo 구현)
3.  low , upper bound로 매운맛이 가능한 범위를 찾고 단맛을 비교해서 개수를 count한다. 

## 어려웠던 점
처음에 매운맛 기준 upper 비교 -> 매운맛 기준 lower 비교 -> 단맛 기준 upper 비교 -> 단맛 기준 lower 비교해서 시간 초과났다. 단맛은 단순 if문으로 카운트 해도 된다는걸 깨닫기까지 시간이 오래걸렸다.
