### ISSUE TITLE
[BOJ] 구슬 탈출

### ISSUE THREAD

**Issue by sangholee235** [SSAFY12th/ssafyAlgostudy#381]
문제 링크
https://www.acmicpc.net/problem/13459

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by sangholee235** [comment]
## 문제링크
#379

## 풀이사항
풀이 일자: 241020
풀이 시간: 40분
채점 결과: 정답
예상 문제 유형: 구현
시간: 104 ms
메모리: 14,300 kb

## 풀이방법
1. BFS를 통해 구슬을 위치를 추적하여 탐색
2. 4차원 배열을 통해 방문 여부 체크 visited[빨강x][빨강y][파랑x][파랑y]
3. 벽에 부딪히거나 구멍에 빠질때까지 위치 이동
4. 10번 넘게 움직이면 return 0; (실패), 파란구슬이 구멍에 빠지면 실패
5. 빨간 구슬이 구멍에 빠지면 성공
6. 두 구슬이 같은 위치에 있으면 더 많이 움직인 구슬을 한 칸 뒤로 이동시킴

## 어려웠던 점
구슬 두개의 위치를 추적 해야하는 부분에 대한 아이디어를 떠올리는게 쉽지 않았음
구슬을 굴리는 전략이 있어야하는줄 알았는데 BFS를 떠올리는데 좀 걸렸음

**Comment by reasonyi** [comment]
## 문제링크
BFS - #382 
BFS - #383

## 풀이사항
풀이 일자: 241021
풀이 시간: 처음 DFS 2시간, BFS 1시간 30분
채점 결과: 정답
예상 문제 유형: 구현/완전탐색/최단거리?
시간: 
  DFS - 2536 ms
  BFS - 192 ms
메모리: 
  DFS - 309,564 kb
  BFS - 32,240 kb

## 풀이방법
DFS로 풀때...  
공이 움직였을 때마다 배열 및 공의 위치를 복사하여 상하좌우로 모두 움직여보고 dfs를 호출한다.
dfs 호출이 끝나면 각 배열 및 공의 위치를 원상복구한다.

BFS로 풀 때...
공의 위치만 가지고 이동.
공이 상하좌우로 이동할 수 있는 만큼 이동한다.
만약 두 공의 위치가 겹치면 한 칸 조정한다.
빨간 공만 구멍에 들어가는 경우 최단경로라 바로 bfs를 종료한다.

## 어려웠던 점
맵가지고 하는 구현 문제에 매우 약한 것 같다.... dfs로 처음에 겨우 풀었지만 시간 초과가 여러 번 났었다.
bfs로 다시 풀어보았지만 풀었던걸 다시 푸는건데도 너무 오래 걸린 것 같다.
그마저도 시간이 엄청 빠른것도 아니고 메모리가 작은것도 아니고
어떻게 해야 잘 할 수 있을까?

**Comment by chanu2** [comment]
## 문제링크
#392 

## 풀이사항
풀이 일자: 241020
풀이 시간: 2시간 10분
채점 결과: 정답
예상 문제 유형: 구현
시간: 2424ms 
메모리: 327212kb
## 풀이방법
1. 맵 크기가 구슬을 굴리는 횟수 10번 이고 방향이 4개라 순열로 방향을 뽑는다.
2. 구슬이 움직이는 방향을 기준으로 자신의 앞에 공이 있다면 앞에 있는 공을 먼저 이동시키고 뒤에 있는 공을 이동시킨다.
3. 10번안에 R이 들어가고 B가 들어가지 않았다면 1을 return 
## 어려웠던 점
BFS를 사용하지 않고 구현해서 시간도 많이 걸리고 코드가 너무 더럽습니다. BFS 적용해 보겠습니다

**Comment by kro46** [comment]
## 문제링크
#397 
## 풀이사항
풀이 일자: 241023
풀이 시간: 이틀
채점 결과: 정답
예상 문제 유형: DFS/BFS + 시뮬레이션
시간: 104ms
메모리: 14,344kb

## 풀이방법
1. 처음 맵을 입력받을 때, 빨간 공과 파란 공의 위치를 미리 저장해두고 공의 자리는 '.'으로 바꿔줌, 구멍자리는 '1'로 바꿈.
2. BFS를 돌면서 두 공의 위치를 동시에 이동시킴
3. 4방향 탐색을 하며 빨간 공과 파란 공이 구멍에 들어갔는지 확인하며 return할지 continue할지 판단
4. 파란 공에 대한 검사를 먼저 함.(파란 공이 구멍에 들어가면 continue -> 실패한 경우)
5. 그 후, 빨간 공에 대한 검사 수행(빨간 공이 구멍에 들어가면 return true -> 성공한 경우)
6. 실패한 경우 다음 조건에 대한 검사 
7. 두 공이 겹치는 경우 방향에 따라 늦게 도착한 공의 위치를 한칸씩 뒤로 조정해줌
8. 4차원 visited배열을 활용하여 빨간 공과 파란 공의 방문여부를 체크
9. BFS가 끝난 후, 공의 이동 횟수가 10이 되면 0을 return

## 어려웠던 점
처음에 DFS로 접근했다가 24%에서 계속 틀리고 벽느껴서 BFS로 방향을 전환함. 이 문제는 어렵게 생각하면 한도끝도없이 어려워짐. 1~2시간 트라이해보다가 어려우면 힌트를 보는걸 추천함.. (나는 기어코 이틀을 박아서 실패함..)
문제를 풀고도 다시 풀려고보니까 어려워서 내일 한 번 더 풀어볼 예정 -> 이 문제 30분안에 완벽하게 풀 수 있으면 이제 맵을 사용하는 구현문제는 걱정 없을 듯

**Comment by kimdevspace** [comment]
### 문제링크
#403 
### 풀이사항
풀이일자: 241024
풀이시간: 3시간 트라이 후 답지참고
채점결과: 정답
예상문제유형: 시뮬레이션
시간: 108ms
메모리: 14,368kb
### 풀이방법
1. 빨간구슬과 파란구슬의 정보와 이동횟수를 담는 클래스 생성
2. 위치 찾아서 q에 넣어주기.
3. 이동을 한칸씩이 아니라 한번에 해주어야함. 이동할 수 있는 위치 찾아서 다시 큐에 넣어주기
  - 벽이나 구멍이아닐 때까지 이동( 이동해야 할 칸수를 누산해서 정해주는것임)      
     - 만약 이동했는데 파란 구슬이 구멍에 빠지면 실패
     - 빨간 구슬만 빠지면 return

4. 구슬 겹친거 처리 (더 많이 이동한 구슬을 뒤로 한칸 이동시킴)
### 어려웠던점
dfs로 풀다가 디버깅도 안되고 시간초과 남.
처리해줄 조건이 너무 많았음
어렵다
강사님한테 물어봄
답지도봄
그래도 어렵다
a형에 이런거 나오면 gg
