### ISSUE TITLE
[BaekJoon] N과 M

### ISSUE THREAD

**Issue by chanu2** [SSAFY12th/ssafyAlgostudy#4]
### 문제 링크
https://www.acmicpc.net/problem/15663

### 풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

### 풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by chanu2** [comment]
### 문제 링크
#5 

### 풀이 사항
풀이 일자: 2024.07.18
풀이 시간: 30분
채점 결과: 정답
예상 문제 유형: 백트레킹

### 풀이 방법
- 리스트를 받아 정렬한다.
- 중복된 수열을 제거 하기위해 이전에 만들어진 수열의 마지막 수를 변수에 담아두어 확인한다.
- 재귀를 통해 결과를 도출한다.

**Comment by reasonyi** [comment]
### 문제 링크
#8 

### 풀이 사항
풀이 일자: 2024.07.19
풀이 시간: 50분
채점 결과: 정답
예상 문제 유형: 백트레킹

### 풀이 방법
- N, M값과 수의 리스트를 받고, 리스트는 오름차순으로 정렬한다.
- 이미 방문했거나 || 현재값과 이전값이 같고 && 이전값을 사용하지 않은 경우 continue하여 다음 반복으로 넘긴다.
- 재귀 호출을 통해 결과를 도출한다.

**Comment by kimdevspace** [comment]
### 문제 링크
#9 
### 풀이 사항
풀이 일자 : 2024.07.21
풀이 시간 : 1시간 30분
채점 결과 : 정답
예상 문제 유형 : 백트래킹

### 풀이 방법
- 입력 받은 배열을 오름차순으로 정렬하기
- 중복이 되지 않게 방문리스트 활용하여 방문체크!
- 똑같은 수열이 나오지 않게 변수(past)에 마지막 수를 담아주고 같은 깊이(depth)에서 past가 배열arr의 다음 수와 같으면 무시함으로 해결하기!

**Comment by kro46** [comment]
## 문제 링크
#11

## 풀이 사항
풀이 일자 : 2024.07.21
풀이 시간 : 1시간 30분
채점 결과 : 정답
예상 문제 유형 : 백트래킹

## 풀이 방법
- 입력 받은 배열을 오름차순으로 정렬하기
- 중복이 되지 않게 방문리스트(selected) 활용하여 방문체크
- (현재 선택 수 == 이전 선택 수 && 이전 수 선택하지 않은 상태) 이면 continue

**Comment by haesoooo** [comment]
### 문제 링크
#13 

### 풀이 사항
풀이 일자: 2024.07.22
풀이 시간: 40분
채점 결과: 정답
예상 문제 유형: 백트래킹

### 풀이 방법
- 입력 데이터 (배열)을 오름차순 정렬
- visited[] 배열 이용, 방문 체크
- 중복 수열을 제거하기 위해 temp 변수에 이전 수열 값을 저장
- C++ 이나 파이썬이라면 permutation 라이브러리를 활용하자!

**Comment by JuHeeKim-joy** [comment]
### 문제 링크

#18

### 풀이 사항

풀이 일자 : 2024.07.23.
풀이 시간 : 2시간
채점 결과 : 정답
예상 문제 유형 : 백트랙킹

### 풀이 방법

- visited 배열로 각 숫자가 이미 사용되었는지 추적
- LinkedHashSet 사용하여 조합 저장하고 중복 제거
- 재귀 호출로 깊이 증가시키며 조합 생성

+) 백트랙킹 문제 다시 풀어보기

**Comment by chanu2** [comment]
close

**Comment by chanu2** [comment]
close
