### ISSUE TITLE
[BOJ] 파티

### ISSUE THREAD

**Issue by reasonyi** [SSAFY12th/ssafyAlgostudy#408]
문제 링크
https://www.acmicpc.net/problem/1238

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by reasonyi** [comment]
### 문제링크
#407 
### 풀이사항
풀이일자: 241025
풀이시간: 28분
채점결과: 정답
예상문제유형: 다익스트라
시간: 468ms
메모리: 68,492kb
### 풀이방법
- 각 학생의 마을마다 X까지 얼마나 걸리는지 다익스트라로 구하여 학생별 시간 배열에 저장한다.
- X에서부터 각 마을로 가는데 얼마나 걸리는지 다익스트라로 구하여 학생별 시간 배열에 더한다.
- 배열을 정렬한 후 가장 마지막 값을 출력한다.
### 주의할 점
다익스트라를 여러 번 쓰는 경우 배열 초기화에 주의할 것

**Comment by kimdevspace** [comment]
# 문제링크
#413 
# 풀이사항
풀이일자: 241029
풀이시간: 28분
채점결과: 정답
예상문제유형: 다익스트라
시간: 552ms
메모리: 68,724kb
# 풀이방법
1. X에서 갈 수 있는 모든 정점의 최단거리를 구한다.
2. 모든 정점에서 X로 갈 수 있는 최단거리를 구한다
3. 최댓값 구하기

# 어려웠던 점
다익스트라 까먹어서 다시 공부했습니다. . . . . . . ..  . . . .. . . .  . . . .
다익스트라 순서
1. 방문배열 초기화
2. dist배열 max로 초기화
3. 시작dist = 0
4. pq 가중치 오름차순후 다익스트라 시작!
5. 연결되어있는 모든 노드들에 대해 dist[연결노드] > dist[현재노드] + 연결노드가중치 라면?  dist[연결노드] > dist[현재노드] = 연결가중치, pq 에 연결된 노드와 다음 연결된노드가중치를 넣어줌

**Comment by sangholee235** [comment]
### 문제링크
#407 

### 풀이사항
풀이일자: 241025
풀이시간: 15분
채점결과: 정답
예상문제유형: 다익스트라
시간: 680 ms
메모리: 84,408 kb
### 풀이방법
1. 정점 -> 파티장소 + 파티장소 -> 정점 다익스트라 2번 계산 후 더하기
2. 최대 도달 거리와 비교 후 갱신
### 느낀 점
더 나은 방법이 있지 않을까 고민을 해봤는데 못 떠올렸다.

**Comment by kro46** [comment]
## 문제링크
#423 

## 풀이사항
풀이일자: 241030
풀이시간: 45분
채점결과: 정답
예상문제유형: 다익스트라
시간: 572ms
메모리: 85,200kb

## 풀이방법
1. 최단거리 배열을 선언
2. 각 학생들이 파티장소로 가는 최단거리 + 집으로 돌아오는 최단거리를 다익스트라로 구해서 최단거리 배열에 저장
3. 최단거리 배열을 정렬해서 마지막 인덱스의 값을 출력(가장 오래 걸린 학생의 최단거리)
## 주의할 점
인접행렬로 해봤는데 시간초과나서 인접리스트로 변경했음. 앞으로 다익스트라 관련문제 나오면 무조건 인접리스트로 푸는걸로...

**Comment by chanu2** [comment]
김찬우 / 241030 / [BOJ_파티_1238] / 676 ms / 72560 kb

## 문제링크
#426 

## 풀이사항
풀이일자: 241030
풀이시간: 30분
채점결과: 정답
예상문제유형: 다익스트라
시간: 676ms
메모리: 72560kb

## 풀이방법
1.  1~ n 번까지 돌면서
2.  start -> end 로 다익스트라 진행
3.  end -> start 로 다익스트라 진행
4. 두개 합을 구해서 최댓값 출력
## 주의할 점

**Comment by haesoooo** [comment]
## 문제링크
#418

## 풀이사항
풀이일자: 241030
풀이시간: 50분
채점결과: 정답
예상문제유형: 다익스트라
시간: 192ms
메모리: 19268kb

## 풀이방법
1.  모든 단방향 길들을 저장하고 반대인 방향의 배열도 저장하자
2. 타겟 집까지 가는 최단거리 다익스트라 한번 돌리기
3. 그 다음에 반대로 가는 다익스트라 한번 돌리기

총 2번 돌리면 된다. 처음에는 하나의 벡터로, 모든 지점에서 X로 가는 다익스트라 (N-1번 실행) -> 이후 X에서 다른 지점으로 가는 다익스트라 1번 실행 = 4% 시간초과
