### ISSUE TITLE
[BOJ] 마법사 상어와 파이어볼

### ISSUE THREAD

**Issue by chanu2** [SSAFY12th/ssafyAlgostudy#414]
문제 링크
https://www.acmicpc.net/problem/20056

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by chanu2** [comment]
### 문제링크
#407 
### 풀이사항
풀이일자: 241029
풀이시간: 2시간 30분
채점결과: 정답
예상문제유형: 구현
시간: 376ms 
메모리: 37500kb
### 풀이방법
- k만큼 돌린다.
- queue에 파이어볼을 int[]로 넣고 queue size 만큼 poll을 하고 이동시킨다. 
- 이때 1번 행은 N번과 연결되어 있고, 1번 열은 N번 열과 연결 되기 때문에 나머지 연산을 통해서 파이어볼 위치를 바꾸어 Result 클래스(질량합, 속도합, 개수, 방향)에 Result[][] visited에 저장한다. 이때 null이면 Result를 새로 생성하고 null이 아니면 기존 값들을 더해주고 방향을 check 해준다.
- visited를 모두 돌면서 null이 아니고 개수가 2개 이상일때 방향을 확인하고 방향에 따라 0,2,4,6 이나 1,3,5,7 돌면서  값을 갱신하여 queue에 삽입한다.
- k번이 지나고 queue에 나머지 값들을 빼서 질량을 더해서 결과를 출력한다.
### 주의할 점
파이어볼이 여러개 만났을 때 속력과 방향으로 바로 각각 파이어볼을 이동시켜서 결과가 이상하게 나왔다. (문제를 잘 읽고 해석하는데 더 신경을 써야할 것 같다 1시간 30분 동안 삽질했습니다. )	


김찬우 / 241029 / BOJ_마법사 파이어볼_20056 / 376ms / 37500kb

**Comment by reasonyi** [comment]
### 문제링크
#416 

### 풀이사항
풀이일자: 241030
풀이시간: 1시간 30
채점결과: 정답
예상문제유형: 구현
시간: 648ms
메모리: 112,592 kb

### 풀이방법
추후 수정 예정...

**Comment by kimdevspace** [comment]
### 문제링크
#420 
### 풀이사항
풀이일자: 2401030
풀이시간: 3시간
채점결과: 정답
예상문제유형: 구현
시간: 920ms
메모리: 213,068kb

### 풀이방법
1. 파이어볼 이동
2. 같은 칸에 파이어볼이 여러개라면 합친 후 분열

파이어볼 클래스를 하나 만들고
2차원 배열에 파이어볼이 들어갈 수 있는 리스트를 만들었습니다.

### 어려웠던 점
처음엔 맵이 이어져 있다는 점을 이해를 못해서 해맸습니다.
그리고 원래 맵에서 tmpMap으로 분열을 시키고 복사를 하는 과정에서 자꾸 뭐가 하나 안돼서 해맸습니다.
그리고 마지막으로 방향 설정 잘못해줘서 마지막 테케만 안풀림. 7을 -1,-1로 해야하는데 -1,1로 하고 풀고 있었음 -.-

**Comment by sangholee235** [comment]
### 문제링크
#411
### 풀이사항
풀이일자: 241028
풀이시간: 1시간
채점결과: 정답
예상문제유형: 구현
시간: 596 ms 
메모리: 136,412 kb

### 풀이방법
1. ArrayList형 2차원 배열을 만든다
2. 파이어볼을 방향과 속도에 따라 이동 시킨 뒤 좌표에 저장한다.
3. 2개 이상의 파이어볼이 쌓인 좌표에서 조건에 맞게 분기를 진행한다.
4. 전체 맵의 총 질량을 계산한다.

### 복기
기존에 비슷한 문제를 풀때는 겹치는 경우가 2개인 경우여서 그냥 Class형 2차원 배열로 풀었다.
근데 이번 문제의 경우는 여러개가 쌓일 수 있으므로 해당 방법으로는 불가능했다.
ArrayList형 이차원 배열로 여러개의 클래스를 쌓는 방법으로 해결 했다.

**Comment by kro46** [comment]
## 문제링크
#440 

## 풀이사항
풀이일자: 241031
풀이시간: 3시간 35분
채점결과: 정답
예상문제유형: 구현
시간: 1,608ms
메모리: 25,400kb

## 풀이방법
1. 파이어볼의 정보를 입력받고 K번 돌린다.
2. map에 파이어볼이 존재하는 곳을 +1 해주어 같은 위치의 파이어볼이 몇 개인지 기록
3. map을 읽으면서 해당 위치에 파이어볼이 2개 이상인 좌표를 positions 리스트에 담음
4.  파이어볼 합침(현재 맵에 있는 파이어볼들의 질량과 속도를 모두 더하고 방향을 체크)
5. 합쳐진 파이어볼을 나누는데 방향에 따라 모두 짝수거나 홀수면 0,2,4,6 방향을 주고 아니면 1,3,5,7로 방향을 줌
6. 분리된 파이어볼을 모두 파이어볼 리스트에 저장 
7. 2~6번 과정을 K번 한 후에 현재 맵에 남아있는 파이어볼들의 질량을 모두 더해서 출력 

## 주의할 점
파이어볼을 움직일 때 dr[d] * s 만큼 한번에 움직이면 dr값이 음수 일 때 맵을 벗어나는 IndexOutOfRange 오류가 발생함. 그래서 s를 곱하기전에 N * 1001을 먼저 더해주고 나중에 %N 계산을 해서 맵의 범위를 벗어나지 않게 해줘야함. <- 아마 이것때문에 안된 경우들이 꽤 많을거임.

**Comment by haesoooo** [comment]
## 문제링크
#433

## 풀이사항
풀이일자: 241031
풀이시간: 오늘 하루종일함
채점결과: 실패
예상문제유형: 구현, 시뮬레이션

## 풀이방법
1. 파이어볼 정보를 받아서
2. 이차원 큐 배열을 만들었는데.. 그 큐 배열에 볼을 옮기는 방식으로 했다.
3. 처음에는 볼 배열을 만들어서 각 볼에 대한 인덱스만 큐에 저장하는 방식으로 했는데
4. 뭐가 마니 꼬여서.. 테케만 맞고 인덱스 오류가 나는데 차마 고치기가 힘들엇다..
