### ISSUE TITLE
[BOJ] ACM Craft

### ISSUE THREAD

**Issue by sangholee235** [SSAFY12th/ssafyAlgostudy#421]
문제 링크
https://www.acmicpc.net/problem/1005

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by sangholee235** [comment]
### 문제링크
#409
### 풀이사항
풀이일자: 241028
풀이시간: 1시간
채점결과: 정답
예상문제유형: 위상정렬, 그래프
시간: 880 ms 
메모리: 242,756 kb

### 풀이방법
1. 그래프를 입력 받을때, 진입차수를 입력받는다.
2. 진입 차수가 0인 건물을 큐에 추가한다.
3. 큐에서 하나의 정점을 뺀 뒤 이웃한 정점을 탐색한다.
4. 이웃한 정점의 진입차수를 뺀다.
5. 다음 정점에 닿는 시간 vs 현재 정점까지의 시간 + 다음 정점의 진행시간 중에 짧은것을 선택한다.
6. 진입 차수가 0이면 큐에 추가한다.
 
### 복기
위상정렬의 개념에 대해 알게되었다. 기존 그래프 알고리즘과 비슷한 부분이 많은 것 같다.
이걸 공부 했더라면.

**Comment by kro46** [comment]
## 문제링크
#424 

## 풀이사항
풀이일자: 241029
풀이시간: 1시간 5분
채점결과: 정답
예상문제유형: 위상정렬, 그래프
시간: 888 ms
메모리: 240,920 kb

## 풀이방법
1. 모든 건물 간의 건설 순서를 graph에 저장
2. 각 건물의 건설 비용을 Time배열에 저장
3. 각 건물 별 최대 건설 비용을 구하기 위해 times배열을 하나 더 선언
4. 진입 차수를 입력 받아 comeCnt 배열에 저장
5. 진입 차수가 0인 정점을 우선순위 큐에 넣음
6. 큐에 들어온 정점과 연결된 정점들의 진입 차수를 하나씩 빼주고 times배열 값을 이전까지 건설에 들었던 비용 + 현재 건물의 건설 비용으로 갱신
7. 진입 차수가 0이 된 정점이 있다면 큐에 다시 삽입
8. 모든 정점을 지나서 반복이 끝나면 W 번째 건물의 최대 비용을 출력

## 어려웠던 점
위상정렬 알고리즘에 대해 잘 몰라서 코드 구현부터 막막했다. 그래서 관련 자료들을 찾아보고 최대한 이해한 것들 바탕으로 고쳐가며 코드를 구현해나갔다. 한 번 이해하고 나면 구현하는 것은 어렵지 않은 것 같다.

**Comment by reasonyi** [comment]
### 문제링크
#425 

### 풀이사항
풀이일자: 241030
풀이시간: 27분
채점결과: 정답
예상문제유형: 위상정렬, 그래프, 다이나믹 프로그래밍
시간: 768 ms 
메모리: 240,960 kb

### 풀이방법
1. 각 건물 별 짓는데 걸리는 시간을 time배열에 저장
2. 간선을 입력받을 때, List에는 from-to로 이어지도록 추가하고, count에는 각 노드별 in의 개수를 저장한다.
3. **위상정렬**
 1. 처음에 in이 없는 건물만 큐에 추가한다. 
 2. dp배열에 처음 시작하는 건물 건설이 완료되는데 걸리는 시간을 저장한다.
 3. 큐에서 하나씩 꺼내면서, 이어지는 최대 건물 건설 시간을 갱신한다.
 4. 만약 선수 건물을 모두 지었다면, 큐에 새롭게 추가한다. (이때 자기 자신을 짓는 시간을 함께 추가한다.)
 5. 만약 목표 건물을 지었다면 위상정렬을 더 진행하지 않고 종료한다.

**Comment by kimdevspace** [comment]
### 문제링크
#430 
### 풀이사항
풀이일자: 241031
풀이시간: 1시간5분
채점결과: 정답
예상문제유형: 위상정렬, DP
시간: 916ms
메모리: 240,532kb

### 풀이방법
---- 위상정렬로직 ----
1. 그래프의 각 노드들의 진입차수 테이블 구성하기
2. 진입차수가 0인 노드들 Queue에 넣기
3. 큐에서 노드를 꺼낸 후 꺼낸 노드와 연결된 노드들의 진입차수 감소
4. 진입차수가 0이 되면 Queue에 넣기
5.  3~4를 Queue가 빌 때까지 반복

3~ 4 중간 과정에 동적계획법을 이용하여 최대 건물 건설 시간을 갱신해준다
dp[연결된노드] = max(dp[연결된노드], dp[현재노드] + buildTime[연결된노드]) 후 dp[W] 출력

### 어려웠던 점
위상정렬의 개념을 다시 한번 공부했고 순서가 정해질 때 건물의 건설시간을 갱신하는 동적계획법을 어느 분기에 넣어야 되는지 고민이 많이 되었습니다요

**Comment by chanu2** [comment]
### 문제링크
#432 
### 풀이사항
풀이일자: 241031
풀이시간: 2시간
채점결과: 정답
예상문제유형: 위상정렬, 그래프
시간: 1028ms 
메모리: 239120 kb

### 풀이방법
1. 인접 리스트를 만든다.
2. 처음 진입 차수가 0인 노드를 넣고 그때 걸리는 시간을 함께 넣는다. 
3. 큐에서 하나의 정점을 뺀 뒤 이웃한 정점들을 확인하고 진입 차수를 줄여준다.
4.  (기존 노드의 걸린 시간 + 이웃 한 정점의 시간) 과 이동한 결과 배열의 최대값을 결과 배열에 저장 
5. 진입 차수가 0이면 큐에 저장한다
 
### 복기
위상정렬의 개념은 어느정도 숙지 했지만 약간 dp 스러운? 어느 분기에 처리해야하는지 어려웠습니다.

**Comment by haesoooo** [comment]
### 문제링크
#429
### 풀이사항
풀이일자: 241031
풀이시간: 1시간
채점결과: 정답
예상문제유형: 위상정렬, 그래프
시간: 896ms 
메모리: 246120 kb

### 풀이방법
1. cost, result 배열을 만든다
2. 진입차수가 0인 애들을 찾는다
3. 이 때 W번째 친구는 무시하기
4. 위상정렬대로 풀면서 최댓값 갱신하기
 
### 복기
위상정렬의 개념은 어느정도 숙지 했지만 약간 dp 스러운? 어느 분기에 처리해야하는지 어려웠습니다.
