### ISSUE TITLE
[BOJ] 문자열 폭발

### ISSUE THREAD

**Issue by sangholee235** [SSAFY12th/ssafyAlgostudy#422]
문제 링크
https://www.acmicpc.net/problem/9935

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by sangholee235** [comment]
### 문제링크
#410
### 풀이사항
풀이일자: 241025
풀이시간: 30분
채점결과: 정답
예상문제유형: 자료구조, 스택
시간: 416 ms 
메모리: 35,756 kb

### 풀이방법
1. 입력 문자열과 폭탄 문자열을 입력받는다
2. 폭탄 문자열의 길이를 저장해둔다.
3. 스택에 입력 문자열을 하나씩 쌓는다
4. 스택의 길이가 폭탄 문자열 길이가 되면 한글자씩 비교한다.
5. 한글자라도 다르면 false 처리한다.
6. 폭탄일 경우 지금까지 쌓인 스택에서 폭탄 사이즈 만큼 뺀다.
7. 스택에서 한글자씩 빼서 결과를 StringBuilder에 저장한다.
8. 결과의 길이가 0인 경우 FRULA 아닌 경우 결과를 출력한다.
 
### 복기
자바로 문자열을 다루는 것은 익숙치 않다.
스택을 다루는 것 또한 익숙치 않다.
많이 다뤄봐야겠다 !

**Comment by kro46** [comment]
## 문제링크
#428  

## 풀이사항
풀이일자: 241031
풀이시간: 1시간 50분
채점결과: 정답
예상문제유형: 문자열 패턴 매칭/ 스택
시간: 352 ms
메모리: 37,044 kb

## 풀이방법
1. original 문자열과 trigger 문자열을 입력받는다
2. 각 문자열의 길이를 저장해둔다.
3. StringBuilder sb에 원본 문자열을 한 문자씩 넣는다.
4. 만약 가장 최근에 들어온 문자가 trigger 문자열의 마지막 문자와 일치하면 검사를 시작한다
5. sb의 길이에서 폭탄 문자열의 길이만큼 뺀 인덱스부터 sb의 길이까지 subString으로 묶어서 trigger문자열과 비교한다 
6. 만약 일치하면 sb에서 해당 부분을 제거한다.
7. 3~6의 과정을 original 문자열을 모두 입력받는 동안 반복한다.
8. 반복이 끝난 후 sb에 남은 문자열이 공백이면 FRULA를, 아니면 결과를 출력한다.

## 어려웠던 점
문자열 관련 메서드들이 자주 쓰지않으면 까먹기 때문에 쓰기가 어려웠다. 그리고 생각보다 index오류가 자주 발생해서 실제 시험에서 같은 문제를 접하면 당황할 것 같다. 이 문제는 가능하면 스택을 이용하는게 좋아보인다. 끝!

**Comment by reasonyi** [comment]
### 문제링크
#427 

### 풀이사항
풀이일자: 241031
풀이시간: 51분
채점결과: 정답
예상문제유형: 스택 
시간: 508 ms 
메모리: 57,600 kb

### 풀이방법
1. 입력 문자열과 폭탄 문자열을 입력받는다.
2. 제공된 문자열을 하나씩 탐색하여 head 또는 tail 중 알맞은 곳에 추가한다.
3. 추가된 문자열 길이만큼 cnt++한다.
4. 만약 cnt가 폭탄문자열 크기를 넘거나 같다면 뒤에서부터 한글자씩 비교하여 폭탄이 있는지 없는지 확인한다.
5. 폭탄 확인에 pivot을 활용한다.
6. 만약 폭탄이면 pivot의 next를 null로 변경(boom만큼 제거)
7. head와 tail을 경우에 맞춰 pivot 위치로 조정한다.
8. 출력 시 head부터 시작하여 연결리스트를 따라 StringBuilder에 추가한다.
9. 결과의 길이가 0인 경우 FRULA 아닌 경우 결과를 출력한다.

### 어려웠던 점
처음에 Deque활용해서 했었는데, 시간이  길게나와서... 상호오빠의 코드를 참고해서 LinkedList를 구현했다.
하지만 그래도 상호오빠 코드보다 느리다....

그래도 오랜만에 LinkedList 구조를 직접 구현해볼 수 있어 좋은 공부가 되었습니다


자바로 문자열을 다루는 것은 익숙치 않다.
스택을 다루는 것 또한 익숙치 않다.
많이 다뤄봐야겠다 !

**Comment by kimdevspace** [comment]
### 문제링크

#431 

### 풀이사항

풀이일자: 241031
풀이시간: 40분
채점결과: 정답
예상문제유형: 구현??스택??
시간: 368ms
메모리: 82,424kb

### 풀이방법

stringbuilder에 입력받은 문자를 하나씩 입력하다가 빌더의 길이가 폭발문자열 길이가 되었을 때 builder의 끝부분 폭발문자열 길이만큼 검사하여 일치하면 sb.delete(startinedx, endindex)를 해준다!

### 어려웠던 점
문자열 어려움  스택으로 하려다가 스트링빌더를 썼읍니다.

**Comment by chanu2** [comment]
### 문제링크
#435 
### 풀이사항
풀이일자: 241030
풀이시간: 1시간 20분
채점결과: 정답
예상문제유형: 자료구조, 스택, String
시간: 428 ms 
메모리: 85032 kb

### 풀이방법
1. 입력 문자열과 폭탄 문자열을 입력받는다
3. StringBuilder에 문자를 쌓는다
4. StringBuilder에 길이가 폭탄 문자열 길이가 되면
5. subString으로 equals 비교로 문자열이 같은지 확인
6. 같다면 sb.length() - bombLen)를 통해서 문자열을 제거한다.
7. 아니면 추가
 
### 복기
stack애서 get하는 방식을 처음 봤습니다. 
그래서 stringBuilder로 문제를 다시 풀어봤습니다.
