### ISSUE TITLE
[BOJ] 낚시왕

### ISSUE THREAD

**Issue by chanu2** [SSAFY12th/ssafyAlgostudy#443]
문제 링크
https://www.acmicpc.net/problem/17143

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by chanu2** [comment]
### 문제링크
https://www.acmicpc.net/problem/17143

#445 
### 풀이사항
풀이일자: 2024.11.04
풀이시간:  2시간 10분
채점결과: 정답
예상 문제 유형:  구현
시간: 724ms
메모리: 84096KB

### 풀이방법
- 1(위) , 2(아래), 3(오른쪽), 4(왼쪽) 을 ->  0(위) , 2(아래), 1(오른쪽), 3(왼쪽)으로 바꾸고 시작 
- 상어가 여러명 모였을 때 확인하기 위한 Result 객체 생성 (속도, 방향, 크기)
- 열 만큼 돌면서 진행 시작 
- catchShark() 메서드를 통해서 상어를 잡는다.
- addShark() 메서드를 통해서 샤크를 queue에 넣어준다.
- queue.size 만큼 큐에서 빼고 상어들을 각각 이동시킨다. (나머지 연산을 통해서 상어가 반복적으로 움직이는 것을 최적화 )
- nx < 0 || nx >=n || ny < 0 || ny >=m  일 때 방향을 d = (d+2) % 4 바꿔준다.
- Result[][]에 값이 있다면 다른 상어도 있기 때문에 크기 비교를 통해서 가장큰 상어만 남긴다.
- m-1번 반복한다.

**Comment by kimdevspace** [comment]
### 문제링크
[#](https://github.com/SSAFY12th/ssafyAlgostudy/blob/main/EuiJoong/Week16/BOJ_%EB%82%9A%EC%8B%9C%EC%99%95_17143.java)

### 풀이사항
풀이일자: 241105
풀이시간: 4시간 넘게 고민한듯
채점결과: 정답
예상 문제 유형: 구현, 시뮬레이션
시간: 552ms
메모리: 134,284kb
### 풀이방법
- 마법사상어와 파이어볼 문제와 유사했기때문에 2차원 배열에 List<Shark>를 담을 수 있게 맵을 만들어줌.
- 낚시꾼이 이동하며 제일 가까운 물고기 낚시!
- 상어 이동을 tmpMap에 해줬음
- 상어가 한칸에 여러마리일 경우 제일 큰상어로 갱신

### 어려웠던 점
상어가 격자안에서 반복하는 로직에서 시간을 많이 쏟았는데 결국 이 로직을 아이디어를 다른사람꺼 얻어왔습니다. 아직 멀다ㅓ 멀어

**Comment by kro46** [comment]
## 문제링크
#453 

## 풀이사항
풀이일자: 241105
풀이시간: 3시간 30분
채점결과: 정답
예상 문제 유형: 구현, 시뮬레이션
시간: 660ms
메모리: 22,860kb

## 풀이방법
1. 상어의 정보를 담아줄 sharkList 배열 선언 <- 여기에 상어의 위치, 속도, 방향, 크기, 인덱스를 담아줬음
2. 순서 : 사람 이동(낚시) -> 상어 이동 -> 상어가 겹친 위치 탐색 -> 크기가 작은 상어 모두 죽임
3. 위 순서를 열 크기만큼 반복한다.
4. 상어 이동 시 시간초과를 피하기 위해 현재의 방향과 위치가 동일해지는 경우를 나머지 연산으로 제거해줌
5. 이후 남은 이동 횟수만큼만 이동 시켜줌
6. 상어가 겹친 위치를 찾는 방법으로 map 좌표에 각각 상어가 몇 마리 있는지를 상어 이동 로직에서 담아줌
7. 2마리 이상 있는 좌표들을 모두 리스트에 저장
8.  상어 리스트를 돌면서 이전 상어와 크기를 비교하여 가장 큰 상어만 남기고 나머지는 모두 죽임
9. 결과 출력

## 어려웠던 점
큰 상어만 남기고 나머지 다 죽이는 로직이 떠올리기 힘들었음. 처음엔 스택으로 해볼까 했는데 생각해보니 처음 상어를 지정하는거 외에는 굳이 스택을 써서 비교할 필요가 없어서 그냥 before 변수에 첫 상어를 담아서 비교를 수행함.
그리고 시간초과.... 파이어볼 문제때도 비슷하게 고비였던 구간인데 이부분은 그래도 경험이 있어서 그런지 떠올릴 수는 있었음. 근데 떠올리는데 꽤나 시간이 걸려서 이 부분도 익숙해지는게 답인듯 함

**Comment by sangholee235** [comment]
## 문제링크
#457

## 풀이사항
풀이일자: 2024.11.05
풀이시간: 1시간
채점결과: 정답
예상 문제 유형: 시뮬레이션
시간: 532 ms
메모리: 49,144 KB

## 풀이방법
1. 낚시왕을 열 이동한다.
2. 가장 가까운 상어를 잡는다.
3. 상어를 이동 시킨다.
3-1. speed를 모듈러 연산을 통해 너무 커지는 것을 방지 (이동 최적화)
3-2. 속력에 맞게 상어를 이동 시킨다.
3-3. 이동 후 같은 자리에 상어가 있으면 크기를 비교하고 덮어쓴다.
4. 반복한다.

## 복기
기존 풀이는 속도만큼 곧이 곧대로 돌려서 속도가 2초넘게 나왔는데 모듈러 연산을 통해 최적화하여
속도를 줄였다.

**Comment by kimjuheee** [comment]
### 문제링크
#

### 풀이사항
풀이일자: 2024.11.06
풀이시간: 2일
채점결과: 오답
예상 문제 유형: 구현
시간: -
메모리: -

### 풀이방법
- 방향 쉽게 바꾸기 위해서 상하좌우에서 상좌하우로 변경
- 낚시왕 이동해서 가장 가까운 상어 크기 정답 변수에 저장
- 새로운 위치가 빈 공간인지 이미 상어가 있는지 확인
- 이미 상어가 있다면 두 상어 크기 비교해서 기존 상어보다 현재 상어가 크다면 현재 상어 넣어주고
- 상어가 없다면 현재 상어 넣어줌

### 어려웠던 점
- 배열 초기화 해주는 처리 못해줘서 계속 오류 발생
- 상어의 방향이동 처리 해주는게 어려웠다. 벽에 부딪힐 때 방향 반대로 해주는 작업 (상하좌우 -> 상좌하우)
- 구현을 할 때 자세하게 설계를 하고 코드를 작성해야 구현을 하는데 막힘이 없다는 것을 알게 되었다.

**Comment by haesoooo** [comment]
### 문제링크
#462

### 풀이사항
풀이일자: 2024.11.06
풀이시간: 6시간 .. 이상
채점결과: 정답
예상 문제 유형: 구현


### 풀이방법
- 낚시왕이 오른쪽으로 이동
- 땅과 가장 가까운 상어부터 잡아간다 (1행부터~ R행)
- 상어를 잡고 결과에 더한다.
- 정해진 속력대로 상어를 이동시킨다.

### 어려웠던 점
- 이동 로직에 대한 수식을 설계하는데 진짜 3시간 이상 걸렸다.. 성태오빠가 힌트를 줘서 그제서야 했다. 진짜 어려웠다
