### ISSUE TITLE
 [BOJ] 방탈출

### ISSUE THREAD

**Issue by chanu2** [SSAFY12th/ssafyAlgostudy#446]
문제 링크
https://www.acmicpc.net/problem/23743

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by chanu2** [comment]
### 문제링크

#447 
### 풀이사항
풀이일자: 2024.11.04
풀이시간:  40분
채점결과: 정답
예상 문제 유형:  구현
시간: 1040 ms
메모리: 71980 kb

### 풀이방법
- 어차피  비상탈출구가 무조건 있어야 하기 때문에 비상 탈출구를 0이라는 정점으로 보고 진행한다.
- 비상 탈출 시간을 0에서 출발해서 i로 가고 시간이 t 걸리는 Node라고 생각하고 그대로 크루스칼을 진행한다.

**Comment by reasonyi** [comment]
## 문제링크
#459 

## 풀이사항
풀이일자: 241106
풀이시간: 33분
채점결과: 정답
예상문제유형: MST
시간: 608 ms
메모리: 68,392 kb

## 풀이방법
1. 간선을 저장할 Edge 클래스 구현.
  1-1. 간선 비용이 적은 순서대로 정렬될 수 있도록 compareTo를 구현한다.
2. 간선을 전부 입력받는다.
3. 탈출구를 건설하는 것을 0번 노드와 연결하는 것이라 생각하고 Edge를 생성하여 추가로 pq에 저장한다.
4. 크루스칼!

## 느낀점
처음에는 if문으로 계속 조건추가했는데 제출하자마자 자꾸 틀려서 생각을 이리저리 바꿔봤지만...
결국 0에 Edge로 잇는 부분을 참고했습니다

**Comment by kro46** [comment]
## 문제링크
#460 

## 풀이사항
풀이일자: 241106
풀이시간: 58분
채점결과: 정답
예상문제유형: MST
시간: 1128 ms
메모리: 73,008 kb

## 풀이방법
1. 0번 노드에 모두 연결하는 아이디어를 활용 (찬우야 고맙다!)
2. Edge 클래스 구현 -> 노드 정렬을 위해 Comparable을 Edge클래스에 구현 & 간선 저장용 EdgeList도 선언
3. M개의 간선을 입력받음, 그 후 다시 N개의 간선을 입력받음(이 때, 출발 노드는 i, 도착 노드는 0, 비용은 주어진 입력)
4. 간선리스트 정렬 후 크루스칼 수행(총 연결될 간선의 개수는 0번 노드까지 N개)
5. 결과 출력

## 어려웠던 점
처음에는 연결된 부분과 연결되지 않은 부분을 따로 나눠서 탈출구 비용을 더하는 방법을 생각했는데 그렇게 하면 무조건 시간초과각이라 찬우와 이야기해서 아이디어를 얻음
MST류는 보통 이런 유형인 것 같다. 이정도가 딱 시험장에서 풀기 괜찮은듯

**Comment by kimdevspace** [comment]
### 문제링크
#467 
### 풀이사항
풀이일자: 240017
풀이시간: 40분
채점결과: 정답
예상문제유형: MST
시간: 760ms
메모리: 70,048kb
### 풀이방법
1. 테케 입력으로 들어오는 간선들을 다 저장!
2. 서로소 집합에서 0 을 탈출구로 설정해줌
3. 정점의 개수만큼 한번 더 입력을 받는데, 0번노드와 현재 있는 노드들을 연결하는 간선들을 모두 저장( 비용도 같이)
4. 정렬후 크루스칼

**Comment by haesoooo** [comment]
### 문제링크
#468
### 풀이사항
풀이일자: 241107
풀이시간: 1시간
채점결과: 실패
예상문제유형: MST

### 풀이방법
1. 테케 입력으로 들어오는 간선들을 다 저장!
2. 서로소 집합에서 0 을 탈출구로 설정해줌
3. 정점의 개수만큼 한번 더 입력을 받는데, 0번노드와 현재 있는 노드들을 연결하는 간선들을 모두 저장( 비용도 같이)
4. 정렬후 크루스칼
### 어려웠던점
크루스칼은 할 때마다 까먹음요 특히 서로소 연결해주는 union 구현부분 다시 기억하기
