### ISSUE TITLE
[BOJ] Gaaaaaaaaaarden

### ISSUE THREAD

**Issue by reasonyi** [SSAFY12th/ssafyAlgostudy#451]
문제 링크
https://www.acmicpc.net/problem/18809

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by reasonyi** [comment]
### 문제링크
#450 

### 풀이사항
풀이일자: 2024.11.05
풀이시간:  1시간 50분
채점결과: 정답
예상 문제 유형:  구현, bfs
시간: 1208 ms
메모리: 321,320kb

### 풀이방법
1. dfs로 우선 G+R개를 선택하는 조합을 구한다.
2. splitCombinations에서 뽑은 조합을 G개와 R개로 나누는 작업을 진행. 
- G개만큼 뽑아 group1에 넣고, 나머지 R개는 group2에 넣는다.
- 두 그룹에서 첫 번째 Point객체의 r값이 더 작은 그룹을 먼저 split ArrayList에 넣는다.
- Set에 split을 넣어서, 만약 중복된다면 제거될 수 있도록 한다.
- 위처럼 하면 G와 R을 서로 바꿔도 같은 경우 (ex. {1, 2, 3}, {4, 5, 6} = {4, 5, 6}, {1, 2, 3} 이런 경우...) 도 제거된다.
3. bfs로 꽃이 피는 경우를 확인한다. 같은 시간대에 퍼진 두 염료가 만난 경우만 꽃이 피기 때문에, Point객체에서 time을 조절해가며 퍼진 시간이 같은 경우에만 꽃이 피도록 한다.
4. bfs 내에서 result를 최대값으로 업데이트.

### 어려웠던 점
구상은 되는데 코드로 구현이 안되어서 좀 헤멨습니다

**Comment by sangholee235** [comment]
## 문제링크
#448

## 풀이사항
풀이일자: 241104
풀이시간: 40분
채점결과: 정답
예상문제유형: 백트래킹, 구현, 너비우선탐색
시간: 944 ms
메모리: 301,164 kb

## 풀이방법
1. 배양을 할 수 있는 좌표를 List에 저장한다.
2. 백트래킹으로 초록색, 빨간색 배양액이 뿌려질 위치를 결정한다.
3. 배양액이 뿌려질 위치가 모두 결정되면 시뮬레이션을 진행한다.
3-1. 큐에 {x좌표,y좌표,이동시간,색} 정보를 넣고 탐색한다.
3-2. 탐색하는 과정에서 색이 다른데 도착시간이 같다면 꽃을 피우고 답을 하나 증가시킨다.
4. 탐색을 마친 후 저장된 답을 출력한다.

## 느낀점
백트래킹으로 좌표 정하는게 제일 어려웠다. 연습해야겠다고 생각한다..

**Comment by kimdevspace** [comment]
### 문제링크
#464 
### 풀이사항
- 풀이일자: 241107
- 풀이시간: 2일
- 채점결과: 정답
- 예상문제유형: 완전탐색,시뮬레이션,BFS,구현
- 시간: 1,304ms
- 메모리: 299,056kb
### 풀이방법
1. 배양이 가능한 땅의 좌표를 리스트에 저장
2. 그 중에 G+R 개를 뽑음
3. 뽑은거 중에 G개를 뽑아서 초록색임을 정해줌
4. 위치를 정한 후 시뮬레이션 진행
5. 배양액이 퍼지면서 꽃을 피우는 것, 배양액의 색깔, 시간을 관리하기 위해 2차원이 두개가 존재하는 3차원 배열로 관리. 첫번째2차원에는 시간을 저장, 두번째2차원에는 배양액의 상태를 저장

### 어려웠던 점
1. 조합의 조합 뽑는거
2. 배양할수 있는 땅을 선택하는 인덱싱 디테일.. <-- 젤어려움
3. 시간처리를 위해 배열을 3차원으로 만들어 관리 2차원이 2개가 존재하는 3차원배열

**Comment by chanu2** [comment]
## 문제링크
#469 

## 풀이사항
풀이일자: 241104
풀이시간: 
채점결과: 실패
예상문제유형: 백트래킹, 구현, 너비우선탐색


## 풀이방법
1. 배양을 할 수 있는 위치를 조합으로 뽑는다. 
2. 백트래킹으로 초록색, 빨간색 배양액이 뿌려질 위치를 결정한다.
3. 배양액이 뿌려질 위치가 모두 결정되면 시뮬레이션을 진행한다.
3-1. 큐에 {x좌표,y좌표,이동시간,색} 정보를 넣고 탐색한다.
3-2, 큐에 모두 넣고 빼면서 겹치는 부분의 합을 구하고 합이 넘어가면 꽃이 피도록 구현했습니다. 그런데 시간초과 

## 느낀점
,,,,,,,

**Comment by haesoooo** [comment]
## 문제링크
#463

## 풀이사항
풀이일자: 241106
풀이시간: 5시간.. 이후 계속 디버깅했는데 안됨,,
채점결과: 테케만 맞고 시간초과
예상문제유형: 백트래킹, 구현, 너비우선탐색


## 풀이방법
1. 배양 가능한 위치 (2)들을 저장해놓고 거기에서 Red 좌표 먼저 뽑기
2. 나머지 좌표에서 Green 뽑기
3.큐에 시작 좌표 다넣기
4. 큐 크기만큼 동시에 돌면서 빨간색이면 1, 초록색이면 2 이런 식으로 방문 처리해주기
5. 다른색이 이미 온 자리면 -1로 바꾸기

## 느낀점
맞왜틀..

큐에 넣을 때 방문처리를 잘 해줘야하는데 그걸 못한게 실패요인 ?
