### ISSUE TITLE
[Programmers] 타겟넘버

### ISSUE THREAD

**Issue by chanu2** [SSAFY12th/ssafyAlgostudy#47]
문제 링크
https://school.programmers.co.kr/learn/courses/30/lessons/43165

### 풀이 사항
풀이 일자: 2024.08.01
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

### 풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by reasonyi** [comment]
문제 링크
#46 

풀이 사항
풀이 일자: 2024.08.01
풀이 시간: 8분 00초
채점 결과: 정답
예상 문제 유형: DFS

풀이 방법
배열에서 인덱스별로 호출하여 한 번은 +한 값, 한 번은 -한 값으로 재귀호출한다.

**Comment by chanu2** [comment]
문제 링크
#48 

풀이 사항
풀이 일자: 2024.08.01
풀이 시간: 18분 00초
채점 결과: 정답
예상 문제 유형: DFS

풀이 방법
배열에서 인덱스별로 호출하면서 더해주는 dfs를 통해서 모든 수의 합을 구하고 빼주는 dfs를 통해서 target값이 나오면 count++을 해준다.

**Comment by kimdevspace** [comment]
### 문제 링크
#49 
### 풀이 사항
풀이 일자 : 240801
풀이 시간 : 12분
채점 결과 : 정답
예상 문제 유형 : DFS, 백트래킹

### 풀이 방법
+와 -를 모두 고려해야 하기 때문에 두 개의 가지로 뻗어 나가면서 탐색해야 함.
마지막 깊이까지 도달헀을 때 계산 결과가 target과 같다면 정답카운트 ++

**Comment by kro46** [comment]
## 문제 링크

## 풀이 사항
풀이 일자 : 240801
풀이 시간 : 1시간
채점 결과 : 오답
예상 문제 유형 : DFS, 백트래킹

## 풀이 방법
+와 -를 모두 고려해야 하기 때문에 두 개의 가지로 뻗어 나가면서 탐색해야 함.
마지막 깊이까지 도달헀을 때 계산 결과가 target과 같다면 정답카운트 ++

**Comment by haesoooo** [comment]
### 문제 링크
#49 
### 풀이 사항
풀이 일자 : 240801
풀이 시간 : 45분
채점 결과 : 정답
예상 문제 유형 : DFS

### 풀이 방법
각 숫자에 대해 +로 dfs, -로 dfs 해서 sum 값을 갱신
마지막 depth 에서 sum이랑 target이랑 같으면 return
배열 for문으로 돌리다가 계속 중복되고 난리나서,, 오래 걸렷다
생각해보니 for문 없이 depth를 증가시키면서 이걸 index로 쓰면 되는거엿다!
