### ISSUE TITLE
[BOJ] 테트로미노

### ISSUE THREAD

**Issue by kimdevspace** [SSAFY12th/ssafyAlgostudy#479]
### 문제링크
https://www.acmicpc.net/problem/14500
https://github.com/kimdevspace/ssafyAlgostudy/blob/main/EuiJoong/Week17/BOJ_%ED%85%8C%ED%8A%B8%EB%A1%9C%EB%AF%B8%EB%85%B8_14500.java

### 풀이사항
풀이일자: 2024.11.14
풀이시간: 1시간30분
채점결과: 정답
예상 문제 유형: 완탐
시간: 704ms
메모리: 34,396kb

### 풀이방법
모든 칸에서 부터 깊이가 4가될 때까지 백트래킹을 통한 dfs를 해주면서 블록의 합을 구해주면 된다.
네 칸을 차지하는 모든 경우의 수를 구해주며 최대를 갱신하면 됨!
근데 ㅗ 모양의 블록은 백트래킹으로 할 수 없다.
두 번째 깊이에서 가지를 하나 더 늘려주며 ㅗ 모양을 고려한다.

### 어려웠던 점
ㅗ 모양 처리하는 거에서 고민을 많이 했습니다 .ㅠ

**Comment by kro46** [comment]
## 문제링크
#482 

## 풀이사항
풀이일자: 2024.11.14
풀이시간: 1시간15분
채점결과: 정답
예상 문제 유형: 구현/시뮬레이션
시간: 460ms
메모리: 31,448kb

## 풀이방법
1. 모든 모양에 맞게 dr , dc를 지정해줌(토네이도 풀었던 것처럼)
2. map 입력받고 max값을 MIN_VALUE로  초기화
3. 블록들이 가질 수 있는 총 모양이 19개이기 때문에 19방향에 대해서 map을 탐색
4. 한 블록에 대해 모든 탐색이 끝나면 max값 업데이트 해줌
5. 최종 결과 출력

## 어려웠던 점
무식하게 모든 모양 다 찍어놓고 돌리다보니까 중간에 방향 이상한 부분있으면 디버깅을 못할거같음.. 다행히 한 번에 성공해서 시간이 오래 걸리진 않았음.

**Comment by reasonyi** [comment]
## 문제링크
#489 

## 풀이사항
풀이일자: 2024.11.14
풀이시간: 30분
채점결과: 정답
예상 문제 유형: 구현/시뮬레이션
시간: 1160 ms
메모리: 307,076 kb

## 풀이방법
- dfs로 가능한 4개 모양을 모두 탐색하며 최대값 갱신한다.
- dsf로 탐색할 수 없는 모양인 'ㅏ' 모양에 대해 dir 배열에 r, c의 이동 인덱스를 저장한다.
- 'ㅏ' 모양만 따로 한번 더 확인해본다.
- 최대값 출력

## 어려웠던 점
빨리 풀긴 한거같은데 그냥 무식하게 모든 모양을 저장해두고 탐색하는것이 시간과 메모리 모두 월등하게 잘 나온다.
근데 너무 귀찮다...
