### ISSUE TITLE
[SWEA] 방향 전환

### ISSUE THREAD

**Issue by sangholee235** [SSAFY12th/ssafyAlgostudy#488]
문제 링크
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWyNQrCahHcDFAVP

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by sangholee235** [comment]
## 문제링크
#486

## 풀이사항
풀이일자: 241111
풀이시간: 1시간
채점결과: 정답
예상문제유형: 최단 경로 탐색
시간: 884 ms
메모리: 280,232 kb

## 풀이방법
1. 벽 뚫고 이동하기와 비슷하게, visited 배열을 3차원으로 생성한다.
2. 큐에 방향, 좌표, 현재 까지 이동거리를 저장한다.
3. 방향에 따라 이전 방향의 반대로만 진행한다.
4. 최종 위치에 도착하면, 종료한다.
5. 도착할때의 거리를 저장한다.
## 느낀점
범위가 음수~양수로 주어져서 100을 더해주고 했는데 그럼에도 불구하고
인덱스에서 실수가 많았다.. 다듬어야겠다.

**Comment by chanu2** [comment]
## 문제링크
#498 

## 풀이사항
풀이일자: 241111
풀이시간: 1시간 30분
채점결과: 정답
예상문제유형: bfs
시간: 327ms
메모리: 2209kb

## 풀이방법

- bfs를 돌면서 type을 전달해준다.
- 들어온 type 이 가로 방향으로 이동했다면 세로 방향 bfs를 진행한다.
- 들어온 type 이 세로 방향으로 이동했다면 가로 방향 bfs를 진행한다.
