### ISSUE TITLE
[SWEA] 작업순서

### ISSUE THREAD

**Issue by haesoooo** [SSAFY12th/ssafyAlgostudy#493]
### 문제 링크
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV18TrIqIwUCFAZN

### 풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

### 풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by haesoooo** [comment]
### 문제 링크
#492

### 풀이 사항
풀이 일자: 2024.11.08
풀이 시간: 20분
채점 결과: 정답
예상 문제 유형: 위상정렬
시간: 125 ms
메모리: 13,700 kb

### 풀이 방법
위상정렬의 핵심은 "depth"
노드 개수만큼의 depth 배열 선언, visited 배열 선언
단방향 간선 정보들을 입력받을 때, 화살표를 받는 쪽 노드의 depth++

depth가 최초에 0이며 방문하지 않은 노드들에 대해 bfs를 진행함.
최초에 0인 노드들을 queue에 삽입하고 방문처리 해준 다음, 그 노드로부터 뻗어나온 간선들에 대해 살펴본다.

해당 간선들을 거둔다는 느낌으로, 화살표를 받는 노드들의 depth--;
만약 depth가 0이 된 노드가 발생하면 해당 노드를 다시 queue에 삽입함
queue가 빌 때까지 반복함.


### 느낀점

위상정렬, 다익스트라, MST 등 그래프와 관련된 알고리즘은 한번만 알아두면 순조롭게 풀 수 있지만 모르면 절대 못푼다.
까먹지 말자!

**Comment by chanu2** [comment]
### 문제 링크
#496 

### 풀이 사항
풀이 일자: 2024.11.08
풀이 시간: 30분
채점 결과: 정답
예상 문제 유형: 위상정렬
시간: 144 ms
메모리: 13,700 kb

### 풀이 방법

위상 정렬은 각 노드마다 진입 차수를 배열에 저장하여 관리한다.
진입 차수가 0인 것들을 queue에 넣고 다음 노드를 찾는다.
노드를 방문 처리하면서 진입차수를 줄여준다.
