### ISSUE TITLE
[BOJ] 괄호 추가하기

### ISSUE THREAD

**Issue by haesoooo** [SSAFY12th/ssafyAlgostudy#495]
### 문제 링크
https://www.acmicpc.net/problem/16637

### 풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

### 풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by haesoooo** [comment]
### 문제 링크
#491

### 풀이 사항
풀이 일자: 2024.11.12
풀이 시간: 2시간
채점 결과: 정답
예상 문제: 부분집합
시간: 0 ms
메모리: 2024 kb

### 풀이 방법
숫자를 선택 -> visited를 true
선택하지 않음 -> visited를 false

- 현재 인덱스의 숫자를 선택 (괄호 안에 포함하겠다) 하면, 바로 다음 숫자까지 묶어서 괄호를 쳐야하므로 다다음 인덱스(idx + 2)로 넘어가서 재귀
- 현재 인덱스의 숫자를 선택하지 않으면, 다음 숫자를 선택할 수도 있으므로 다음 인덱스 (idx + 1)로 넘어가서 재귀

마지막 인덱스에 도달하면, visited true인 숫자에 한해서 괄호 계산을 먼저 해줌 
- ex) 8 * 3 + 5 에서 (8 * 3) + 5 라면 visited 배열은 1 1 0, num은 8 3 5 -> 계산한 값을 num에 다시 저장 -> 24 24 5
visited false인 숫자에 대해서는 이후에 계산
- ex) 24 24 5 에서 24 + 5 진행 -> 24 29 29
최종 값은 num[num.size() - 1] 에 담긴 값을 보면 됨


### 느낀 점
백트래킹은 정말 어떤 것을 파라미터로 넘기고 원복할 지를 결정하는 게 어렵다.

**Comment by chanu2** [comment]
### 문제 링크
#497 

### 풀이 사항
풀이 일자: 2024.11.12
풀이 시간: 2시간
채점 결과: 정답
예상 문제: 부분집합
시간:  108ms
메모리: 2024 kb

### 풀이 방법
- 괄호 마다 계산한 값을 리스트에 저장한다.
- 부분 집합으로 계산한 값들을 뽑는다.
-  계산한 값의 인덱스 가 1차이가 나지 않는 것들만 사용한다.
-  원본 배열을 값을 visited 처리 해주고 계산 해준다.
- 최대값을 갱신한다,



### 느낀 점
문제를 어떻게 접근해야 하는지 시간이 오래 걸린 것 같다

**Comment by kimjuheee** [comment]
### 문제 링크
https://github.com/kimjuheee/ssafyAlgostudy/blob/main/JuHee/Week17/BOJ_16637_%EA%B4%84%ED%98%B8%EC%B6%94%EA%B0%80%ED%95%98%EA%B8%B0.java

### 풀이 사항
풀이 일자: 2024.11.09
풀이 시간: 2시간
채점 결과: 정답
예상 문제: 부분집합
시간:  104ms
메모리:  14296KB

### 풀이 방법
- 수식에서 숫자와 연산자를 분리하여 각각 numbers와 operators 리스트에 저장
- 부분집합으로 가능한 모든 괄호 위치(계산 순서)를 탐색
- 각 탐색 경로에서 다음 숫자를 괄호로 묶거나 묶지 않는 두 가지 경우를 시도
- 연산 결과를 계산해 최댓값을 갱신하며 저장
- 가능한 모든 경우의 최댓값을 찾고, 최종적으로 그 값을 출력

### 느낀 점
부분집합 구현 부분이 어려웠다.
