### ISSUE TITLE
[Programmers]문자열 압축

### ISSUE THREAD

**Issue by chanu2** [SSAFY12th/ssafyAlgostudy#504]
### 문제 링크
https://school.programmers.co.kr/learn/courses/30/lessons/60057?language=java#

### 풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

### 풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by chanu2** [comment]
## 문제링크
#505 

## 풀이사항
풀이일자: 241211
풀이시간: 1시간
채점결과: 정답
예상문제유형: 자료구조, 문자열
test25 (4.88ms, 87.8MB)

## 풀이방법
1. 문자열 길이의 절반 만큼만 확인을 한다.
2. 1 ~ 문자열 길이/2 개수 만큼 문자를 자른다
3. stack peek()을 통헤서 문자열이 같은지 비교하고 같으면 count++해준다.
4.  다르면 stack에 count 값을 넣어주고 문자열도 넣어준다
5.  마지막 남은 count 처리를 위해 count > 1 일때  stack에 추가 한다.
6.  stack에서 모든 값을 꺼내 문자열로 바꿔 size를 구해 최솟값을 갱신

**Comment by sangholee235** [comment]
## 문제링크
#506 

## 풀이사항
풀이일자: 241211
풀이시간: 52분
채점결과: 정답
예상문제유형: 문자열

## 풀이방법
1. 압축 단위를 1부터 문자열 길이 절반까지 반복
2. 문자열을 단위 길이 만큼 순회
3. 현재 단위의 문자열을 추출
4. 이전 단위와 같으면 count ++
4-1. 아닐 경우 이전 단위 문자열과 반복 횟수를 압축 결과에 추가
5. 압축된 문자열의 길이와 최소 길이를 비교하여 갱신

**Comment by reasonyi** [comment]
## 문제링크
#507 

## 풀이사항
풀이일자: 241211
풀이시간: 1시간
채점결과: 정답
예상문제유형: 문자열
테스트 27 (2.84ms, 82.7MB)

## 풀이방법
1. 문자열을 자르는 길이는 최소 1개부터 최대 s.length()/2개까지 이다. 1부터 최대만큼 반복 +1씩하며 아래 내용을 반복한다.
2. 베이스가 되는 문자열을 구한다. = 0부터 i-1번째까지 s를 자른 문자열.
3. i번째부터  베이스와 비교하여 문자열이 같은지 보고, 같으면 cnt를 ++한다.
4. 다르다면 cnt가 1보다 큰 경우에만 cnt를 result에 추가한다. cnt의 값과 상관없이 베이스를 result에 추가한다.
5. 방금 비교한 다른 문자열을 베이스로 교체한다.
6. cnt는 1로 초기화한다.
7. reulst를 모두 구한 뒤, answer를 최소값으로 갱신한다.

## 어려웠던 점
처음에 스택을 쓰려고 했는데... 풀이 방법이 잘 생각 안나서 결국 다른 사람의 풀이 방법을 참고하였음.
문자열을 다룰 때는 Java에서 StringBuilder가 필수인 것 같다.

**Comment by kimjuheee** [comment]
## 문제링크
#512 

## 풀이사항
풀이일자: 241212
풀이시간: 1시간 32분
채점결과: 정답
예상문제유형: 문자열

## 풀이방법
- 1부터 문자열 길이 반까지의 길이에 대해 압축
- compress 함수로 압추된 문자열 길이 계산
- 연속된 부분 문자열이 동일하다면 count 증가시키고 다르다면 그 값을 결과 문자열에 추가
- 압축된 문자열의 길이를 구하고 그 중에서 가장 짧은 길이를 결과로 저장
- 결과 return

## 느낀점 
- sysout으로 출력하려고 했더니 출력 오류가 발생해서  StringBuilder로 변경했다. 오류 발생 이유를 모르겠다.
- 삼항 연산자 사용방법이 헷갈렸다..

**Comment by haesoooo** [comment]
## 문제링크
#513 

## 풀이사항
풀이일자: 241212
풀이시간: 1시간 20분
채점결과: 정답
예상문제유형: 문자열

## 풀이방법
- 1부터 문자열 길이의 절반까지의 길이에 대해 압축
- 문자열 조각들을 저장할 v 벡터 생성
- v 크기만큼 돌면서 중복된 조각이 있으면 첫번째 조각 앞에 숫자 추가, 이후 조각은 삭제

## 느낀점 
- 문자열이지만 어려운 알고리즘을 쓰진 않은 완전탐색!
- 그렇지만 어렵다
