### ISSUE TITLE
[PGS] 파일명 정렬

### ISSUE THREAD

**Issue by sangholee235** [SSAFY12th/ssafyAlgostudy#509]
### 문제 링크
https://school.programmers.co.kr/learn/courses/30/lessons/17686

### 풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

### 풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by sangholee235** [comment]
## 문제링크
#508 

## 풀이사항
풀이일자: 241211
풀이시간: 40분
채점결과: 정답
예상문제유형: 문자열

## 풀이방법
1. 파일 정렬을 위해 List로 선언
2. 파일명을 Stirng[] 에 head, number 나눠서 추출하는 메서드 만들기
3. 추출해서 head와 number를 순서대로 비교 (head는 대소문자 무시)
4. head와 number가 같으면 입력순서 유지

**Comment by reasonyi** [comment]
## 문제링크
#510 

## 풀이사항
풀이일자: 241212
풀이시간: 41분 57초
채점결과: 정답
예상문제유형: 문자열, 정렬
테스트 7 (15.32ms, 91.5MB)

## 풀이방법
1. 문자열을 head, number, tail로 구분하여 저장할 객체(MyString)를 만든다.
2. MyString에 Comparable을 implements하여 compareTo를 구현한다.
-  원본은 유지하되, 비교할 때는 대소문자, 숫자를 다르게 봐야하므로, 현재 객체와 새로 들어오는 객체 o의 head는 전부 소문자로 변경하고, number는 0011 -> 11 처럼 변경하기 위해 int형으로 변환한다.
- 만약 비교시 head가 다르다면 String의 compreTo를 활용하여 오름차순 정렬한다. head가 같다면 number가 작은 순으로 정렬한다.
3. files에 있는 문자열을 head, umber, tail로 구분하여 ArrayList에 저장한다.
4. 저장한 ArrayList를 sort한다.
5. 정렬한 ArrayList에서 객체를 하나씩 꺼내어 head, number, tail을 합친 뒤, answer ArrayList에 추가한다.
6. 구한 answer를 String[]으로 변환하여 반환한다.

## 느낀점
- 오랜만에 하니까 정렬 시 음수가 오름차순인지 양수가 오름차순인지 헷갈렸다...
- ArrayList를 일반 배열로 변경하는 방법을 아는 계기가 되었다.

**Comment by chanu2** [comment]
## 문제링크
#511 

## 풀이사항
풀이일자: 241212
풀이시간: 52분 
채점결과: 정답
예상문제유형: 문자열, 정렬
테스트 5 (15.83ms, 85.2MB)

## 풀이방법
- comparator를 사용하여 files를 정렬
- head 부분을 추출 
- compareTo를 사용하여 비교 
- number부분을 추출 Integer로 문자를 치환후 빼기 값을 return 

## 느낀점 
- compareTo 함수를 오랜만에 써서 헷갈렸다

**Comment by kimjuheee** [comment]
## 문제링크
#512 

## 풀이사항
풀이일자: 241212
풀이시간:  1시간 47분
채점결과: 정답
예상문제유형: 문자열

## 풀이방법
1. 입력받은 파일명을 HEAD, NUMBER, TAIL로 분리
- 문자열 처음부터 순회하면서 첫 순자의 인덱스 찾기
- 첫번째 숫자 이전까지 HEAD로 추출
- 숫자 부분은 5자리까지 NUMBER로 추출
- 남은 부분 TAIL로 저장
2. 정렬
- 첫번째로 HEAD로 비교
- 사전순으로 비교하고 HEAD가 다르면 해당 결과로 정렬
- 두번째로 NUMBER로 비교
- HEAD가 같을 경우 NUMBER로 결정

## 느낀점 
- 각 문자를 하나씩 비교해야하기 때문에 아스키 코드값을 비교하면서 숫자 시작 지점을 찾도록 하기 위한 부분 구현이 어려웠다.

**Comment by haesoooo** [comment]
## 문제링크
#513

## 풀이사항
풀이일자: 241212
풀이시간:  1시간 50분
채점결과: 정답
예상문제유형: 문자열

## 풀이방법
1. 입력받은 파일명을 head, number, order로 분리 (order는 입력받을 때 주어진 순서)
- 첫번째 숫자 전까지 head
- 숫자 부분은 5자리까지 number

2. 정렬 (비교 연산자 오버라이딩)
- 첫번째로 head로 비교
- head가 같으면 number로 비교
- number가 같으면 order로 비교
