### ISSUE TITLE
[Softeer] 출퇴근길

### ISSUE THREAD

**Issue by haesoooo** [SSAFY12th/ssafyAlgostudy#516]
### 문제 링크
https://softeer.ai/practice/6248

### 풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

### 풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by haesoooo** [comment]
### 문제 링크
#514

### 풀이 사항
풀이 일자: 2024.12.16
풀이 시간: 2시간
채점 결과: 정답
예상 문제 유형: 완전탐색
시간: 585 ms
메모리: 64.34MB

### 풀이 방법
집 (S) -> 회사 (T) / T -> S의 경로에서 모두 방문할 수 있는 임의의 정점 K라 하면
S -> K -> T (출근길)
T -> K -> S (퇴근길)

단방향 경로에 대해서 S에서 출발하는 모든 경우의 수를 구한다 (완전탐색) : 지나는 모든 점은 K를 만족한다 (visited1)
만약 K에서 지나는 모든 경로를 구하고 T를 지날 경우 카운트한다 -> 시간초과 (m이 최대 20만이므로)
그래서 단방향 경로를 뒤집어서 저장하고 (reverse) T에서 출발하는 경우를 모두 탐색한다 (visited2)

퇴근길도 똑같은 로직 (visited3, visited4)
마지막에는 임의의 노드 K에 대해서 visited1~visited4까지 모두 방문했다면 모든 조건을 충족하는 노드이므로 카운트

이 때 S와 T는 제외해야 하므로 카운트 - 2 = answer

**Comment by sangholee235** [comment]
### 문제 링크
#519

### 풀이 사항
풀이 일자: 2024.12.18
풀이 시간: 2시간 30분
채점 결과: 정답
예상 문제 유형: 그래프
시간: 815 ms
메모리: 91.91 MB

### 풀이 방법
정점 입력 받을때 정방향을 입력받고
역방향도 입력해둠

특정 정점에서 정점으로 탐색하는 BFS 메서드 제작
- 특정 정점을 도달하거나 더 이상 없으면 멈춤.
- 나아갈때마다 정점을 기록

1. 출발 -> 도착 정방향 탐색
2. 도착 -> 출발 역방향 탐색
3. 도착 -> 출발 정방향 탐색
4. 출발 -> 도착 역방향 탐색

모든 조건 만족하는 정점 집합 출력

### 어려웠던 점

4가지 경우를 나눈다는 생각을 해내기가 어려웠다.

1,4번 2,3번은 각각 똑같은게 아닌가 했는데 최단거리로만 집을 가는게 아니다 보니 

다른 경우가 생길 여지가 있었다.

**Comment by kimdevspace** [comment]
### 문제 링크
#523 

### 풀이 사항
풀이 일자: 2024.12.19
풀이 시간: 48분
채점 결과: 정답
예상 문제 유형: DFS
TC7 0.061s, 10.18MB

### 풀이 방법
시작노드에서 도달할 수 있는 노드들
도착노드에서 역방향 그래프를 통해 도달할 수 있는 노드들
도착노드에서 도달할 수 있는 노드들
시작노드에서 역방향 그래프를 통해 도달할 수 있는 노드들

DFS 탐색을 통해 Set 자료구조에 저장후 s1과 s2,  s3과 s4 의 교집합을 구한 후 s1, s3의 교집합을 구한다.

결과로 도출된 집합에서 시작노드와 도착노드를 빼준 것이 출퇴근에 들리는 길임

**Comment by chanu2** [comment]
### 문제 링크
#525 

### 풀이 사항
풀이 일자: 2024.12.19
풀이 시간: 1시간 30분
채점 결과: 정답
예상 문제 유형: DFS


### 풀이 방법
시작노드에서 도달할 수 있는 노드들
도착노드에서 역방향 그래프를 통해 도달할 수 있는 노드들
도착노드에서 도달할 수 있는 노드들
시작노드에서 역방향 그래프를 통해 도달할 수 있는 노드들

DFS 탐색을 4번 하면서 교집합이 있는 부분을 count 한다

**Comment by kro46** [comment]
## 문제 링크
#515 

## 풀이 사항
풀이 일자: 2024.12.17
풀이 시간: 6시간?(거의 밤새 풀었음...)
채점 결과: 정답
예상 문제 유형: DFS/BFS

## 풀이 방법
1. 총 4개의 visited 배열을 선언(FromHome, ToHome, FromCompany, ToCompany)
2. 집에서 출발하여 도착할 수 있는 모든 노드를 구함, 동시에 역방향으로 도달 노드에서 집으로 갈 수 있는지 체크
3. 회사에서 출발하여 도착할 수 있는 모든 노드를 구함, 동시에 역방향으로 도달 노드에서 회사로 갈 수 있는지 체크
4. 총 4번의 DFS 탐색을 하며 visited값을 업데이트하고 최종적으로 교집합 노드의 개수를 세어 출력

## 어려웠던 점
2번의 DFS 탐색으로 해결하려고 약 4시간정도 도전해봤으나 결과는 런타임에러... 후에 이 문제를 해설해주는 영상을 찾아봤는데 이런 아이디어(역방향 탐색으로 4번 DFS 돌리는 것)를 떠올리는게 참 대단하다는 생각이 들었다. 그래도 한 번 겪어봤으니 다음에 비슷한 문제가 나오면 풀 수 있을 것 같다.
