### ISSUE TITLE
[BOJ] 컵라면

### ISSUE THREAD

**Issue by sangholee235** [SSAFY12th/ssafyAlgostudy#521]
### 문제 링크
https://www.acmicpc.net/problem/1781

### 풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

### 풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by sangholee235** [comment]
### 문제 링크
#520

### 풀이 사항
풀이 일자: 2024.12.19
풀이 시간: 40분
채점 결과: 정답
예상 문제 유형: 그리디
시간: 1020 ms
메모리: 76,020 kb

### 풀이 방법
problem클래스 선언(deadline, reward)
마감일 기준으로 내림차순 정렬 같은 마감일 내에서는 보상이 큰순으로 정렬
가장 큰 데드라인부터 1까지 역순회
현재 마감일에 풀 수 있는 모든 문제를 큐에 추가
큐에서 우선순위 가장 높은 보상 선택
totalReward 계산

### 어려웠던 점
마감일 개념을 오해했다..
같은 마감일 내에서 보상이 큰것을 먼저 선택하는 것을 정리하는데 좀 시간을 썼다.

**Comment by kimdevspace** [comment]
### 문제 링크
https://github.com/SSAFY12th/ssafyAlgostudy/blob/main/EuiJoong/Week22/boj_%EC%BB%B5%EB%9D%BC%EB%A9%B4_1781.java

### 풀이 사항
풀이 일자: 2024.12.19
풀이 시간: 1시간 2분
채점 결과: 정답
예상 문제 유형: 정렬 우선순위 큐
시간: 828 ms
메모리: 77,832kb

### 풀이 방법
1. 데드라인, 컵라면 보상 형태의 배열을 리스트에 저장
2. 데드라인 기준으로 오름차순 정렬하되 데드라인이 같다면 컵라면 보상이 큰 순으로 정렬
3. 문제를 하나씩 탐색하면서 pq에 해당 문제의 컵라면보상을추가
4. 큐의 크기가 현재 데드라인을 초과하면 최솟값 제거
5. 우선순위 큐에 남아있는 모든 값이 정답!

**Comment by chanu2** [comment]
### 문제 링크
#524 

### 풀이 사항
풀이 일자: 2024.12.19
풀이 시간: 2시간
채점 결과: 정답
예상 문제 유형: 그리디 / 정렬
시간: 655 ms
메모리: 71,892 kb

### 풀이 방법
1. 데드라인과 컵라면의 정보를 담을 Study 클래스를 선언한다. Comparable을 상속받아 컵라면이 더 많은 순서대로, 같다면 데드라인이 더 긴 순서대로 정렬한다. (우선순위 큐에서 사용)
2. 입력받은 정보를 ArrayList에 넣고, 데드라인만 가지고 데드라인이 더 긴 순서대로 먼저 정렬한다.
3. qp를 하나 더 만들어서 컵라면 가중치를 저장 
4. qp 사이즈를 기준으로 deadLine을 비교하여 queue에서 빼고 넣고 한다

### 어려웠던 점
첨에 정렬을 이리저리 바꿔가며 해봤는데 도저히 모르겠어서 다른 풀이를 참고했다. 정렬과 pq를 같이 활용하는 풀이 방법은 처음 봐서 떠올리기 어려웠다.

**Comment by kimjuheee** [comment]
## 문제링크
#526 

## 풀이사항
풀이일자: 241219
풀이시간: 2시간 30분
채점결과: 정답
예상문제유형: 그리디

## 풀이방법
- 데드라인을 순서대로 정렬
- 컵라면의 수가 데드라인의 갯수 초과하면 제일 작은 것만 저장
- 큐가 비어있지 않으면 가장 큰 컵라면 갯수 저장하면서 갱신

## 느낀점 
- 처음에 Q를 사용해야하는 줄 알았는데 다른 풀이 참고해서 PQ를 적용해야하는 것을 깨달았다.
- 오랜만에 그리디 다시 적용해보려고 하니까 어려웠다 ...

**Comment by kro46** [comment]
## 문제 링크
#518 

## 풀이 사항
풀이 일자: 2024.12.18
풀이 시간: 2시간 30분
채점 결과: 정답
예상 문제 유형: 그리디 / 정렬
시간: 908 ms
메모리: 74,812 kb

## 풀이 방법
1. problem클래스 선언(deadline, cup)
2. 마감일 기준으로 내림차순 정렬
3. PQ에 현재 마감일에 풀 수 있는 모든 문제의 컵라면 수를 큐에 추가
4. PQ의 크기가 마감일보다 커지면 컵라면 수가 작은 것부터 큐에서 제거
5. 큐에 남은 컵라면 수를 모두 더하여 출력

## 어려웠던 점
처음 풀이를 시작했을 때에는 마감일에만 문제를 풀 수 있는 것으로 착각하여 코드 제출을 했는데 4%에서 계속 막혔다. 근데 반례를 몇 개 찾아보니 마감일 전에만 문제를 해결하면 되는 것을 알게되었다. 그래서 우선순위 큐를 사용하는 것으로 해결했다!
