### ISSUE TITLE
[PGS] 석유 시추

### ISSUE THREAD

**Issue by reasonyi** [SSAFY12th/ssafyAlgostudy#531]
문제 링크
https://school.programmers.co.kr/learn/courses/30/lessons/250136

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by reasonyi** [comment]
### 문제 링크
#530 

### 풀이 사항
풀이 일자: 2024.12.24
풀이 시간: 19분 20초
채점 결과: 정답
예상 문제 유형: DFS / BFS / 시뮬레이션
정확성 테스트: 테스트 9 (1.06ms, 77.4MB)
효율성 테스트: 테스트 5 (51.89ms, 74.5MB)

### 풀이 방법
1. 0과 1은 처음 받은 배열에서 이미 사용하고 있기 때문에 배제하고 2번부터 사용하도록 ArrayList와 num값을 조정한다.
2. 맵을 전부 돌면서 1이 있으면 dfs를 활용하여 해당 구간을 num으로 번호매긴다. 동시에 총 개수를 세어 ArrayList에 저장한다.
3. 각 열마다 아래로 내려가보면서 0이 아닌 공간이 있을 경우, (석유인 경우) 이미 방문한 곳인지 확인한다. 방문하지 않았다면 방문 처리 후 석유 개수를 sum에 더한다.
4. max값을 갱신한다. 

### 느낀점
다리만들기랑 비슷하다는 느낌이었음

**Comment by sangholee235** [comment]
### 문제 링크
#535 

### 풀이 사항
풀이 일자: 2024.12.25
풀이 시간: 1시간
채점 결과: 정답
예상 문제 유형: BFS 

### 풀이 방법
1. 덩어리에 번호를 매길 2차원 배열 선언
2. 덩어리의 크기를 기록할 List 선언
3. BFS로 덩어리 별 크기를 계산하여 리스트에 저장
4. 각 열에 대해 순회하며 해당 열에서 얻을 수 있는 최대 석유랑 계산
5. 최대 석유량 리턴

### 느낀점
처음에는 각 열에서 꽂을 때마다 BFS 돌아서 시간초과 났던 기억이 있다. 효율성을 생각해야겠다 !

**Comment by chanu2** [comment]
### 문제 링크
#540 

### 풀이 사항
풀이 일자: 2024.12.25
풀이 시간: 25분
채점 결과: 정답
예상 문제 유형: BFS 
풀이 시간: 93.72ms / 69.9MB

### 풀이 방법
1. bfs를 돌면서 각각의 구역에 번호를 매긴다.
2.  각각의 구역 번호와 개수를 hashMap에 저장
3. 행을 돌면서 석유를 뽑는다 land를 돌면서 hashSet에 구역 번호를 저장한다.
4. hashSet에 있는 값들을 뽑아 map에서 찾아서 최대 값을 구한다.

**Comment by kimdevspace** [comment]
### 문제 링크
#541 

### 풀이 사항
풀이 일자: 2024.12.25
풀이 시간: 50분
채점 결과: 정답
예상 문제 유형: BFS
풀이 시간: tc5 0.45ms / 84.2MB

### 풀이 방법
처음에는 단순하게 열을 탐색하면서 bfs를 해 누산해줬는데 시간초과가 났다..
찾아보니 set 자료구조로 구역들의 크기를 정해준 후 마지막에 해줘야 한다고 합니다.
시간초과가 나는 원인을 잘 파악해야 해요 500 x 500의 제곱 조금 안될만큼 bfs를 해야하니 당연히 시간초과가 납니다.

**Comment by kro46** [comment]
## 문제 링크
#544 

## 풀이 사항
풀이 일자: 2024.12.25
풀이 시간: 1시간 30분
채점 결과: 정답
예상 문제 유형: BFS
풀이 시간: 테스트 5 (82.98ms, 73.6MB)

## 풀이 방법
1. 맵 크기에 맞게 visited 배열을 만듦 -> visited[N][M]
2. 각 열마다 뽑아낼 수 있는 총 석유량을 저장해둘 배열을 선언 -> int[] capacities
3. 맵을 탐색하면서 석유부분이 찾으면 HashSet을 만들어서 해당 석유 덩어리가 포함된 열을 저장
4. BFS의 반환값으로 석유 덩어리 크기를 받아 Set에 있는 열 번호에 맞게 capacities에 더해줌
5. 반복이 끝나면 capacities를 정렬하고 마지막인덱스 값을 answer에 대입

## 어려웠던 점
아무생각없이 BFS를 열마다 돌리다가 시간초과나서 당황함. 근데  생각해보니 맵이 꽤 커서 그럴만했음. 그래서 새로운 방법이 필요했고, 알아낸 방법이 Set을 써서 해당 영역에 포함된 열을 알아내는 것이었음. 이렇게 풀면 O(NxM)의 시간복잡도로 문제 해결 가능.원래대로라면 최악의 경우 O(Mx(N*M))의 시간복잡도가 걸리기 때문에 효율적이지 못한 방법임. 비슷한 문제가 기업코테문제로 나올수도 있다는 생각이 들어서 앞으로는 Set을 쓰는 방법을 의식적으로 고려해봐야겠음.

**Comment by haesoooo** [comment]
## 문제 링크
#549

## 풀이 사항
풀이 일자: 2024.12.26
풀이 시간: 1시간 50분
채점 결과: 정답
예상 문제 유형: DFS
풀이 시간: 테스트 5 (16.79ms, 26.6MB)

## 풀이 방법
- DFS를 통해서 석유 덩어리들의 각 크기를 찾음
   - set에 석유에 해당하는 열들을 저장하고, dfs 빠져나와서는 dp[set에 해당하는 원소들]에 값을 모두 저장함
- 열 별로 시추 가능한 애들 구하기
- 석유 덩어리들을 구할 때, 각 열들에 대해 석유들의 크기를 미리 구해놓음



dp[set에 해당하는 원소들]에 저장해놓고, 마지막에 최댓값만 구한다.
dp는 아닌데 그냥 테이블 이름을 dp라고 해보았다..

## 어려웠던 점
bfs로 풀면 훨씬 쉬운 문제이다.
효율성에서 시간초과나서 set을 활용하는 방안을 구글링해서 참고했다,,

**Comment by kimjuheee** [comment]
## 문제 링크
#551 

## 풀이 사항
풀이 일자: 2024.12.26
풀이 시간: 2시간
채점 결과: 정답
예상 문제 유형: BFS

## 풀이 방법
- 석유 발견했을 때 BFS 탐색해서 석유 얼만큼 있는지 count
- 석유 덩어리 합한 값 더해서 출력

## 어려웠던 점
- 처음에 코드를 작성할 때 효율성을 고려하지 않아 계속 오답으로 채점되었다.
