### ISSUE TITLE
[BOJ] 상범빌딩

### ISSUE THREAD

**Issue by reasonyi** [SSAFY12th/ssafyAlgostudy#533]
문제 링크
https://www.acmicpc.net/problem/6593

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by reasonyi** [comment]
### 문제 링크
#532 

### 풀이 사항
풀이 일자: 2024.12.24
풀이 시간: 34분 9초
채점 결과: 정답
예상 문제 유형: DFS / BFS
시간: 164 ms
메모리: 17,908 kb

### 풀이 방법
1. 0 0 0이 입력되기 전까지는 무한으로 입력받는다.
2. L, R, C를 입력받아 저장하고 [L][R][C] 크기의 3차원 배열을 만든다.
3. 맵을 입력받는다. 입력받으면서 S가 있는 위치를 시작지점으로 저장한다.
4. 시작지점에서 출발하여 BFS로 E를 찾는다. E를 찾으면 result를 cnt만큼으로 업데이트하고 BFS를 종료한다.
5. 만약 도착지점으로 갈 수 없다면 result가 초기값인 0으로 지정되어있다. 이 경우 "Trapped!" 를 출력한다. 
6. 만약 도착지점으로 갈 수 있다면 문제의 조건에 맞게 출력한다.

### 어려웠던 점
출력할때 minute(s) 뒤에 온점(.)을 안붙여주면 16퍼에서 계속 틀린다.... 여기서 삽질 좀 했다. 문제 조건을 잘 읽어봐야겠다.

**Comment by sangholee235** [comment]
### 문제 링크
#534

### 풀이 사항
풀이 일자: 2024.12.25
풀이 시간: 30분
채점 결과: 정답
예상 문제 유형: 최단거리탐색
시간: 160 ms
메모리: 18,536 kb

### 풀이 방법
1. 'S' 인곳 좌표 저장
2. 'S' 인곳부터 'E' 까지의 3차원 BFS 탐색
3. 좌표, 거리 큐에 저장
4. 거리가 무한대라면 Trapped! 출력, 아니라면 거리 출력


### 어려웠던 점
빈 입력 처리때문에 머리가 아팠습니다.

**Comment by kimdevspace** [comment]
### 문제 링크
#538 

### 풀이 사항
풀이 일자: 2024.12.25
풀이 시간: 20분 0초
채점 결과: 정답
예상 문제 유형: BFS
시간: 180 ms
메모리: 19,608 kb

### 풀이 방법
단순 3차원 맵 탐색
bfs나 dfs를 사용하여 S에서 출발하여 E에 도달하는 조건에 맞춰 탈출과 함정을 출력해주면 됨

### 어려웠던 점
없습니다. 감 잡기에 좋은 문제같아요. 감잡아서 앞으로 더 취업준비에 열심히 해보겠습니다!>!>!>!>!>

**Comment by kro46** [comment]
## 문제 링크
#542 

## 풀이 사항
풀이 일자: 2024.12.23
풀이 시간: 1시간
채점 결과: 정답
예상 문제 유형: BFS/DFS
시간: 172 ms
메모리: 18,232 kb

## 풀이 방법
1. 맵을 입력받으면서 동시에 시작점/끝점을 저장
2. 입력받은 층수, 행, 열이 모두 0이면 반복에서 탈출
3. 3차원 visited배열을 만들어서 시작점부터 한칸씩 이동하면서 방문체크
4. 현재위치가 끝점인지 비교하여 끝점이면 이전까지 이동한 횟수를 StringBuilder에 저장
5. BFS를 끝까지 돌았는데 끝점에 도달하지 못했으면 Trapped를 StringBuilder에 저장
6. 결과 출력

## 어려웠던 점 
오랜만에 BFS구현 해보니까 오타가 너무 많았음. EX) visited[nl][nr][nc]로 구현해야하는데 visited[l][r][c]로 구현
감각이 너무 떨어져서 감각을 올릴 필요성을 매우 느낌.

**Comment by haesoooo** [comment]
## 문제 링크
#550

## 풀이 사항
풀이 일자: 2024.12.26
풀이 시간: 1시간 40분
채점 결과: 정답
예상 문제 유형: BFS
시간 (C++): 4 ms
메모리 (C++) : 2084 kb

## 풀이 방법
1. 맵을 입력받고 시작 좌표를 저장
2. bfs 시작 => z, y, x 좌표와 좌표별 이동횟수인 cnt 까지 총 4개의 변수를 튜플로 저장해서 큐에 튜플을 원소로 다룸
3. E (도착 좌표) 에 도달할 시 도착 여부를 나타내는 flag = true 로 변경 후 결과 배열에 cnt 저장하고 bfs 종료
4. bfs 종료 후 flag가 false일 경우 결과 배열에 -1 저장
5. while문 다 끝나고 결과 배열을 순서대로 출력함

## 어려웠던 점 
3차원 bfs를 오랜만에 구현해보았는데 x,y,z 순서를 z, y, x로 정해두고 풀다보니 도중에 혼자 헷갈려서 헤맸다
그리고 오랜만에 하니까 visited 배열을 언제 써야하는지 또 까먹었어요 .... 그래서 멍충하게 계속 헤맸다 .....

**Comment by chanu2** [comment]
### 문제 링크
#546 

### 풀이 사항
풀이 일자: 2024.12.24
풀이 시간: 40분 
채점 결과: 정답
예상 문제 유형: DFS / BFS
시간: 164 ms
메모리: 17,908 kb

### 풀이 방법
1. 0 0 0이 입력되기 전까지는 무한으로 입력받는다.
2. L, R, C를 입력받아 저장하고 [L][R][C] 크기의 3차원 배열을 만든다.
3. 방문처리를 위한 visited[][][]를 만든다. 
4. 초기 위치와 끝 위치를 배열에 저장한다.
5.  visited[][][] + 1을 통해서 최단거리를 찾는다
6.  3차원으로 bfs를 돌리고 끝지점에 도착했다면 결과를 도출한다.

**Comment by kimjuheee** [comment]
## 문제 링크
#552 

## 풀이 사항
풀이 일자: 2024.12.26
풀이 시간: 2시간 30분
채점 결과: 오답
예상 문제 유형: BFS

## 풀이 방법
1. 3차원 맵 탐색
2. 조건에 부합하면 탈출 및 탐색

## 어려웠던 점
- 3차원 맵 탐색 처음이라 어려웠다.
- 오랜만에 BFS 사용해봐서 전체적인 틀을 구현하는데 어려웠다.
- 컴파일 에러 발생 이유를 모르겠다.
