### ISSUE TITLE
[PGS] 캐시

### ISSUE THREAD

**Issue by sangholee235** [SSAFY12th/ssafyAlgostudy#537]
문제 링크
https://school.programmers.co.kr/learn/courses/30/lessons/17680

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by sangholee235** [comment]
### 문제 링크
#536 

### 풀이 사항
풀이 일자: 2024.12.25
풀이 시간: 40분
채점 결과: 정답
예상 문제 유형: 자료구조

### 풀이 방법
1. 캐시사이즈가 0일 경우 모든 요청이 캐시 미스이므로 cities길이 * 5 리턴
2. cache를 LinkedHashSet으로 선언 (중복 불가, 순서유지)
3. cities를 순회하며 캐시 히트시 totaltime +1 , 해당 도시 맨뒤로 보냄
4. 캐시 미스시 totaltime + 5
4-1. 캐시가 가득 찼다면, Iterator 자료구조를 사용하여 가장 오래된 항목 제거
(LinkedHashSet은 인덱스를 사용하지 않기 때문에 직접 접근이 불가하므로 Iterator를 통해 맨앞 데이터 가져옴)
5. 맨 뒤에 도시 추가

### 느낀점
자료구조를 많이 알아두자.

**Comment by reasonyi** [comment]
### 문제 링크
#539 

### 풀이 사항
풀이 일자: 2024.12.25
풀이 시간: 13분
채점 결과: 정답
예상 문제 유형: LRU (Least Recently Used)
테스트 13 (2.91ms, 86MB)

### 풀이 방법]
1. 대소문자 구분을 하지 않기 위해 도시 이름을 전부 소문자로 변경한다.
2. 도시 이름을 하나하나 가져와서 캐시에 해당 도시가 있는지 확인한다.
3. 만약 캐시에 해당 도시가 없다면 miss로 실행시간 5를 추가하고 캐시에 도시 이름을 추가한다.
4. 캐시 사이즈보다 값이 많아지면 가장 오래된 값을 캐시에서 삭제한다.
5. 만약 캐시에 해당 도시가 있다면 hit으로 실행시간 1을 추가하고 기존 캐시에 있던 값을 지운 뒤 다시 추가하여 가장 앞으로 가져온다.
6. answer를 return한다.

### 어려웠던 점
LRU알고리즘을 전혀 모른다면 풀지 못하는 문제라고 생각한다. 
문제를 풀기 전 알고리즘을 찾아보느라 시간이 조금 지체됐다.
운영체제 시간에 배웠던 기억이 나는데... CS 공부를 열심히 해야겠다...

**Comment by kro46** [comment]
## 문제 링크
#543 

## 풀이 사항
풀이 일자: 2024.12.24
풀이 시간: 1시간
채점 결과: 정답
예상 문제 유형: 자료구조

## 풀이 방법
1. 캐시사이즈가 0일 경우 모든 요청이 캐시 미스이므로 cities길이 * 5 리턴
2. cache를 LinkedHashSet으로 선언 (중복 불가, 순서유지)
3. cities를 순회하며 캐시 히트시 answer +1 , set.remove(히트한 도시) , set.add(히트한 도시)를 순서대로 수행(순서 맨 뒤로 이동)
4. 캐시 미스시 answer + 5 , set.add(미스한 도시)
4-1. 캐시가 가득 찼다면, Iterator 자료구조를 사용하여 가장 오래된 항목 제거
(LinkedHashSet은 인덱스를 사용하지 않기 때문에 직접 접근이 불가하므로 Iterator를 통해 맨앞 데이터 가져옴)
 + 맨 뒤에 도시 추가

## 어려웠던 점 
LRU 패턴이 기억안나서 찾아봤다. 그리고 처음에 문제를 잘못 읽어서 LRU와 LFU를 동시에 고려하는 코드를 짜려다가 멘붕와서 좀 해멨다. 근데 남들 풀이를 조금 참고했더니 그냥 오래된거부터 지우는거여서 현타옴.. 암튼 CS공부도 이제 슬슬 시작해야겠다..

**Comment by kimdevspace** [comment]
### 문제 링크
#545 

### 풀이 사항
풀이 일자: 2024.12.26
풀이 시간: 30분
채점 결과: 정답
예상 문제 유형: 자료구조
시간, 메모리 : tc 11 36.75ms, 109MB

### 풀이 방법
LRU 알고리즘을 알고 있어야 한다.
1. 참조된 것이 있다면 가장 오랫동안 참조되지 않은 순으로 순서를 변경해야 한다.
2. 캐시사이즈가 가득 차있다면 가장 오랫동안 참조되지 않은 걸 제거 후 저장한다.

자료구조는 삽입과 삭제가 많이 일어나고 때때로는 참조된 값이 중간에 있을 때 삭제에 용이하게 하기 위해 LinkedList를 사용해야 할것같아 사용해봤습니다.

캐시사이즈가 0인 경우는 cities 의 크기 * 5 만큼을 리턴해주면 됩니다요~

### 느낀점

요새 cs 스터디도 하고 있는데 자료구조, 운영체제 등등 다방면으로 알고있어야 풀 수 있는 문제 같습니다.

**Comment by haesoooo** [comment]
### 문제 링크
#548

### 풀이 사항
풀이 일자: 2024.12.23
풀이 시간: 40분
채점 결과: 정답
예상 문제 유형: 자료구조
시간, 메모리 : 테스트 11 27.64ms, 12.6MB (C++)

### 풀이 방법
자료구조 중 덱을 이용하였습니다.
- LRU (오랫동안 참조되지 않은 순서를 따른다) 를 구현
    - 덱에 존재하는 도시일 경우 (cache hit) 덱에서 해당 문자를 한번 제거하고 앞에다 해당 문자를 삽입 (push_front)
    - 덱에 존재하지 않는 도시일 경우 (cache miss) 캐시 크기보다 덱 크기가 작을 때만 앞에 해당 문자를 삽입 (push_front)
    - 덱 크기가 캐시 크기 제한에 도달할 경우에는 뒤에서부터 제거함 (pop_back) : 가장 오래 사용되지 않은 문자이므로


### 느낀점
오랫동안 사용되지 않은 것을 어떻게 순서를 구분할지, 어떤 자료구조를 사용할지 고민하는데 오래걸렸다!

**Comment by chanu2** [comment]
### 문제 링크
#547 

### 풀이 사항
풀이 일자: 2024.12.26
풀이 시간: 1시간
채점 결과: 정답
예상 문제 유형: 자료구조


### 풀이 방법
LRU 알고리즘을 몰라서 테스트 케이스 보면서 규칙을 찾았다 
1.  캐시 사이즈와 queue 사이즈를 비교하여 캐시 사이즈 보다 작으면 queue에 포함 되어있는지 확인
2. 포함 돼 있으면 지우고 뒤로 삽입
3. 포함이 안돼있으면 그냥 삽입
4. 결과를 도출

**Comment by kimjuheee** [comment]
## 문제 링크
#553 

## 풀이 사항
풀이 일자: 2024.12.26
풀이 시간: 1시간 45분
채점 결과: 정답
예상 문제 유형: 자료구조

## 풀이 방법
1. 도시 있다면 해당 도시 지우고 맨 뒤에 추가
2. 캐시가 꽉 차있으면 맨 앞 도시 지우기
3. 캐시가 다 안찼으면 맨 뒤에 추가

## 어려웠던 점 
- LRU알고리즘이 생소해서 알고리즘에 대해 생소해서 학습했다.
- CS 공부를 더 꼼꼼하게 해야겠다는 생각이 들었다.
