### ISSUE TITLE
[BaekJoon] 토마토

### ISSUE THREAD

**Issue by chanu2** [SSAFY12th/ssafyAlgostudy#58]
문제 링크
https://www.acmicpc.net/problem/7576

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by kro46** [comment]
## 문제 링크
#62 

## 풀이 사항
풀이 일자: 2024.08.02
풀이 시간: 3시간정도? 
채점 결과: 정답
예상 문제 유형: BFS/DFS

## 풀이 방법
1. 입력 받은 문자열 중 익은 토마토가 있는 위치와 토마토가 없는 위치를 구분하여 List에 담아 둔다.
2. 익은 토마토가 있는 위치를 Point클래스를 이용하여 Queue에 offer한다.
3. while반복문 안에서 익은 토마토의 개수(초기 Queue의 size)로 BFS를 여러 갈래로 분기 -> 이거 생각하는게 좀 걸림
4. 익은 토마토의 4방을 체크하며 아직 익지 않은 토마토들을 방문(그 곳의 값을 1로 초기화)
5. BFS 한 사이클을 돌리고 나면 while의 가장 마지막 부분에서 <b>Queue의 size가 0이 아니면 day++ </b>-> 이거 생각 못해서 계속 결과값이+1 되어서 나옴;;

**Comment by kimdevspace** [comment]
### 문제 링크
#74 
### 풀이 사항
풀이 일자 : 240806
풀이 시간 : 20분
채점 결과 : 정답
예상 문제 유형 : BFS
### 풀이 방법
익은 토마토를 큐에 미리 넣어 +1 을 해주면서 BFS 탐색
토마토가 다 익고 나서도 안익은 토마토 존재 시 ans는 -1 출력!
안익은 토마토 없을 시 배열 탐색 하며 최댓값 갱신 후 -1후 출력!
상호의 아이디어를 얻었습니다

**Comment by chanu2** [comment]
### 문제 링크
#80 
### 풀이 사항
풀이 일자 : 240806
풀이 시간 : 43분
채점 결과 : 정답
예상 문제 유형 : BFS
### 풀이 방법
- 익은 토마토가 있는 곳 배열로 저장
- queue에 모든 익은 토마토를 저장 bfs 돌면서 내부에 있는 모든 노드를 꺼내 상,하,좌,우 확인 후 queue 삽입 모든 요소를 꺼낼때 day++
- 배열에 0이 존재하는지 확인 
- 결과 값 리턴

**Comment by reasonyi** [comment]
### 문제 링크
#84 

### 풀이 사항
풀이 일자 : 2024.08.07
풀이 시간 : 29분 36초
채점 결과 : 정답
예상 문제 유형 : BFS

### 풀이 방법
- 토마토의 위치를 저장할 클래스 Point의 필드로 r, c및 day를 추가하여, 해당 토마토가 며칠째에 익었는지 표시해서 날짜를 count한다.
- map을 받을 때 안익은 토마토의 개수를 미리 저장하여 출력 시 활용한다.
- map을 받을 때 익은 토마토를 미리 queue에 삽입한다.
- map을 다 받아도 안익은 토마토의 개수가 0이면 0 출력.
- 아니라면 bfs를 활용하여 토마토가 모두 익는데 걸리는 날짜를 구한다.
- bfs가 끝났는데 안익은 토마토의 개수가 남았다면 -1출력, 아니라면 걸린 날짜를 출력한다.

**Comment by haesoooo** [comment]
### 문제 링크
#99 

### 풀이 사항
풀이 일자 : 2024.08.07
풀이 시간 : 32분
채점 결과 : 정답
예상 문제 유형 : BFS

### 풀이 방법
- map을 입력 받음
- 입력 중에, 익은 토마토의 위치를 모두 저장함 (queue)
- 입력이 끝나고, bfs 전에 토마토 queue 크기가 N * M이면 모두 익어있으므로 0 출력 후 return
- 익힌다 (bfs) -> 큐에서 토마토 위치를 꺼내면서, 4방향에 대해 안익은 토마토가 존재하면 해당 위치를 익힌다, 이 때 현재 위치의 배열 값 + 1을 저장하며 day를 증가시킴
- map 전체를 돌면서, 0이 존재하면 (안익음) -1 출력 후 리턴. 매 인덱스마다 최대 day값을 비교 갱신.

**Comment by kimjuheee** [comment]
### 문제링크
#90

### 풀이사항
풀이일자 : 240807
풀이시간 : 2시간
메모리 : 346964KB
시간 : 1512ms
채점 결과 : 정답
예상 문제 유형 : BFS

### 풀이 방법
큐에서 현재 위치와 토마토를 꺼내고 상하좌우로 이동 가능한 위치를 계산한다.
이동 가능한 위치가 아직 익지 않은 토마토인 경우, 큐에 추가하고 그 위치의 값을 현재 토마토의 값 +1로 설정한다.
반복이 끝난 후 ,배열 순회하여 모든 토마토가 익었는지 확인하고, 가장 오래 걸린 날 수를 계산한다.
