### ISSUE TITLE
[BaekJoon] 치킨배달

### ISSUE THREAD

**Issue by chanu2** [SSAFY12th/ssafyAlgostudy#59]
문제 링크
https://www.acmicpc.net/problem/15686

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by reasonyi** [comment]
문제 링크
#72 

풀이 사항
풀이 일자: 2024.08.05
풀이 시간: 35분 26초
채점 결과: 정답
예상 문제 유형: DFS, 브루트포스, 백트래킹

풀이 방법
- 치킨집과 집의 위치를 담을 배열을 만들어 저장해둔다.
- dfs를 활용하여 전체 치킨집 중, m개의 치킨집을 선택한다. (조합)
- 집집마다 치킨 거리를 구해 더하여 도시의 치킨 거리를 구하고, 최소값과 비교하여 갱신한다.

**Comment by chanu2** [comment]
문제 링크
#78 

풀이 사항
풀이 일자: 2024.08.05
풀이 시간: 40분 35초
채점 결과: 정답
예상 문제 유형: DFS, 백트래킹

풀이 방법
- 치킨집과 집을 각각 배열을 만들어 저장.
- 백트레킹을 통해 조합을 구한다. 이때 중복 선택되지 않도록 탐색 위치 인덱스를 제공한다.
- 집집마다 치킨 거리를 구해 더하여 도시의 치킨 거리를 구하고, 최소값과 비교하여 갱신한다.

**Comment by kro46** [comment]
## 문제 링크
#82 

## 풀이 사항
풀이 일자: 2024.08.07
풀이 시간: 1시간 
채점 결과: 정답
예상 문제 유형: DFS

## 풀이 방법
치킨 집, 일반 집을 각각 리스트에 담아 둠 
폐업하지 않을 치킨 집은 DFS로 선정
선택된 집을 방문할 때마다 최소 거리를 계산하여 이전 최소 거리와 비교 후 값을 갱신

**Comment by kimdevspace** [comment]
### 문제 링크
https://www.acmicpc.net/problem/15686
### 풀이 사항
풀이 일자 : 240808
풀이 시간 : 1시간 30분
채점 결과 : 정답
메모리 : 18148KB
예상 문제 유형 : DFS, 백트래킹
### 풀이 방법
치킨집의 좌표와 집의 좌표를 리스트에 담아서
최대 치킨집 중 M 개를 뽑아
도시의 치킨거리의 최솟값을 구한다!

**Comment by kimjuheee** [comment]
### 문제링크
https://github.com/SSAFY12th/ssafyAlgostudy/commit/e77eaddc5172a3f88e7d876a501db83eafcb9ae0
PR 잘못 이슈로 링크 첨부합니다 ...

### 풀이사항
풀이일자 : 240808
풀이시간 : 2시간 30분
메모리 : 22752KB
시간 : 328ms
채점 결과 : 정답
예상 문제 유형 : 백트랙킹

### 풀이 방법
도시 크기와 각 칸의 상태를 배열에 저장한다.
선택된 치킨 가게들에 대해 각 집에서 가장 가까운 치킨 가게의 거리를 계산한다.
계산된 총 거리가 현재의 최소 거리보다 작으면 minChickenDistance를 갱신한다.

**Comment by haesoooo** [comment]
### 문제링크
#103 

### 풀이사항
풀이일자 : 240808
풀이시간 : 55분
메모리 : 34176KB
시간 : 436ms
채점 결과 : 정답
예상 문제 유형 : 조합

### 풀이 방법
맵을 입력받을 때 배열 값이 2인 좌표 => combi 리스트에 좌표 저장
배열 값이 1인 좌표 => home 리스트에 좌표 저장
combi 리스트 (모든 치킨집 좌표가 저장됨) 에서 M개의 치킨집만 뽑아서 유지할거다.. 조합 구현 (재귀)
M개를 뽑은 경우의 수마다 남은 치킨집을 새로운 chicken 리스트에 저장하고 이중 반복문으로 각 가정집 (home)에서 모든 치킨집(chicken) 까지의 좌표 간 거리를 구해서 min 값을 비교 갱신하여 sum에 누산
