### ISSUE TITLE
[BaekJoon] 연산자 끼워 넣기

### ISSUE THREAD

**Issue by chanu2** [SSAFY12th/ssafyAlgostudy#60]
문제 링크
https://www.acmicpc.net/problem/14888

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by reasonyi** [comment]
문제 링크
#65 

풀이 사항
풀이 일자: 2024.08.05
풀이 시간: 25분 52초
채점 결과: 정답
예상 문제 유형: DFS

풀이 방법
연산이 완료될 때까지 dfs로 연산을 지속

**Comment by kimdevspace** [comment]
### 문제 링크
#67
### 풀이 사항
풀이 일자 : 240805
풀이 시간 : 20분
채점 결과 : 정답
예상 문제 유형 : DFS

### 풀이 방법
add, sub, mul, div의 개수를 각각 dfs의 매개변수로 넘겨서 0이 되기 전까지 계산을 한다. 수열의 마지막까지 탐색 시 계산 결과의 최대, 최소를 갱신한다

**Comment by kro46** [comment]
## 문제 링크
#71 

## 풀이 사항
풀이 일자: 2024.08.05
풀이 시간: 45분
채점 결과: 정답
예상 문제 유형: DFS

## 풀이 방법
첫 번째 피연산자와 depth=0을 DFS의 파라미터로 넘긴다. DFS는 피연산자와 그 다음번째 피연산자를  +-*/의 개수가 0이 아닌동안 연산을 지속한다. (총 4개의 DFS 갈래가 생성). depth가 N-1이면 min , max 값을 업데이트한다.

**Comment by kimjuheee** [comment]
### 문제링크
#81 

### 풀이사항
풀이일자 : 2024.08.06
풀이시간 : 1시간
채점 결과 : 정답
예상 문제 유형 : DFS

### 풀이방법
각 연산자를 사용할 때마다 연산자 감소시키고 재귀 후에는 다시 증가시킨다.
모든 숫자를 사용한 경우, 결과를 max와 min과 비교하여 최대값과 최소값을 갱신한다.

**Comment by haesoooo** [comment]
### 문제링크
#75

### 풀이사항
풀이일자 : 2024.08.05
풀이시간 : 40분
채점 결과 : 정답
예상 문제 유형 : DFS

### 풀이방법
연산자를 총 개수 (N -1) 만큼 하나의 배열에 받아서 dfs 내부에서 해당 배열의 길이만큼 돌며 재귀를 실행하는 방법 -> 이 때 사용한 연산자는 -1로 표기해둔다. - 노드가 많아지니까 아무래도 오래 걸릴 수밖에 없다.. 
=> 22408KB, 720ms

크기 4의 배열에 사칙연산에 대한 각 연산자 '개수'를 받아서 dfs 내부에서 길이 4만큼의 재귀를 돈다 -> 이 때 소모한 연산자를 감소 연산, 개수가 0이 된 연산자에 대해서는 연산 생략하는 방식으로 진행
=> 18856KB, 144ms
