### ISSUE TITLE
[BaekJoon]로봇 청소기

### ISSUE THREAD

**Issue by chanu2** [SSAFY12th/ssafyAlgostudy#61]
문제 링크
https://www.acmicpc.net/problem/14503

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by sangholee235** [comment]
## 문제 링크
#66 

## 풀이 사항
풀이 일자: 2024.08.05
풀이 시간: 2시간 30분
채점 결과: 정답
예상 문제 유형: BFS 브루트포스 구현

## 풀이 방법
 문제에서 주어진 제한사항을 꼼꼼히 구현하는게 중요한 문제
현재 좌표에서 4방탐색을 한후 청소를 성공했는지 못했는지 여부로 구분하여
후진을 할지 말지 결정하면 된다 나머지는 BFS로 탐색
벽으로 막혀있지 않더라도 맵 구조에따라 전체 청소가 불가능 할 수도 있었습니다.

청소를 성공했는지 여부를 검증하지 않고 BFS탐색을 한다면, 벽에 막혀있지 않는한 
모든 구역을 청소합니다. 또한 BFS문제 이지만 후진 탐색을 진행 할 경우 재귀적 구조를 띕니다.

**Comment by reasonyi** [comment]
문제 링크
#69 

풀이 사항
풀이 일자: 2024.08.05
풀이 시간: 42분 02초
채점 결과: 정답
예상 문제 유형: 구현, 시뮬레이션

풀이 방법
중복되는 코드는 메서드로 구현.
문제의 요구사항에 맞춰 구현.
청소기를 이동하기 위해 dr, dc를 북-동-남-서 순서로 이동할 수 있도록 선언하고, 이를 이용하여 이동할 공간이 맵 이내인지, 청소해야하는 빈 공간인지, 벽인지 체크하여 각각 상황에 맞는 코드 구현

**Comment by kro46** [comment]
## 문제 링크
#79 

## 풀이 사항
풀이 일자: 2024.08.05
풀이 시간: 3시간
채점 결과: 정답
예상 문제 유형: BFS 

## 풀이 방법
이 문제는 4방향 탐색을 성공했는지 안했는지를 따로 저장해두는 변수가 필요. 그래야 후진 알고리즘 적용 가능 -> 이거 생각못해서 오래걸림..
벽이 아닌 공간에서 방향을 바꿔가며 이동할 수 있는 경로 탐색 : BFS
만약 4방향이 모두 막혀있으면 후진
후진을 할 때에는 방문배열 사용X , 벽이 있는지만 검사
마지막으로 더이상 후진할 수 없는 상황(뒤에 벽이 존재) 이면 return

**Comment by chanu2** [comment]
## 문제 링크
#89 

## 풀이 사항
풀이 일자 : 2024.08.06
풀이 시간 : 2시간 
메모리 : 14380KB
시간 : 108ms
채점 결과 : 정답
예상 문제 유형 : 구현

## 풀이 방법
 로봇의 방향을 바꾸는 코드와, 방향을 기준으로 반대편으로 이동하는 코드를 구현하는데 시간이 많이 소요된것 같습니다.

**Comment by kimdevspace** [comment]
### 문제 링크
https://www.acmicpc.net/problem/14503

### 풀이 사항
풀이 일자 : 240808
풀이 시간 : 6try
메모리 : 14503KB
시간 : 108ms
채점 결과 : 정답
예상 문제 유형 : DFS
### 풀이 방법
지문대로 풀다가
지문이 살짝 이상했지만 팀원들 보충 설명 받아 구현했습니다

**Comment by kimjuheee** [comment]
### 문제링크
---
#85

### 풀이사항
---
풀이일자 : 240807
풀이시간 : 4시간
메모리 : 21064KB
시간 : 220ms
채점 결과 : 정답
예상 문제 유형 : 구현

### 풀이 방법
---
문제 의도를 파악하는 데 시간이 오래 걸렸습니다.
isValid 메서드로 주어진 좌표가 경계를 벗어나지 않고 벽이 아닌지 확인한다.
더 이상 청소할 공간이 없으면 후진하여 이전 위치로 돌아간다.
모든 가능한 공간 청소 후, countCleanedCells 에 청소된 셀의 총 개수를 세어 반환한다.

**Comment by haesoooo** [comment]
### 문제 링크
#101

### 풀이 사항
풀이 일자 : 240808
풀이 시간 : 약 3시간
메모리 : 14468KB
시간 : 108ms
채점 결과 : 정답
예상 문제 유형 : DFS

### 풀이 방법
시작 좌표 값을 청소 표시해주고 dfs 진행
dfs 내에서, 4방향을 돌면서 청소 안된 인덱스가 있으면 flag = 1로 처리
flag가 1일 때 ) 직진 case
　- 반시계 회전
　- 4방향에 대해 0이 아닐 때까지 반시계로 돌아주고,, 배열 범위 내 && 청소해야댐 -> 청소해주고 ans 증가 후 재귀
아닐 때 ) 후진 case
    - 후진을 위한 좌표로 변경, 방향은 유지한다
    - 재귀 ㄱㄱ한다
