### ISSUE TITLE
[BaekJoon] 안전 영역

### ISSUE THREAD

**Issue by kimdevspace** [SSAFY12th/ssafyAlgostudy#64]
문제 링크
https://www.acmicpc.net/problem/2468

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by kimdevspace** [comment]
### 문제 링크
#63 
### 풀이 사항
풀이 일자 : 240804
풀이 시간 : 35분
채점 결과 : 정답
예상 문제 유형 : BFS, DFS, 브루트 포스
### 풀이 방법
안전 영역의 기준을 정하기 위한 빗물이 차오르는 높이를 처음에는 못 떠올렸다. N의 높이가 100까지니깐, 처음에는 1부터 100까지의 높이마다 bfs로 안전영역을 구했다. 그런데 이건 최악의 경우니깐 다시 graph[i][j]을 입력받을 때 최댓값을 갱신시켜 최대 높이를 설정해두고 최대 높이만큼만 반복했다.!

**Comment by sangholee235** [comment]
## 문제 링크
#57 

## 풀이 사항
풀이 일자: 2024.08.02
풀이 시간: 30분
채점 결과: 정답
예상 문제 유형: BFS DFS 완전탐색

## 풀이 방법
1. 물의 높이를 0~ 최대 높이까지 완전탐색
2. 물의 높이마다 안전 영역이 몇개인지 세기
3. 최대 안전 영역 return 

물의 높이가 차오른다는 생각이 잘 떠오르지 않았으나 떠올린 이후는 간단한 BFS로 해결되는 문제였습니다.

**Comment by chanu2** [comment]
### 문제 링크
#68 
### 풀이 사항
풀이 일자 : 240805
풀이 시간 : 32분19초
채점 결과 : 정답
예상 문제 유형 : BFS, DFS, 브루트 포스
### 풀이 방법
처음 비가 1~100 까지 올 수 있다고 생각하고 이 차원 배열을 돌면서 bfs로 확인 했다. 틀렸다는 결과가 나왔고 생각해보니 비가 오지 않을 수 있기 때문에 0~100으로 변경하였다.

**Comment by reasonyi** [comment]
### 문제 링크
#83 

### 풀이 사항
풀이 일자: 2024.08.07
풀이 시간: 53분 45초
채점 결과: 정답
예상 문제 유형: BFS/DFS/브루트포스

### 풀이 방법
처음에 문제를 이해 못해서 16분 가량을 문제 이해하는데 사용했다.... -> 책을 많이 읽어야겠다....

- 물의 높이가 아무리 높아도 map에서 가장 높은 위치보다 높으면 탐색을 하는게 소용없으므로, map을 받을 때 map에서 가장 높은 위치를 waterHight에 기록해둔다. 
- waterHight를 1씩 줄여가며 탐색을 반복한다. 
- main에서 맵 전체를 돌다가 안전영역인데 방문하지 않은 위치를 발견했다면 dfs를 호출한다.
- dfs는 호출된 위치에서 이어져있는 영역을 방문하여 visited에 표기한다. 
- main에서 호출한 dfs가 끝나면 안전영역 1개를 센 것으로 sum++하여 표시한다.
- 탐색이 끝나면 그 전까지의 최대 안전 영역 개수와 sum을 비교해 더 큰 값을 저장한다.

**Comment by kro46** [comment]
## 문제 링크
#88 

## 풀이 사항
풀이 일자 : 240807
풀이 시간 : 1시간 40분
채점 결과 : 정답
예상 문제 유형 : BFS, DFS, 브루트 포스

## 풀이 방법
안전 영역의 최대 높이 max_height를 잡기 위해 for문으로 최대값 갱신해서 저장해둠.
rain=0부터 max_height까지 bfs를 도는 횟수 = 안전 영역의 개수로 최대 값을 계속 갱신
-> 이 때 중요한 점 : 방문 배열과 안전 영역의 개수는 BFS를 돌기 전 항상  초기화를 시켜 줘야함. 이걸 안하면 값으로 1만 뱉음

**Comment by haesoooo** [comment]
### 문제 링크
#76

### 풀이 사항
풀이 일자 : 240805
풀이 시간 : 30분
채점 결과 : 정답
예상 문제 유형 : DFS

### 풀이 방법
0~maxlimit (배열 내의 최댓값) 까지 돌며 각 값만큼 비가 올 때 영역 개수의 최댓값을 찾는다.
이 때 매번 visit 배열을 초기화해야함
맵에서, 방문하지 않았고 해당 배열 값이 현재 limit보다 큰 값일 때, 그 배열 인덱스에서 dfs 호출
해당 인덱스부터 4방향 탐색을 하며 영역을 찾아나감, dfs가 끝날 때마다 영역 개수++
초기에, 비가 안 올 수도 있다는 생각을 전혀 못해서,, 반복문을 minlimit부터 시작했다가 오래걸렸다.
=> 19452kb, 284ms

**Comment by kimjuheee** [comment]
### 문제링크
https://github.com/SSAFY12th/ssafyAlgostudy/blob/main/JuHee/Week03/BOJ_2468_%EC%95%88%EC%A0%84%EC%98%81%EC%97%AD.java
커밋 이슈로 인해 링크 첨부합니다 ...

### 풀이사항
풀이일자 : 240807
풀이시간 : 3시간
메모리 : 67712KB
시간 : 480ms
채점 결과 : 정답
예상 문제 유형 : BFS

### 풀이 방법
높이가 h보다 큰 위치이면서 방문하지 않은 경우 BFS 함수 호출한다.
BFS 함수 호출 할 때 마다 안전 지역 개수 증가시킨다. (이 부분을 놓쳤음 ... 문제 읽을 때 블럭으로 구현 순서 꼼꼼하게 작성하기 !)
각 높이에서 계산한 안전 지역 개수와 maxSafeAreas를 비교하여 갱신한다.
