### ISSUE TITLE
[BaekJoon] 톱니바퀴

### ISSUE THREAD

**Issue by sangholee235** [SSAFY12th/ssafyAlgostudy#94]
문제 링크
https://www.acmicpc.net/problem/14891

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by sangholee235** [comment]
### 문제 링크
#91
### 풀이 사항
풀이 일자 : 240808
풀이 시간 : 1시간 40분
채점 결과 : 정답
예상 문제 유형 : 구현
시간 : 124 ms
메모리 : 14292 kb
### 풀이 방법
처음에는 재귀로 톱니바퀴가 연쇄적으로 반응이 일어나는줄 알고 풀었다 
하지만 1회 톱니바퀴가 회전하면 모든 톱니바퀴는 최대 1회 영향을 받는 구조 이다.
그러므로 재귀탐색할 필요없이 최초회전하는 톱니 바퀴를 기준으로 모든 톱니바퀴의 회전 방향만 결정하면 되므로
자원을 아낄 수 있었다.

**Comment by reasonyi** [comment]
### 문제 링크
#107 

### 풀이 사항
풀이 일자: 2024.08.10
풀이 시간: 1시간 5분
채점 결과: 정답
예상 문제 유형: 구현/시뮬레이션
시간: 100ms
메모리:  14304 KB

### 풀이 방법
노드의 삽입삭제를 쉽게 하기위해 LinkedList를 활용하였다. 다만 이 과정에서 LinkedList로 2차원 배열을 만드는 방법을 잘 몰라 많은 시간이 소요되었다.

- 각 톱니바퀴가 어느 방향으로 회전하는지 저장해둘 배열을 만든다.
- 어떤 톱니를 회전시키는지 입력받았을 때, 해당 톱니를 중심으로 오른쪽으로 이동하며 회전 여부를 확인하는 것과, 왼쪽으로 이동하며 회전 여부를 확인하는 것으로 두 번 나누어 for문으로 방향을 알아내고 배열에 저장한다. 이 과정에서 안움직이는 톱니가 있다면 그 다음 톱니는 회전 여부를 고려할 필요가 없으므로, break한다.
-  각 톱니를 회전시킨다. 회전시킬 때는 시계방향의 경우, 맨 뒤 요소를 빼내어 맨 앞으로 삽입하고, 반시계방향의 경우 맨 앞 요소를 빼내어 맨 뒤로 삽입한다.
- 점수를 계산하여 출력한다.

**Comment by kro46** [comment]
## 문제 링크
#109 

## 풀이 사항
풀이 일자 : 240811
풀이 시간 : 3시간
채점 결과 : 정답
예상 문제 유형 : 구현
시간 : 104 ms
메모리 : 14232 kb

## 풀이 방법
- 전체 휠의 N,S극 정보를 담기 위해 이차원 배열 사용
- 회전 방향(반시계 or 시계)에 따른 배열의 원소 이동 메서드 구현
- 이전의 휠이 회전했는지 판단하기 위한 boolean 타입 변수 before_rotate 선언
- 전체 휠의 이동 가능성 검사(이전 휠과 그 다음 휠이 만나는 지점에서 극이 같은지판단)하여 다르면 true, 같으면 false를 boolean 타입 배열 can_rotate 에 삽입
- 현재 휠을 우선 회전
- 오른쪽 휠 회전이 가능한지 검사(can_rotate && before_rotate) , 회전이 가능하면 이전 휠의 반대방향으로 회전 , 그 후 direct*(-1)하여 다음 휠이 회전할 방향 지정
- 오른쪽 휠 검사가 끝나면 왼쪽 휠 검사(이때 direct와 before_rotate값 초기화)
- 최종적으로 전체 휠을 담은 이차원배열을 검사하여 각 배열의 0번째 원소가 1이면 sum 값을 누적계산하여 출력

**Comment by kimdevspace** [comment]
### 문제 링크
<hr>
#110 
### 풀이 사항
<hr>
풀이 일자 : 240811
풀이 시간 : 2시간
채점 결과 : 정답
예상 문제 유형 : 구현
시간 : 104ms
메모리 :  14260kb
### 풀이 방법
<hr>
- 회전할 수 있는 톱니바퀴를 찾아 회전해주기 [ 현재 톱니바퀴의 2번 인덱스와 다음 톱니바퀴의 6번 인덱스가 다르면 회전 ]
- 위를 재귀로 구현하기! 탈출 조건은 맞물려 있는 극이 같을 때 또는 톱니바퀴 개수의 범위 밖일 때
- 톱니바퀴들의 0번 인덱스가 1일 때 점수 계산

tip 👍 방향 잘 고려하기, 현재 회전 방향이 반 시계 방향일 때 바로 이전이나 바로 다음은 시계 방향으로 돌아야 하므로
재귀 함수 인자를 넘겨줄 때 방향에 -부호 붙혀서 넘겨주면 탐색 하는 범위 마다 방향이 바뀌게 됨!

**Comment by kimjuheee** [comment]
문제 링크
#132 

### 풀이 사항
풀이 일자 : 240814
풀이 시간 : 5시간
채점 결과 : 정답
예상 문제 유형 : 구현
시간 : 124ms
메모리 : 14200KB

### 풀이 방법
- 시계방향과 반시계방향으로 회전시키는 함수 각각 만들었다.
- "톱니바퀴를 반시계 방향으로 회전시키면 붙어있는 톱니바퀴들은 시계방향으로 회전하고 반대로 시계방향으로 회전시키면 붙어있는 톱니바퀴들은 반시계 방향으로 회전한다." 는 원리를 이용하였다.
- visited 배열을 사용하여 이미 회전시킨 톱니를 다시 방문하지 않도록 하였다.
