### ISSUE TITLE
[BaekJoon] 퇴사

### ISSUE THREAD

**Issue by sangholee235** [SSAFY12th/ssafyAlgostudy#95]
문제 링크
https://www.acmicpc.net/problem/14501

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by sangholee235** [comment]
### 문제 링크
#91
### 풀이 사항
풀이 일자 : 240808
풀이 시간 : 1시간 40분
채점 결과 : 정답
예상 문제 유형 : 구현
시간 : 124 ms
메모리 : 14292 kb
### 풀이 방법
마지막 상담일자부터 1일까지 역순으로 계산했다 현재일자 + 현재일의 상담일자가
퇴사일을 넘어가면 즉시 리턴하고 그렇지 않다면 
다음날 dp값 vs 현재값 + 현재+소요일의 dp값을 비교하여 더 큰 값 선택하는 방식으로 해결했다

**Comment by kimdevspace** [comment]
### 문제 링크
#115 
### 풀이 사항
풀이 일자 : 240812
풀이 시간 : 2시간
채점 결과 : 정답
예상 문제 유형 : 완전탐색
시간 : 168ms
메모리 : 17704kb
### 풀이 방법
![image](https://github.com/user-attachments/assets/3c97b9b6-3c39-413a-a233-e7e70c0eff7b)
- 상담을 하는 경우와 상담을 하지 않는 경우로 가지를 뻗어 나가면서 탐색한다.
- 상담을 하는 경우는 다음 상담 일자로 갈 때 비용을 계산하면서 상담한 날짜만큼 건너 뛰어 가야함
- 상담을 하지 않는 경우는 다음 상담일자 선택할 때 비용 계산 x
- N+1 일 째가 퇴사날이라면 최댓값 갱신
- 날짜가 N을 넘어버리고 N+1일째가 아니라면 리턴

**Comment by reasonyi** [comment]
문제 링크
#116 

풀이 사항
풀이 일자 : 2024.08.12
풀이 시간 : 29분 38초
채점 결과 : 정답
예상 문제 유형 : DP
시간 : 196ms
메모리 : 14284 kb

풀이 방법
퇴근해야해서 나중에 수정하겠슴다

**Comment by chanu2** [comment]
### 문제 링크
#123 
### 풀이 사항
풀이 일자 : 240813
풀이 시간 : 2시간
채점 결과 : 정답
예상 문제 유형 : bfs
시간 : 124ms
메모리 : 14228kb
### 풀이 방법

- 2의 15승 이기 때문에 완탐이 가능하다고 생각했다.
- 현재 날짜와 퇴사일, 남은 날짜를 기준으로 탐색 진행 
- depth + 상담하는데 걸리는 기간으로 탐색을 진행한다.
- 선택하지 않을 수도 있기 때문에 탐색 추가
- 최댓값 갱신

**Comment by kimjuheee** [comment]
### 문제링크
#126 

### 풀이사항
풀이 일자 : 240813
풀이 시간 : 5시간
채점 결과 : 정답
예상 문제 유형 : 완전탐색, DP
시간 : 128ms
메모리 : 14296KB

### 풀이방법
- DP유형의 문제이지만 완전탐색 방법으로 접근했다.
- 현재 작업을 선택하는 경우와 현재 작업을 선택하지 않는 경우를 분기로 설정하였다.
- money, max._money 비교하여 최대 이익 출력

**Comment by kro46** [comment]
## 문제링크
#129 

## 풀이사항
풀이 일자 : 240813
풀이 시간 : 2시간
채점 결과 : 정답
예상 문제 유형 : 완전탐색, DP
시간 : 124ms
메모리 : 14220KB

## 풀이방법
- 입력받은 수를 저장하기 위해 arr[N][2] 배열 선언
- dp 배열을 N+1로 하나 크게 선언 -> day가 N과 같은 경우에도 계산에 들어가기 때문
- 현재 dp 배열의 i번 값을 i+1로 복사해준다.(Math.max()로 두 원소간의 크기를 비교해서 넣어줘야한다.)
- 이후 만약  현재 날짜 + 일한 후의 날짜 값이 N보다 작거나 같으면 해당하는 일을 선택
- 선택한 일의 날짜만큼 현재 날짜에 더해주고, 돈도 더하여 최대 값을 갱신해준다.
- 위의 과정을 i=0부터 N-1까지 반복한다.
- 마지막으로 최댓값이 저장된 dp[N]을 출력해준다.

**Comment by haesoooo** [comment]
### 문제링크
#127

### 풀이사항
풀이 일자 : 240813
풀이 시간 : 2시간
채점 결과 : 정답
예상 문제 유형 : DP
시간 : 124ms
메모리 : 14212KB

### 풀이방법

점화식을 찾는 것이 핵심인데.. dp 테이블을 생성한다. (각 날짜까지의 이익을 계산하기 위해)
dp[i] = max(i일의 이익 + j일까지의 이익, i일의 이익) 으로 값을 갱신해나감.
이 때 j일까지의 이익은 dp[j]와 같다.

i - j >= T[j] 일 때만 max 계산을 해야한다. j일까지 상담을 하고 i일에 또 할 수 있는지 그 날짜 간격을 계산해야 i일의 이익을 더하는 계산을 할 수 있기 때문이닷
