### ISSUE TITLE
[SWEA] 최대 상금

### ISSUE THREAD

**Issue by sangholee235** [SSAFY12th/ssafyAlgostudy#96]
문제 링크
https://swexpertacademy.com/main/code/problem/problemDetail.do?problemLevel=3&contestProbId=AV15Khn6AN0CFAYD&categoryId=AV15Khn6AN0CFAYD&categoryType=CODE&problemTitle=&orderBy=RECOMMEND_COUNT&selectCodeLang=ALL&select-1=3&pageSize=10&pageIndex=1

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by sangholee235** [comment]
### 문제 링크
#97 
### 풀이 사항
풀이 일자 : 240808
풀이 시간 : 2시간 30분
채점 결과 : 정답
예상 문제 유형 : 완전 탐색
시간 : 299 ms
메모리 : ?? kb
### 풀이 방법
이중 반복문으로 현재 인덱스와 현재 인덱스  + 1 부터 마지막인덱스를 교환한뒤 
DFS 재귀호출을 진행하고 깊이가 바꿀 기회에 닿을때 최대값과 비교하여 갱신한다.

단, 바꿀 기회가 문자열의 길이보다 길게 주어졌을 경우 기회를 문자열의 길이만큼으로 제한한다

제한하지 않을 경우 시간 초과가 발생한다.

**Comment by kro46** [comment]
## 문제 링크
#111 

## 풀이 사항
풀이 일자 : 240812
풀이 시간 : 3시간 30분
채점 결과 : 정답
예상 문제 유형 : DFS/백트래킹
시간 : 397 ms
메모리 : 87844 kb

## 풀이 방법
- 가장 중요한 것 : <string>count가 배열의 길이보다 길면 배열의 길이로 변경해준다</strong> 안그러면 시간초과 발생 - 상호의 아이디어로 해결
- DFS안에서 2중 for문을 사용하여 스왑할  인덱스 2개를 선정
- count만큼 DFS를 호출하여 스왑 진행
- depth가 count와 같으면 현재 배열의 값을 max와 비교 후 최대값 갱신
- 모든 호출이 끝나면 max값 출력

**Comment by chanu2** [comment]
## 문제 링크
#130  

## 풀이 사항
풀이 일자 : 240812
풀이 시간 : 1시간 30분
채점 결과 : 정답
예상 문제 유형 : DFS/백트래킹
시간 : 1520ms
메모리 : 105,912 kb

## 풀이 방법
- 가장 중요한 것 : <string>count가 배열의 길이보다 길면 배열의 길이로 변경해준다</strong> 안그러면 시간초과 발생 - 성태님 아이디어 참고
- 조합을 통해 2개를 고르는 경우의수 
- 조합을 통해 가져온 리스트 순열을 통해서 경우의수 구하기
- for문을 통해서 위치 스왑
- 최대값 갱신

**Comment by kimdevspace** [comment]
### 문제 링크
#134 
### 풀이 사항
풀이 일자 : 240814
풀이 시간 : 4시간 + @
채점 결과 : 정답
예상 문제 유형 : 백트래킹
시간 : 267ms
메모리 : 88,308kb
### 풀이 방법
- [  카드 2개를 조합을 뽑아 교환 ] <---- 이걸 최대 교환 횟수까지 무조건 반복해야 함.
- 최대 교환 횟수는 카드의 개수를 넘으면 중복 발생하기 때문에 시간 초과 발생한다. ; 최대 교환 횟수 <= 카드의 개수
- 카드를 뽑는 경우도 인덱스를 하나씩 밀어서 중복을 방지한다.
1 2 3 에서 0번 인덱스 부터 시작힌다 치면 1 과 2를 바꾸는 경우가 있음. 모두 교환을 하고서 1번 인덱스 교환 차례에 2와 1을 교환 할 필요 없음 !

**Comment by haesoooo** [comment]
### 문제 링크
#127
### 풀이 사항
풀이 일자 : 240813
풀이 시간 : 3시간
채점 결과 : 정답
예상 문제 유형 : 백트래킹
시간 : 166ms
메모리 : 21,820 kb
### 풀이 방법
- 2개를 뽑는다. 단, 오른쪽 숫자가 왼쪽 숫자보다 클 경우에만 ! (21 -> 교환 X, 12-> 21로 교환)
- 단, 그럴 경우에는 54321 처럼 처음부터 가장 크게 정렬된 경우에도 반드시 교환을 해야 한다면, if 문으로 조건을 걸어서 맨 뒤 두자리만 교환시킨다 (1의자리, 10의 자리만)

- C++에서는 교환 횟수가 자릿수보다 크더라도 시간초과가 나지 않았는데, 자바에선 난다 ㅡㅡ 그래서 그거 때문에 또 오래걸렸다.. (교환 횟수 > 자릿수일 경우) 교환 횟수 = 자릿수로 대입
