### ISSUE TITLE
[BaekJoon] 게리맨더링

### ISSUE THREAD

**Issue by chanu2** [SSAFY12th/ssafyAlgostudy#98]
문제 링크
https://www.acmicpc.net/problem/17471

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
메모리 : 00KB
시간 : 00ms
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by chanu2** [comment]
## 문제 링크
#102 

## 풀이 사항
풀이 일자 : 2024.08.08
풀이 시간 : 1시간 30분 
메모리 : 16420KB
시간 : 128ms
채점 결과 : 정답
예상 문제 유형 : BFS,DFS,백트래킹

## 풀이 방법
- 조합을 통해서 각각의 팀을 나눈다.
- bfs를 돌면서 인접한 노드가 팀에 포함되는지 확인 후 bfs를 돈다.
- 팀에 모든 노드를 방문했다면 인구를 더해 리턴 방문하지 않았다면 리턴 한다.
- 최솟값을 갱신한다

**Comment by kimdevspace** [comment]
### 문제 링크
#108 
### 풀이 사항
풀이 일자 : 240810
풀이 시간 : 3일
메모리 : 15596KB
시간 : 132ms
채점 결과 : 정답
예상 문제 유형 : BFS, 백트래킹
### 풀이 방법
- 지역을 두 구역으로 나눈다.
- bfs를 돌면서 나뉜 두 구역마다 연결 되어 있는지 검사를 한다.
- 연결 되어있다면 인구수 차이를 최솟값으로 갱신!

**Comment by kro46** [comment]
## 문제 링크
#120 

## 풀이 사항
풀이 일자 : 2024.08.12
풀이 시간 : 6시간 30분
메모리 : 15580KB
시간 : 124ms
채점 결과 : 정답
예상 문제 유형 : BFS,DFS,백트래킹

## 풀이 방법
- 인접리스트를 생성하여 모든 노드의 연결구조를 저장
- 조합으로 2개의 구역에 들어갈 노드를 선택
- bfs를 돌면서 각 영역에 포함된 노드들이 연결되어 있는지 확인
- 영역의 크기와 연결된 노드의 수가 같으면 각 영역의 인구 수 총합을 반환
- bfs의 결과 영역 내 노드들이 연결되어 있지 않으면 -1을 최종 값으로 갱신
최솟값을 갱신한다

**Comment by sangholee235** [comment]
## 문제 링크
#122 

## 풀이 사항
풀이 일자 : 2024.08.13
풀이 시간 : 1시간 40분 
메모리 : 16140KB
시간 : 140ms
채점 결과 : 정답
예상 문제 유형 : 완전탐색, BFS

## 풀이 방법
1. 완전탐색 조합으로 팀을 배정한다 팀의 수 N - i : N (i < N//2 + 1)  N C i 조합
2. BFS를 통해 각 정점에서 연결돼있으며, 같은 팀인 지역 한 구역으로 묶음
3. 구역이 2개로 나뉘어질때만, 각 구역의 인구 차이를 계산 후 최소값 갱신
4. 2개로 나뉘어 지지 않는 경우 boolean변수를 통해 구분

**Comment by reasonyi** [comment]
### 문제 링크
#125 

### 풀이 사항
풀이 일자: 2024.08.13
풀이 시간: 1시간 49분
메모리 :15676 KB
시간 : 156 ms
채점 결과: 정답
예상 문제 유형: 백트래킹/DFS/BFS

### 풀이 방법
- 구역 선택 시 1개도 선택될 수 있으므로, 종료조건을 정해줘야한다. 종료조건은 main에서 정하여, dfs를 호출할 때 같이 인자로 넘겨준다.
- 조합으로 구역을 선택하여 선택한 구역과 선택하지 않은 구역으로 나눈다.
- 종료조건에 도달하면, 두 구역이 유효한지 bfs를 호출하여 확인한다.
- 각 구역이 서로 이어져있다면 true, 이어져있지 않다면 false를 return한다.
- 두 구역이 유효하다면, 각 구역의 인구수를 구하여 차의 절대값과 최소값을 비교하여 갱신한다.
- 만약 최소값이 변하지 않는 경우, -1로 변경한다.
- 최소값을 출력한다.

**Comment by haesoooo** [comment]
### 문제 링크
#135

### 풀이 사항
풀이 일자: 2024.08.15
풀이 시간: 1시간 25분
메모리 : 16272KB
시간 : 128 ms
채점 결과: 정답
예상 문제 유형: 조합, BFS

### 풀이 방법
- 조합으로  floor(N / 2)개 뽑기
- 뽑은 idx는 선거구 1, 아닌 idx는 선거구 2로 할당
- 선거구 내의 구역 연결 확인
- 선거구 1, 선거구 2 각각 연결되어 있다면 인원 계산


- 두 선거구로 나눌 수 없는 경우 : 모든 연산이 끝났는데도 비교한 min값이 처음에 초기화한 값이랑 동일한 지로 확인
- 선거구 내의 구역들이 연결되어 있는지 확인하는 방법 : bfs를 돌고 나서, [queue에 노드가 저장된 횟수 == 선거구의 구역 개수] 를 확인한다
- 처음에는 입력받고 연결 정보 (간선)가 없으면 -1 바로 출력하도록 했는데 34%에서 계속 틀렸다

**Comment by kimjuheee** [comment]
### 문제 링크
#133 

### 풀이 사항
풀이 일자 : 240814
풀이 시간 : 5시간 + α 
메모리 : 15804KB
시간 : 164ms
채점 결과 : 정답
예상 문제 유형 : 그래프 탐색, 조합 

### 풀이 방법
- N을 입력받고 각 구역의 인구수(people)와 연결된 구역(graph)들을 저장한다.

- divide 함수로 백트랙킹을 통해 N개의 구역을 두 선거구로 나누는 모든 경우의 수를 탐색한다.

- selected 배열을 통해 현재 구역이 어떤 선거구에 속하는지 표시한다.

- check 함수로 BFS를 통해 해당 선거구의 모든 구역이 연결되어 있는지 판단한다.

- 두 선거구가 모두 연결된 경우에만 getPeople 함수를 통해 두 선거구의 인구수 차이를 계산한다.

- 모든 경우의 수를 탐색한 후, 구할 수 있는 최소 인구수 차이를 출력한다.

- 모든 경우가 불가능한 경우 -1 리턴한다.
